export type MentorTier = 'Top Student' | 'Young Professional'
export type MentorPhotoStatus = 'ready' | 'missing'

export type Mentor = {
  slug: string
  name: string
  tier: MentorTier | null
  title?: string
  credentials: string[]
  expertise: string[]
  linkedIn?: string
  portrait: AssetKey
  photoStatus: MentorPhotoStatus
}

const mentor = (entry: Mentor): Mentor => entry

export const mentors: Mentor[] = [
  mentor({ slug: 'navira-putri', name: 'Navira Putri', tier: 'Young Professional', title: 'Senior Associate Consultant at Altha Consulting', credentials: ['Co-Founder Strativate', 'Next Generation Women Leaders Asia Pacific 2026 — McKinsey & Company', 'Winner of 30+ business and research competitions'], expertise: ['Lintas kategori kompetisi'], linkedIn: 'https://www.linkedin.com/in/navira-putri-apriliani-063476207/', portrait: 'mentors.navira-putri.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'safira-aulia', name: 'Safira Aulia', tier: 'Young Professional', title: 'Associate Finance Graduate Program at Grab', credentials: ['Highest GPA in Management, FEB Universitas Indonesia 2024', 'Former Case Team Assistant at Boston Consulting Group', 'Winner of 30+ business case competitions'], expertise: ['Finance'], linkedIn: 'https://www.linkedin.com/in/safiraaulia5/', portrait: 'mentors.safira-aulia.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'aqil-drajat', name: 'Aqil Drajat', tier: 'Young Professional', title: 'Key Account Executive at LUXASIA ID', credentials: ['1st Most Outstanding Student Vocational UI 2024', 'L’Oréal Brandstorm Favorite Winner 2024', 'Winner of 10+ business and marketing competitions'], expertise: ['Marketing', 'Business Plan'], linkedIn: 'https://www.linkedin.com/in/aqildrajat/', portrait: 'mentors.aqil-drajat.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'ilham-hakim', name: 'Ilham Hakim', tier: 'Young Professional', credentials: ['Winner of 10+ business competitions'], expertise: ['Business Plan', 'Business Case', 'Marketing'], linkedIn: 'https://www.linkedin.com/in/ilhamlh/', portrait: 'mentors.ilham-hakim.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'rohananda-devi', name: 'Rohananda Devi', tier: 'Young Professional', credentials: ['Winner of 5 business competitions'], expertise: ['Lintas kategori kompetisi'], linkedIn: 'https://www.linkedin.com/in/rohanandadevi/', portrait: 'mentors.rohananda-devi.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'ratna-puspa', name: 'Ratna Puspa', tier: 'Young Professional', credentials: ['Winner of 10+ business competitions'], expertise: ['Business Case'], linkedIn: 'https://www.linkedin.com/in/ratnapuspaamelia/', portrait: 'mentors.ratna-puspa.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'ivonne-qiu', name: 'Ivonne Qiu', tier: 'Young Professional', credentials: ['Winner of 5+ business competitions'], expertise: ['Business Case', 'Economics', 'Finance'], portrait: 'mentors.ivonne-qiu.portrait', photoStatus: 'missing' }),
  mentor({ slug: 'fajri-alan', name: 'Fajri Alan', tier: 'Young Professional', credentials: ['Winner of 5+ business competitions'], expertise: ['Business Case', 'Finance', 'Accounting'], portrait: 'mentors.fajri-alan.portrait', photoStatus: 'missing' }),
  mentor({ slug: 'deanna', name: 'Deanna', tier: 'Young Professional', credentials: ['Winner of 5+ business competitions'], expertise: ['Business Plan', 'Business Case', 'Marketing'], portrait: 'mentors.deanna.portrait', photoStatus: 'missing' }),
  mentor({ slug: 'cherien-stevie', name: 'Cherien Stevie', tier: 'Top Student', title: 'Market Research Intern at Wordpanel', credentials: ['The Most Potential Student FEB UI 2026', 'NUS NOC Student Awardee', 'Winner of 20+ business competitions'], expertise: ['Marketing', 'Finance', 'Business Plan'], linkedIn: 'https://www.linkedin.com/in/cherien-stevie/', portrait: 'mentors.cherien-stevie.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'm-iqbal-banoza', name: 'M. Iqbal Banoza', tier: 'Young Professional', title: 'Management Trainee at BCA Life', credentials: ['Top 3 Mahasiswa Berprestasi Universitas Indonesia 2025', 'Winner of 30+ business and research competitions', 'Founder and Chief of National Debate Community Center'], expertise: ['Business Plan', 'Business Case', 'Marketing', 'Proposal Development'], linkedIn: 'https://www.linkedin.com/in/m-iqbal-banoza/', portrait: 'mentors.m-iqbal-banoza.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'terry-kuron', name: 'Terry Kuron', tier: 'Young Professional', title: 'Relations at PT Pertamina Hulu Indonesia', credentials: ['Founder of Dear You Planner', '1st Winner — National Marketing Plan Competition 2024', 'Winner of 10+ business and marketing competitions'], expertise: ['Business Plan', 'Business Case', 'Marketing', 'Proposal Development'], linkedIn: 'https://www.linkedin.com/in/terry29/', portrait: 'mentors.terry-kuron.portrait', photoStatus: 'missing' }),
  mentor({ slug: 'akmal-faqih', name: 'Akmal Faqih', tier: 'Top Student', credentials: ['Winner of 10+ business and marketing competitions'], expertise: ['Business Case', 'Finance'], linkedIn: 'https://www.linkedin.com/in/akmal-faqih-567131247/', portrait: 'mentors.akmal-faqih.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'syona-hana', name: 'Syona Hana', tier: 'Top Student', title: 'Shopee Apprenticeship Program — Business Development', credentials: ['Director of Consulting at 180 Degrees Consulting UI', '1st Place — Mahasiswa Berprestasi FTUI, Business Category 2025', 'Winner of 30+ business and research competitions'], expertise: ['Business Plan', 'Business Case', 'Marketing', 'Proposal Development'], linkedIn: 'https://www.linkedin.com/in/syonahana/', portrait: 'mentors.syona-hana.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'lubna-qumilaila', name: 'Lubna Qumilaila', tier: 'Young Professional', title: 'SAP Student Training and Rotation (STAR) Program', credentials: ['President of 180 Degrees Consulting UI 2026', 'CIMB Niaga Kejar Mimpi Scholarship Awardee Batch 2025', 'Winner of 5+ business case competitions'], expertise: ['Business Plan', 'Business Case', 'Marketing', 'Proposal Development'], linkedIn: 'https://www.linkedin.com/in/lubnaalkaysa/', portrait: 'mentors.lubna-qumilaila.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'albert-lukas', name: 'Albert Lukas', tier: 'Young Professional', credentials: ['Winner of 10+ business and marketing competitions'], expertise: ['Marketing', 'Business Plan', 'Business Case'], portrait: 'mentors.albert-lukas.portrait', photoStatus: 'missing' }),
  mentor({ slug: 'ruth-debora', name: 'Ruth Debora', tier: 'Top Student', credentials: ['Winner of 10+ business competitions'], expertise: ['Business Case', 'Business Plan'], portrait: 'mentors.ruth-debora.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'muhammad-harits', name: 'Muhammad Harits', tier: 'Top Student', credentials: ['Winner of 10+ business competitions'], expertise: ['Marketing', 'Business Plan', 'Business Case'], portrait: 'mentors.muhammad-harits.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'rafi-aurelian', name: 'Rafi Aurelian', tier: 'Top Student', credentials: ['Winner of 10+ business and research competitions'], expertise: ['Business Case', 'Business Plan'], linkedIn: 'https://www.linkedin.com/in/rafiaurelian/', portrait: 'mentors.rafi-aurelian.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'ratu-hanifa', name: 'Ratu Hanifa', tier: 'Top Student', credentials: ['Winner of 10+ business and marketing competitions'], expertise: ['Business Case', 'Finance'], portrait: 'mentors.ratu-hanifa.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'william-philip', name: 'William Philip', tier: 'Top Student', title: 'Research Intern at Badan Pusat Statistik', credentials: ['Most Potential Student FEB UI 2023', 'Highest GPA FEB UI 2023', '1st Winner — Policy Brief Competition, 22nd Economix FEB UI × Tony Blair Institute'], expertise: ['Business Plan', 'Business Case'], linkedIn: 'https://www.linkedin.com/in/williampk/', portrait: 'mentors.william-philip.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'alvaro-zhafran', name: 'Alvaro Zhafran', tier: 'Top Student', title: 'Commercial Finance Intern at Siemens Mobility', credentials: ['2nd Place — AlphaSights Asia Case Competition 2026', '1st Winner — UI Makarapreneur Business Case Competition 2025', 'Winner of 5+ business case competitions'], expertise: ['Business Case', 'Finance'], linkedIn: 'https://www.linkedin.com/in/alvaro-zhafran-prananta-a5986a220/', portrait: 'mentors.alvaro-zhafran.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'adrian-nicholas', name: 'Adrian Nicholas', tier: 'Top Student', title: 'Product Development Intern at Allianz Indonesia', credentials: ['1st Most Outstanding Student at FMIPA ITB', 'Project Leader — Gandeng Foundation × education technology startup', 'Winner of 5+ business case and consulting competitions'], expertise: ['Business Case', 'Business Plan'], portrait: 'mentors.adrian-nicholas.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'naura-tsabita-wibowo', name: 'Naura Tsabita Wibowo', tier: 'Top Student', title: 'Founder of Charmiez.id', credentials: ['Global Winner — Lenovo Innovation Challenge', 'Asia Representative Finalist — De La Vega Global Entrepreneurship Award', 'Winner of 10+ business and marketing competitions'], expertise: ['Business Plan', 'Marketing', 'Business Case'], linkedIn: 'https://www.linkedin.com/in/naura-tsabita-wibowo-859428303/', portrait: 'mentors.naura-tsabita-wibowo.portrait', photoStatus: 'ready' }),
  mentor({ slug: 'faluna-a-janitra', name: 'Faluna A. Janitra', tier: null, credentials: ['Winner of 10+ business and marketing competitions'], expertise: ['Business Plan', 'Marketing', 'Business Case'], portrait: 'mentors.faluna-a-janitra.portrait', photoStatus: 'missing' }),
  mentor({ slug: 'm-sultan-perkasa', name: 'M. Sultan Perkasa', tier: null, credentials: ['Winner of 5+ business and accounting competitions'], expertise: [], portrait: 'mentors.m-sultan-perkasa.portrait', photoStatus: 'missing' }),
]

export const featuredMentors = mentors.slice(0, 3)
import type { AssetKey } from './asset-registry'
