'use client'

import {CalendarDays,Clock3,ExternalLink,Eye,Layers3,UsersRound,X} from 'lucide-react'
import {useEffect,useMemo,useRef,useState} from 'react'
import {CopyTextButton} from '@/components/dashboard/copy-text-button'
import {MentoringCompetitionEditor} from '@/components/mentoring/mentoring-competition-editor'
import {MentoringSessionPreferences} from '@/components/mentoring/mentoring-session-preferences'
import type {PrivateMentoringSessionFocusView} from '@/lib/private-mentoring/types'
import {intensiveStageLabels,type IntensiveEngagementView,type IntensiveSessionView} from '@/lib/intensive-mentoring/types'

function shortId(value:string){return value.length>12?value.slice(0,8)+'…'+value.slice(-4):value}
function schedule(session:IntensiveSessionView){if(!session.scheduledStartAt)return'Belum dijadwalkan';return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(session.scheduledStartAt))}
function status(value:IntensiveSessionView['status']){return({awaiting_focus:'Menunggu review',awaiting_scheduling:'Siap dijadwalkan',scheduled:'Terjadwal',completed:'Selesai',cancelled:'Dibatalkan'} as const)[value]}
function tone(value:IntensiveSessionView['status']){if(value==='completed')return'positive';if(value==='scheduled')return'info';if(value==='cancelled')return'danger';return'warning'}

export function IntensiveMentoringEngagements({engagements,sessionFocuses:_sessionFocuses}:{engagements:IntensiveEngagementView[];sessionFocuses:PrivateMentoringSessionFocusView[]}){
 const detailRef=useRef<HTMLDialogElement>(null)
 const [selectedEngagementId,setSelectedEngagementId]=useState(engagements[0]?.engagementId??'')
 const [selectedSessionId,setSelectedSessionId]=useState<string|null>(null)
 const engagement=useMemo(()=>engagements.find(item=>item.engagementId===selectedEngagementId)??engagements[0]??null,[engagements,selectedEngagementId])
 const selectedSession=useMemo(()=>selectedSessionId?engagements.flatMap(item=>item.sessions).find(session=>session.sessionId===selectedSessionId)??null:null,[engagements,selectedSessionId])
 useEffect(()=>{if(selectedSessionId&&!selectedSession)setSelectedSessionId(null)},[selectedSession,selectedSessionId])
 useEffect(()=>{const d=detailRef.current;if(!d)return;if(selectedSession&&!d.open)d.showModal();if(!selectedSession&&d.open)d.close()},[selectedSession])
 if(!engagements.length)return <section className="workspace-card empty-card"><Layers3/><div><h3>Belum ada engagement Intensive Mentoring</h3><p>Program Intensive yang sudah dibayar akan muncul di sini sebagai satu engagement terstruktur.</p></div></section>
 return <section className="intensive-engagement-workspace">
  <div className="mentoring-enrollment-selector" role="list" aria-label="Pilih engagement Intensive Mentoring">{engagements.map(item=><button type="button" role="listitem" key={item.engagementId} className={'mentoring-enrollment-summary '+(item.engagementId===engagement?.engagementId?'active':'')} onClick={()=>setSelectedEngagementId(item.engagementId)}><span className="mentoring-enrollment-summary__eyebrow">Intensive Mentoring</span><strong>{item.programName}</strong><span>{item.primaryMentorName||'Mentor utama belum ditetapkan'}</span><small>{item.baselineSessionsPerMonth?'Baseline '+item.baselineSessionsPerMonth+' sesi/bulan':'Baseline disesuaikan program'} · {item.sessions.length} sesi tercatat</small></button>)}</div>
  {engagement?<>
   <section className="workspace-card intensive-engagement-overview">
    <div className="section-heading"><div><p className="kicker">Engagement Intensive</p><h3>{engagement.programName}</h3><p>Program berkelanjutan. Baseline adalah intensitas layanan, bukan batas keras jumlah sesi.</p></div><div className="button-row"><span className="ops-status ops-status--info">{engagement.status==='active'?'Aktif':engagement.status==='completed'?'Selesai':'Dibatalkan'}</span><span className="ops-status ops-status--info">{intensiveStageLabels[engagement.programStage]}</span></div></div>
    <div className="intensive-engagement-metrics"><div><UsersRound/><span>Dedicated Mentor</span><strong>{engagement.primaryMentorName||'Menunggu admin'}</strong></div><div><Clock3/><span>Baseline</span><strong>{engagement.baselineSessionsPerMonth?engagement.baselineSessionsPerMonth+' sesi/bulan':'Custom'}</strong></div><div><CalendarDays/><span>Sesi tercatat</span><strong>{engagement.sessions.length}</strong></div><div><CalendarDays/><span>Mulai</span><strong>{new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(engagement.startedAt))}</strong></div></div>
    <MentoringCompetitionEditor kind="intensive" parentId={engagement.engagementId}/>
    {engagement.currentActivity?<p className="intensive-progress-summary"><strong>Aktivitas saat ini</strong>{engagement.currentActivity}</p>:null}{engagement.progressSummary?<p className="intensive-progress-summary"><strong>Ringkasan progres</strong>{engagement.progressSummary}</p>:null}
    <div className="intensive-addons"><strong>Dukungan tambahan</strong>{engagement.addOns.length?<div>{engagement.addOns.map(addon=><span key={addon.entitlementId??addon.code} className="intensive-addon-chip">{addon.name}</span>)}</div>:<p className="muted">Tidak ada add-on terpasang pada engagement ini.</p>}</div>
   </section>
   <section className="workspace-card mentoring-session-table-section">
    <div className="section-heading"><div><p className="kicker">Sesi Intensive</p><h3>Riwayat dan jadwal sesi</h3></div></div>
    <div className="ops-table-wrap"><table className="ops-table mentee-session-table" data-testid="intensive-session-table"><thead><tr><th>Sesi</th><th>Topik / Fokus</th><th>Mentor</th><th>Jadwal</th><th>Status</th><th>Zoom</th><th>Detail</th></tr></thead><tbody>{engagement.sessions.length?engagement.sessions.map(session=><tr key={session.sessionId}><td data-label="Sesi"><strong>Sesi {session.sessionNumber}</strong><small><code title={session.sessionId}>{shortId(session.sessionId)}</code></small></td><td data-label="Topik / Fokus"><strong>{session.resolvedTopic||session.focusName||session.menteeTopicRequest||'Diserahkan ke Admin'}</strong><small>{session.topicStatus==='pending_review'?'Menunggu review admin':session.topicStatus==='confirmed'?'Sudah ditinjau':'Belum ditinjau'}</small></td><td data-label="Mentor">{session.mentorName||engagement.primaryMentorName||'Menunggu admin'}</td><td data-label="Jadwal">{schedule(session)}</td><td data-label="Status"><span className={'ops-status ops-status--'+tone(session.status)}>{status(session.status)}</span></td><td data-label="Zoom">{session.status==='scheduled'&&session.meetingUrl?<a className="button button-primary button-compact" href={session.meetingUrl} target="_blank" rel="noopener noreferrer" aria-label={'Buka Zoom sesi '+session.sessionNumber}><ExternalLink/>Zoom</a>:<span className="muted">Belum tersedia</span>}</td><td data-label="Detail"><button type="button" className="button button-outline button-compact" onClick={()=>setSelectedSessionId(session.sessionId)}><Eye/>Detail</button></td></tr>):<tr className="responsive-table-empty"><td colSpan={7}>Admin belum menambahkan sesi untuk engagement ini.</td></tr>}</tbody></table></div>
   </section>
  </>:null}
  {selectedSession?<dialog ref={detailRef} className="ops-dialog" aria-labelledby="intensive-detail-title" onCancel={event=>{event.preventDefault();setSelectedSessionId(null)}} onClose={()=>setSelectedSessionId(null)}><div className="ops-dialog__surface"><header className="ops-dialog__header"><div><p className="kicker">Detail sesi Intensive</p><h2 id="intensive-detail-title">Sesi {selectedSession.sessionNumber}</h2></div><button type="button" className="ops-icon-button" onClick={()=>setSelectedSessionId(null)} aria-label="Tutup detail"><X/></button></header><dl className="session-detail-grid"><div><dt>Program</dt><dd>{engagement?.programName}</dd></div><div><dt>Mentor</dt><dd>{selectedSession.mentorName||engagement?.primaryMentorName||'Menunggu admin'}</dd></div><div><dt>Jadwal</dt><dd>{schedule(selectedSession)}</dd></div><div><dt>Durasi</dt><dd>{selectedSession.durationMinutes} menit</dd></div></dl><MentoringSessionPreferences kind="intensive" sessionId={selectedSession.sessionId} role="mentee"/><details className="mentoring-audit-details"><summary>Detail tambahan</summary><div className="session-reference-row"><code>{selectedSession.sessionId}</code><CopyTextButton value={selectedSession.sessionId} label="Salin Session ID"/></div></details>{selectedSession.meetingUrl?<div className="mentor-detail-meeting-actions"><a className="button button-primary" href={selectedSession.meetingUrl} target="_blank" rel="noopener noreferrer"><ExternalLink/>Buka Zoom</a><CopyTextButton value={selectedSession.meetingUrl} label="Salin link Zoom"/></div>:null}</div></dialog>:null}
 </section>
}
