import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import test from 'node:test'
const path='supabase/migrations/202609150004_google_calendar_mentoring_scheduling.sql'
function sql(){assert.equal(existsSync(path),true,'calendar scheduling must use a forward-only migration');return readFileSync(path,'utf8')}
test('migration isolates OAuth credentials from profiles and authenticated table reads',()=>{const value=sql();assert.match(value,/create table public\.google_calendar_connections/i);assert.match(value,/encrypted_refresh_token/i);assert.doesNotMatch(value,/alter table public\.profiles[\s\S]*refresh_token/i);assert.match(value,/revoke all on table public\.google_calendar_connections[\s\S]*from public, anon, authenticated/i)})
test('migration links one calendar integration row to each mentoring session with explicit sync state and meeting override',()=>{const value=sql();assert.match(value,/create table public\.private_mentoring_session_calendar_integrations/i);for(const field of ['google_event_id','google_ical_uid','provider_meeting_url','manual_meeting_url','sync_status','sync_error'])assert.match(value,new RegExp(field,'i'));assert.match(value,/session_id uuid primary key/i)})
test('scheduling is concurrency safe and validates declared availability plus conflicts',()=>{const value=sql();assert.match(value,/exclude using gist[\s\S]*tstzrange/i);assert.match(value,/mentor_availability_rules/i);assert.match(value,/for update/i);assert.match(value,/scheduled_start_at < now\(\)|p_scheduled_start_at <= now\(\)/i);assert.match(value,/admin_schedule_private_mentoring_session/i)})
test('role RPCs keep mentee and mentor session reads isolated',()=>{const value=sql();assert.match(value,/list_my_private_mentoring_sessions_v2/i);assert.match(value,/list_my_mentor_private_mentoring_sessions/i);assert.match(value,/e\.mentee_id = auth\.uid\(\)/i);assert.match(value,/s\.mentor_id = auth\.uid\(\)/i)})
test('raw Google event details are not exposed through admin scheduling context',()=>{const value=sql();const fn=value.match(/create (?:or replace )?function public\.admin_get_private_mentoring_slot_context[\s\S]*?\$\$;/i)?.[0]??'';assert.ok(fn);assert.doesNotMatch(fn,/event_title|description|attendees|meeting_url/i);assert.match(fn,/availability/i);assert.match(fn,/strativate_busy/i)})
test('calendar session projections expose mentor timezone for clear role displays',()=>{const value=sql();for(const name of ['list_my_private_mentoring_sessions_v2','list_my_mentor_private_mentoring_sessions','list_admin_private_mentoring_calendar_sessions']){const start=value.indexOf(`function public.${name}`);assert.notEqual(start,-1);const next=value.indexOf('$$;',start);const fn=value.slice(start,next);assert.match(fn,/mentor_timezone/i,`${name} should return mentor timezone`)}})
test('admin slot context limits declared availability to each mentor current and next week horizon',()=>{const value=sql();const fn=value.match(/create (?:or replace )?function public\.admin_get_private_mentoring_slot_context[\s\S]*?\$\$;/i)?.[0]??'';assert.ok(fn);assert.match(fn,/week_start_date\s+in\s*\([\s\S]*?date_trunc\('week',[\s\S]*?\+\s*7/i)})
