import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import test from 'node:test'
const read=(path:string)=>readFileSync(path,'utf8')
const migration='supabase/migrations/202609200005_intensive_mentoring_operations.sql'
const commerceMigration='supabase/migrations/202609210001_intensive_custom_offers_and_guarantee_commerce.sql'

test('Intensive domain separates paid entitlement from flexible operational engagements and sessions',()=>{
 const sql=read(migration)
 assert.match(sql,/create table if not exists public\.intensive_mentoring_engagements/i)
 assert.match(sql,/base_entitlement_id uuid not null unique references public\.intensive_mentoring_entitlements/i)
 assert.match(sql,/create table if not exists public\.intensive_mentoring_sessions/i)
 assert.match(sql,/engagement_id uuid not null references public\.intensive_mentoring_engagements/i)
 assert.match(sql,/mentor_id uuid references public\.mentor_profiles\(user_id\)/i)
 assert.match(sql,/creation_source text not null default 'admin_added'/i)
 const addStart=sql.indexOf('function public.admin_add_intensive_mentoring_session')
 const addEnd=sql.indexOf('$$;',addStart)
 const addFn=sql.slice(addStart,addEnd)
 assert.match(addFn,/coalesce\(max\(session_number\),0\)\+1/i)
 assert.match(addFn,/baselineSessionsPerMonth/i)
 assert.doesNotMatch(addFn,/update public\.orders|update public\.order_items|total_amount|unit_price_amount/i)
 assert.doesNotMatch(addFn,/session_number\s*[<>]=?\s*v_eng\.baseline_sessions_per_month/i)
})

test('historical entitlement grouping never guesses ambiguous add-ons',()=>{
 const sql=read(migration)
 assert.match(sql,/every paid package\/bundle entitlement owns exactly one base engagement/i)
 assert.match(sql,/candidate_count=1/i)
 assert.match(sql,/entitlement_kind='add_on' and addon\.engagement_id is null/i)
 assert.match(sql,/admin_attach_intensive_add_on/i)
 assert.match(sql,/same paid order has exactly one base Intensive engagement/i)
 assert.doesNotMatch(sql,/update public\.orders set|update public\.order_items set/i)
})

test('bundle add-ons are projected inside the engagement even without separate add-on order items',()=>{
 const sql=read(migration)
 assert.match(sql,/intensive_engagement_add_ons_json/i)
 assert.match(sql,/base\.entitlement_kind='bundle'/i)
 assert.match(sql,/intensive_mentoring_bundle_items bi/i)
 assert.match(sql,/bi\.item_type='add_on'/i)
 assert.match(sql,/not exists\([\s\S]*attached\.engagement_id=g\.id/i)
})

test('Intensive RLS and security-definer operations keep owner mentor and admin boundaries',()=>{
 const sql=read(migration)
 for(const table of ['intensive_mentoring_engagements','intensive_mentoring_sessions','intensive_mentoring_session_events','intensive_mentoring_engagement_events'])assert.match(sql,new RegExp('alter table public\\.'+table+' enable row level security','i'))
 assert.match(sql,/intensive_sessions_owner_read[\s\S]*g\.mentee_id=auth\.uid\(\)/i)
 assert.match(sql,/intensive_sessions_mentor_read[\s\S]*mentor_id=auth\.uid\(\)/i)
 assert.match(sql,/admin_set_intensive_primary_mentor[\s\S]*public\.is_admin\(\)/i)
 assert.match(sql,/admin_schedule_intensive_mentoring_session[\s\S]*public\.is_admin\(\)/i)
 assert.match(sql,/security definer set search_path=''/i)
})

test('Intensive scheduling reuses availability rules and checks Private plus Intensive conflicts',()=>{
 const sql=read(migration)
 const start=sql.indexOf('function public.admin_schedule_intensive_mentoring_session')
 const end=sql.indexOf('$$;',start)
 const fn=sql.slice(start,end)
 assert.match(fn,/mentor_availability_rules/i)
 assert.match(fn,/private_mentoring_sessions/i)
 assert.match(fn,/intensive_mentoring_sessions/i)
 assert.match(fn,/private_mentoring_enrollments/i)
 assert.match(fn,/intensive_mentoring_engagements/i)
 assert.match(fn,/tstzrange/i)
 assert.match(fn,/duration_minutes/i)
})

test('program progress uses the six source-backed stages and writes engagement audit',()=>{
 const sql=read(migration)
 for(const stage of ['goal_setting','initial_assessment','guided_development','practice_application','review_refinement','final_evaluation'])assert.ok(sql.includes(stage),stage)
 assert.match(sql,/create table if not exists public\.intensive_mentoring_engagement_events/i)
 assert.match(sql,/program_progress_updated/i)
 const types=read('lib/intensive-mentoring/types.ts')
 for(const label of ['Penetapan Tujuan','Asesmen Awal','Pengembangan Terarah','Praktik dan Penerapan','Review dan Penyempurnaan','Final Evaluation'])assert.ok(types.includes(label),label)
})

test('catalog values stay source-backed while approved guarantee products are active and sellable',()=>{
 const sql=read(migration)
 const forward=read(commerceMigration)
 const seed=read('supabase/migrations/202609160005_intensive_catalog_seed.sql')
 assert.match(sql,/code='INTENSIVE'[\s\S]*?sessions_per_month=4|sessions_per_month=4[\s\S]*?code='INTENSIVE'/i)
 assert.match(sql,/1150000/);assert.match(sql,/1400000/);assert.match(sql,/2200000/);assert.match(sql,/2800000/)
 assert.match(sql,/INTERNATIONAL_COMPETITION/);assert.match(sql,/pricing_mode='consultation'/)
 assert.match(sql,/WIN_GUARANTEE_PROTECTION[\s\S]*?is_active=true|is_active=true[\s\S]*?WIN_GUARANTEE_PROTECTION/i)
 assert.match(sql,/COMPETITION_ASSURANCE[\s\S]*?is_active=true|is_active=true[\s\S]*?COMPETITION_ASSURANCE/i)
 assert.doesNotMatch(sql,/requires separate legal\/business approval before activation|must remain recorded until legal approval/i)
 assert.match(forward,/WIN_GUARANTEE_PROTECTION[\s\S]*500000|500000[\s\S]*WIN_GUARANTEE_PROTECTION/)
 assert.match(forward,/COMPETITION_ASSURANCE[\s\S]*3000000|3000000[\s\S]*COMPETITION_ASSURANCE/)
 assert.match(forward,/drop trigger if exists intensive_legal_blocked_add_on_guard/)
 assert.match(forward,/drop trigger if exists intensive_legal_blocked_bundle_guard/)
 assert.match(seed,/SKILL_BUILDER/);assert.match(seed,/COMPETITION_READY/);assert.match(seed,/COMPETITION_ASSURANCE/)
})

test('user mentoring is mode-switched and Intensive is engagement-centric with nested add-ons',()=>{
 const workspace=read('components/dashboard/mentoring-workspace.tsx')
 const intensive=read('components/dashboard/intensive-mentoring-engagements.tsx')
 const privateUi=read('components/dashboard/private-mentoring-sessions.tsx')
 assert.match(workspace,/role="tablist"/)
 assert.match(workspace,/Private Mentoring \(/)
 assert.match(workspace,/Intensive Mentoring \(/)
 assert.match(intensive,/Dukungan tambahan/)
 assert.match(intensive,/Baseline/)
 assert.match(intensive,/intensiveStageLabels/)
 assert.match(intensive,/data-testid="intensive-session-table"/)
 assert.match(intensive,/CopyTextButton value=\{selectedSession\.sessionId\}/)
 const table=intensive.slice(intensive.indexOf('data-testid="intensive-session-table"'),intensive.indexOf('editingSessionId?'))
 assert.doesNotMatch(table,/CopyTextButton/)
 assert.match(privateUi,/selectedEnrollmentId/)
 assert.match(privateUi,/mentoring-enrollment-selector/)
})

test('admin operations expose mode switch primary mentor flexible add session and shared session operations',()=>{
 const workspace=read('components/admin/admin-mentoring-session-workspace.tsx')
 const admin=read('components/admin/intensive-mentoring-session-management.tsx')
 assert.match(workspace,/Private Mentoring/)
 assert.match(workspace,/Intensive Mentoring/)
 assert.match(admin,/admin_set_intensive_primary_mentor/)
 assert.match(admin,/admin_add_intensive_mentoring_session/)
 assert.match(admin,/Tambah sesi/)
 assert.match(admin,/admin_set_intensive_program_stage/)
 assert.match(admin,/AdminScheduleDialog[\s\S]*mentoringKind="intensive"/)
 assert.match(admin,/AdminSessionOperations[\s\S]*mentoringKind="intensive"/)
 assert.match(admin,/admin_attach_intensive_add_on/)
})

test('mentor projection combines Private and Intensive while table keeps copy controls out of scanning rows',()=>{
 const server=read('lib/mentor/dashboard-server.ts')
 const table=read('components/mentor/dashboard/mentor-assignments.tsx')
 const detail=read('components/mentor/dashboard/mentor-detail-dialogs.tsx')
 assert.match(server,/list_my_mentor_private_mentoring_sessions/)
 assert.match(server,/list_my_mentor_intensive_mentoring_sessions/)
 assert.match(table,/Jenis mentoring/)
 assert.match(table,/Intensive/)
 assert.doesNotMatch(table,/CopyTextButton/)
 assert.match(detail,/CopyTextButton/)
 assert.match(detail,/Dukungan tambahan/)
})

test('calendar and Zoom webhook route Intensive sessions through their own persistence',()=>{
 const server=read('lib/calendar/server.ts')
 const calendar=read('components/calendar/role-calendar.tsx')
 const webhook=read('app/api/webhooks/zoom/route.ts')
 const sql=read(migration)
 assert.match(server,/list_admin_intensive_mentoring_calendar_sessions/)
 assert.match(server,/list_my_intensive_mentoring_calendar_sessions/)
 assert.match(server,/list_my_mentor_intensive_mentoring_sessions/)
 assert.match(calendar,/mentoringType/)
 assert.match(calendar,/\/api\/admin\/\$\{kind\}-mentoring/)
 assert.match(webhook,/intensive_mentoring_session_calendar_integrations/)
 assert.match(sql,/service_get_zoom_meeting_context[\s\S]*service_get_intensive_zoom_meeting_context/i)
 assert.match(sql,/notify_intensive_mentoring_integration_changes/i)
})

test('catalog admin and Cart Link no longer expose obsolete legal-blocked copy',()=>{
 const catalog=read('components/admin/intensive-mentoring-management.tsx')
 const cart=read('components/admin/commerce-cart-link-management.tsx')
 assert.doesNotMatch(catalog,/legal blocked|requires legal approval|tetap nonaktif sampai/i)
 assert.doesNotMatch(cart,/Item legal-blocked|tetap tercatat di katalog admin, tetapi tidak muncul/i)
 assert.match(catalog,/Syarat, ketentuan, dan asesmen kelayakan berlaku/)
 assert.match(cart,/Penawaran Internasional/)
})

test('all historical Intensive policies are rerun-safe and obsolete guarantee guards stay removed',()=>{
 const sql=read(migration)
 const policies=[
  'intensive_engagement_owner_read','intensive_engagement_admin_read','intensive_engagement_mentor_read',
  'intensive_sessions_owner_read','intensive_sessions_admin_read','intensive_sessions_mentor_read',
  'intensive_session_events_owner_read','intensive_session_events_admin_read','intensive_session_events_mentor_read',
  'intensive_engagement_events_owner_read','intensive_engagement_events_admin_read','intensive_engagement_events_mentor_read',
 ]
 for(const policy of policies){
  assert.match(sql,new RegExp('drop policy if exists '+policy+' on public\\.','i'),policy)
  assert.equal((sql.match(new RegExp('create policy '+policy+' on public\\.','gi'))??[]).length,1,policy)
 }
 assert.match(sql,/drop trigger if exists intensive_legal_blocked_add_on_guard/)
 assert.match(sql,/drop trigger if exists intensive_legal_blocked_bundle_guard/)
 assert.doesNotMatch(sql,/create trigger intensive_legal_blocked_(?:add_on|bundle)_guard/)
})

test('International custom offer is an authoritative recipient-bound Shared Commerce source',()=>{
 const sql=read(commerceMigration)
 assert.match(sql,/create table if not exists public\.intensive_mentoring_custom_offers/)
 assert.match(sql,/final_price_amount bigint not null/)
 assert.match(sql,/create table if not exists public\.intensive_mentoring_custom_offer_items/)
 assert.match(sql,/item_type in \('add_on','benefit'\)/)
 assert.match(sql,/intensive_mentoring_custom_offer/)
 assert.match(sql,/resolve_commerce_item/)
 assert.match(sql,/International custom offer belongs to another mentee/)
 assert.match(sql,/create or replace function public\.create_order_from_cart/)
 assert.match(sql,/status='converted'/)
 assert.match(sql,/entitlement_kind in\('package','bundle','add_on','custom_offer'\)/)
 assert.match(sql,/Paid International Intensive custom offer/)
 assert.match(sql,/'custom_offer'::text/)
 assert.match(sql,/supportType/)
})

test('admin Intensive UI uses engagement table, centered config dialog, explicit edit states and blank add-session duration',()=>{
 const admin=read('components/admin/intensive-mentoring-session-management.tsx')
 const css=read('app/operations-dashboard.css')
 assert.match(admin,/intensive-engagement-table/)
 assert.match(admin,/intensive-config-dialog/)
 assert.match(admin,/editingDedicatedMentor/)
 assert.match(admin,/editingProgramProgress/)
 assert.match(admin,/editingSessionTopic/)
 assert.match(admin,/editingSessionMentor/)
 assert.match(admin,/addingSession/)
 assert.match(admin,/Aktivitas saat ini/)
 assert.match(admin,/value=\{duration\}/)
 assert.doesNotMatch(admin,/setDuration\('75'\)|useState\('75'\)|placeholder="75"/)
 assert.match(admin,/white-space:nowrap|intensive-reload-button/)
 assert.match(css,/\.intensive-config-dialog\{position:fixed!important;inset:0!important;margin:auto!important/)
 assert.match(css,/grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/)
 assert.match(css,/\.intensive-config-card \.ops-form-stack\{[^}]*display:grid[^}]*gap:16px/)
 assert.match(css,/\.intensive-config-actions\{[^}]*gap:10px[^}]*margin-top:2px/)
 assert.match(css,/\.intensive-config-card \.ops-form-stack>\.intensive-config-actions\{margin-top:2px\}/)
 assert.match(css,/\.intensive-config-actions \.button[^}]*white-space:nowrap/)
})

test('Intensive session detail defaults to read surfaces with independent topic and mentor editors',()=>{
 const admin=read('components/admin/intensive-mentoring-session-management.tsx')
 const css=read('app/operations-dashboard.css')
 assert.match(admin,/className="ops-dialog intensive-session-detail-dialog"/)
 assert.match(admin,/editingSessionTopic\?/)
 assert.match(admin,/editingSessionMentor\?/)
 assert.match(admin,/Status topik/)
 assert.match(admin,/Edit topik/)
 assert.match(admin,/Simpan topik/)
 assert.match(admin,/Edit mentor/)
 assert.match(admin,/Simpan mentor sesi/)
 assert.match(admin,/Jadwal/)
 assert.match(admin,/setScheduleId\(session\.sessionId\)/)
 assert.match(admin,/resetSessionTopicDraft/)
 assert.match(admin,/resetSessionMentorDraft/)
 assert.match(css,/\.intensive-session-section\{/)
 assert.match(css,/\.intensive-session-read-grid\{/)
 assert.match(css,/\.intensive-session-action-row\{/)
 assert.match(css,/\.intensive-session-action-row \.button[^}]*white-space:nowrap/)
})

test('International offer admin workflow defaults to view mode and reuses Cart Link checkout',()=>{
 const ui=read('components/admin/intensive-international-offer-management.tsx')
 assert.match(ui,/type Mode='create'\|'view'\|'edit'/)
 assert.match(ui,/mode==='view'/)
 assert.match(ui,/Simpan penawaran/)
 assert.match(ui,/Buat Cart Link/)
 assert.match(ui,/commerceItemIds:\[activeOffer\.offer_id\]/)
 assert.match(ui,/p_final_price_amount:amount/)
 assert.match(ui,/p_add_on_ids:selectedAddOns/)
 assert.match(ui,/p_benefits:benefits/)
})
