'use client'

import { useEffect, useMemo, useState } from 'react'
import { Bell, CalendarDays, Check, ChevronRight, Clock3, LayoutDashboard, Menu, UsersRound, X } from 'lucide-react'
import { DemoOrder, readOrders, readState, writeState } from '@/lib/demo-store'
import { useAccount } from '@/components/auth/account-provider'
import { SignOut } from '@/components/auth/sign-out'
import { displayName } from '@/lib/auth/rules'
import { displayLabel } from '@/lib/labels'
import { displayDemoLabel } from '@/lib/demo-labels'
import { ProfileForm } from '@/components/auth/profile-form'
import { BrandLogo } from '@/components/brand/brand-logo'

const nav = ['Overview', 'Calendar', 'Assignments', 'My Mentees', 'Programs', 'Availability', 'Session History', 'Notifications', 'Profile']
const sessions = [{ time: '09:00', type: 'Private Mentoring', student: 'Aqil Farrukh', topic: 'Kasus Bisnis' }, { time: '13:00', type: 'Intensive Mentoring', student: 'Sarah Rahman', topic: 'Modul 3' }, { time: '19:00', type: 'Private Mentoring', student: 'Dimas Prakoso', topic: 'Tinjauan Presentasi Bisnis' }]

export default function MentorDashboard() {
  const account = useAccount()
  const [section, setSection] = useState('Overview'); const [orders, setOrders] = useState<DemoOrder[]>([]); const [mobile, setMobile] = useState(false)
  useEffect(() => setOrders(readOrders()), [])
  const assignments = useMemo(() => orders.filter((order) => order.type === 'Private Mentoring' || order.type === 'Intensive Mentoring'), [orders])
  const accept = (id: string) => { const state = readState(); const order = state.orders.find((item) => item.id === id); const next = { ...state, orders: state.orders.map((item) => item.id === id ? { ...item, status: 'MENTOR_ASSIGNED' as const, fulfillmentStatus: 'ACTIVE' as const, mentor: item.mentor || 'Mentor yang ditugaskan' } : item), engagements: state.engagements.map((item) => item.orderId === id ? { ...item, assignmentStatus: 'Assigned' as const, status: 'ACTIVE' as const, mentor: order?.mentor || item.mentor } : item) }; writeState(next); setOrders(next.orders) }
  return <div className="role-shell mentor-shell"><aside className={`role-sidebar ${mobile ? 'open' : ''}`}><div className="role-brand"><BrandLogo /> <button onClick={() => setMobile(false)} className="role-close"><X /></button></div><div className="role-person"><span className="role-avatar blue">{displayName(account).slice(0, 2)}</span><div><strong>{displayName(account)}</strong><small>Akun mentor</small></div></div><nav>{nav.map((item) => <button className={section === item ? 'active' : ''} key={item} onClick={() => { setSection(item); setMobile(false) }}>{item === 'Overview' ? <LayoutDashboard /> : item === 'Calendar' ? <CalendarDays /> : item === 'My Mentees' ? <UsersRound /> : <Clock3 />}{displayLabel(item)}{item === 'Assignments' && assignments.some((o) => o.status === 'ASSIGNMENT_PENDING') && <b>1</b>}</button>)}</nav><div className="role-sidebar-bottom"><button>Bantuan & dukungan</button><SignOut /></div></aside>{mobile && <button className="role-scrim" onClick={() => setMobile(false)} aria-label="Tutup menu" />}<main className="role-main"><header className="role-topbar"><button className="role-menu" onClick={() => setMobile(true)}><Menu /></button><span className="role-context">{displayLabel(section)}</span><div className="role-actions"><Bell /><span className="role-avatar blue small">{displayName(account).slice(0, 2)}</span></div></header><div className="role-content"><div className="role-title"><div><p className="kicker">Senin, 17 Agustus 2026</p><h1>Selamat siang, {displayName(account)}.</h1><p>Berikut jadwal mengajar dan tugas peserta yang perlu Anda tinjau.</p></div><button className="button button-primary">Atur ketersediaan</button></div>{section === 'Overview' && <MentorOverview assignments={assignments} />}{section === 'Assignments' && <AssignmentPanel assignments={assignments} accept={accept} />}{section === 'Calendar' && <CalendarPanel />}{section === 'My Mentees' && <MenteePanel assignments={assignments} />}{section === 'Availability' && <Availability />}{section === 'Programs' && <Programs />}{section === 'Session History' && <History />}{section === 'Notifications' && <Notifications />}{section === 'Profile' && <ProfileForm />}</div></main></div>
}
function MentorOverview({ assignments }: { assignments: DemoOrder[] }) { return <><div className="metric-grid four"><Metric label="Sesi hari ini" value="2" /><Metric label="Sesi mendatang minggu ini" value="5" /><Metric label="Peserta aktif" value={String(Math.max(4, assignments.length))} /><Metric label="Waktu tersedia" value="8 jam" /></div><div className="role-grid mentor-grid"><section className="role-card"><div className="role-card-heading"><div><p className="kicker">Jadwal hari ini</p><h2>Jalani hari dengan terarah.</h2></div><button className="text-link">Lihat kalender <ChevronRight /></button></div><div className="session-timeline">{sessions.map((session) => <div className="mentor-session" key={session.time}><time>{session.time}</time><span className="session-dot" /><div><small>{displayLabel(session.type)}</small><h3>{session.student}</h3><p>{session.topic}</p></div><button className="text-link">Lihat <ChevronRight /></button></div>)}</div></section><section className="role-card mentor-note"><p className="kicker">Catatan mengajar</p><h2>Pertanyaan yang tepat membentuk peserta yang lebih siap.</h2><p>Tinjau hipotesis peserta sebelum setiap sesi, lalu gunakan lima menit pertama untuk mempersempit masalah.</p><button className="button button-outline">Buka catatan sesi</button></section></div></> }
function Metric({ label, value }: { label: string; value: string }) { return <section className="metric-card"><span>{label}</span><strong>{value}</strong><small>dibanding minggu lalu <em>+12%</em></small></section> }
function AssignmentPanel({ assignments, accept }: { assignments: DemoOrder[]; accept: (id: string) => void }) { return <><RolePageTitle eyebrow="Permintaan penugasan" title="Bersiap untuk mendampingi peserta." detail="Terima peserta dan program yang sesuai dengan keahlian serta ketersediaan Anda." /><div className="assignment-board">{assignments.map((order) => <section className="role-card assignment-card" key={order.id}><div><p className="kicker">{order.status === 'ASSIGNMENT_PENDING' ? 'Penugasan mentoring baru' : 'Penugasan aktif'}</p><h2>{order.customer}</h2><p>{displayDemoLabel(order.title)} · {order.sessions} sesi</p></div><span className="status-pill">{displayLabel(order.status)}</span><dl><div><dt>Kompetisi</dt><dd>{displayDemoLabel(order.subject)}</dd></div><div><dt>Jadwal mulai yang disarankan</dt><dd>{displayDemoLabel(order.schedule)}</dd></div><div><dt>Tujuan peserta</dt><dd>Struktur analisis kasus yang lebih tajam dan penyampaian yang percaya diri.</dd></div></dl>{order.status === 'ASSIGNMENT_PENDING' && <div className="button-row"><button className="button button-primary" onClick={() => accept(order.id)}><Check /> Terima penugasan</button><button className="button button-ghost">Tolak</button></div>}</section>)}</div></> }
function CalendarPanel() { return <><RolePageTitle eyebrow="Kalender" title="Jadwal mingguan dalam satu tampilan." detail="Lihat sesi terkonfirmasi, jadwal mengajar, waktu yang diblokir, dan waktu luang Anda." /><section className="role-card week-calendar"><div className="calendar-toolbar"><button>‹</button><strong>17–23 Agustus 2026</strong><button>›</button><span className="calendar-view active">Minggu</span><span className="calendar-view">Bulan</span><span className="calendar-view">Agenda</span></div><div className="week-grid">{['Sen 17', 'Sel 18', 'Rab 19', 'Kam 20', 'Jum 21', 'Sab 22'].map((day, i) => <div key={day}><small>{day}</small><div className={`calendar-block block-${i % 3}`} style={{ marginTop: `${42 + i * 18}px` }}><strong>{displayLabel(i % 2 ? 'Intensive Mentoring' : 'Private Mentoring')}</strong><span>{i % 2 ? '13:00' : '19:00'} · Aqil</span></div></div>)}</div></section></> }
function MenteePanel({ assignments }: { assignments: DemoOrder[] }) { return <><RolePageTitle eyebrow="Peserta saya" title="Peserta yang Anda dampingi." detail="Informasi mentoring yang Anda perlukan untuk sesi yang bermanfaat." /><div className="table-card"><div className="table-head"><span>Peserta</span><span>Program</span><span>Tujuan</span><span>Progres</span><span>Sesi berikutnya</span></div>{assignments.map((o) => <div className="table-row" key={o.id}><strong>{o.customer}</strong><span>{displayDemoLabel(o.title)}</span><span>{displayDemoLabel(o.subject)}</span><span>{o.completed}/{o.sessions} sesi</span><span>{displayDemoLabel(o.schedule)}</span></div>)}</div></> }
function Availability() { return <><RolePageTitle eyebrow="Ketersediaan" title="Buka waktu terbaik Anda untuk sesi." detail="Peserta dan admin hanya melihat waktu yang Anda buka." /><section className="role-card availability-list">{['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'].map((day, i) => <div key={day}><strong>{day}</strong><span>{i === 1 ? 'Tidak tersedia' : i === 5 ? '10:00–14:00' : '18:00–21:00'}</span><button className="text-link">Ubah <ChevronRight /></button></div>)}</section></> }
function Programs() { return <><RolePageTitle eyebrow="Program" title="Portofolio mengajar Anda." detail="Lihat program dan format pembelajaran yang sedang Anda ampu." /><div className="role-grid cards-3">{['Penugasan Mentoring Privat', 'Mentoring Intensif Kasus Bisnis', 'Kelas Besar Kasus Bisnis'].map((p, i) => <section className="role-card" key={p}><p className="kicker">{i === 0 ? 'Mentoring perorangan' : i === 1 ? 'Program terstruktur' : 'Kelas per angkatan'}</p><h2>{p}</h2><p className="muted">{i + 2} peserta aktif · {i + 1} sesi mendatang</p><button className="text-link">Buka program <ChevronRight /></button></section>)}</div></> }
function History() { return <><RolePageTitle eyebrow="Riwayat sesi" title="Sesi yang telah diselesaikan." detail="Tinjau sesi terbaru dan catat perkembangan peserta." /><div className="table-card"><div className="table-head"><span>Tanggal</span><span>Peserta</span><span>Program</span><span>Topik</span><span>Status</span></div>{sessions.map((s, i) => <div className="table-row" key={s.student}><strong>0{i + 8} Agu 2026</strong><span>{s.student}</span><span>{displayLabel(s.type)}</span><span>{s.topic}</span><span className="status-pill">Selesai</span></div>)}</div></> }
function Notifications() { return <><RolePageTitle eyebrow="Notifikasi" title="Pantau setiap pembaruan." detail="Pembaruan penugasan, jadwal, dan peserta muncul di sini." /><section className="role-card notification-stack">{['Penugasan mentoring baru diterima', 'Aqil menjadwalkan sesi untuk Kamis', 'Jadwal Kelas Besar diperbarui'].map((n) => <div key={n}><Bell /><div><strong>{n}</strong><p>Hari ini · 09:24</p></div><ChevronRight /></div>)}</section></> }
function RolePageTitle({ eyebrow, title, detail }: { eyebrow: string; title: string; detail: string }) { return <div className="role-page-title"><p className="kicker">{eyebrow}</p><h2>{title}</h2><p>{detail}</p></div> }
