'use client'

import Link from 'next/link'
import { use, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, CreditCard } from 'lucide-react'
import { getCatalogItem } from '@/lib/catalog'
import { completePurchase, createPendingOrder, readState, writeState } from '@/lib/demo-store'

export default function CheckoutPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = use(params); const item = getCatalogItem(slug); const [step, setStep] = useState<'configure' | 'review' | 'success'>('configure'); const [subject, setSubject] = useState('L’Oréal Brandstorm'); const [goal, setGoal] = useState('Competition Focused'); const [mentor, setMentor] = useState('Let Strativate match me'); const [schedule, setSchedule] = useState('Weekday evenings'); if (!item) return null
  if (item.informationOnly) return <main className="detail-page"><h1>{item.title}</h1><p className="detail-lede">{item.detail}</p><Link href={`/program/${item.slug}`} className="primary-cta">View program <ArrowRight size={16} /></Link></main>
  const pay = () => { const pending = createPendingOrder({ type: item.category === 'Digital Products' ? 'Digital Product' : item.category, title: item.title, productId: item.id, subject, price: item.priceLabel, amount: item.price, sessions: item.sessions, goal, mentorPreference: mentor, packageLabel: item.sessions ? `${item.sessions} Sessions` : 'Digital access' }); const next = completePurchase(readState(), pending, 'QRIS'); writeState(next); setStep('success') }
  if (step === 'success') return <main className="checkout-page success-page"><div className="success-mark"><Check size={28} /></div><p className="kicker">PURCHASE CONFIRMED</p><h1>You are ready for<br /><em>what is next.</em></h1><p>Your {item.title} purchase is now connected to your Strativate account. {item.sessions ? 'We will notify you when your mentor is assigned.' : 'Your digital product is ready in your Library.'}</p><div className="success-actions"><Link href="/dashboard" className="primary-cta">Go to My Programs <ArrowRight size={16} /></Link><Link href="/explore" className="secondary-cta">Explore another program</Link></div></main>
  return <main className="checkout-page"><Link href={`/program/${item.slug}`} className="back-link"><ArrowLeft size={15} /> Back to program</Link><div className="checkout-head"><p className="kicker">CHECKOUT / {step === 'configure' ? 'CONFIGURE' : 'REVIEW'}</p><h1>{item.title}</h1><div className="checkout-steps"><span className="current">1 Configure</span><span className={step === 'review' ? 'current' : ''}>2 Review</span><span>3 Success</span></div></div>{step === 'configure' ? <section className="checkout-layout"><div className="config-panel"><h2>Make this engagement yours.</h2><p>Choose the context that helps us prepare the right experience.</p><label>What are you working toward?<input value={subject} onChange={(event) => setSubject(event.target.value)} /></label><label>Primary goal<div className="choice-row">{['Competition Focused', 'Career Growth', 'Build confidence'].map((option) => <button key={option} className={goal === option ? 'selected' : ''} onClick={() => setGoal(option)}>{option}</button>)}</div></label>{item.sessions > 0 && <><label>Mentor preference<div className="choice-row">{['Let Strativate match me', 'Albert L.', 'Navira A.'].map((option) => <button key={option} className={mentor === option ? 'selected' : ''} onClick={() => setMentor(option)}>{option}</button>)}</div></label><label>Preferred schedule<div className="choice-row">{['Weekday evenings', 'Weekend mornings', 'Flexible scheduling'].map((option) => <button key={option} className={schedule === option ? 'selected' : ''} onClick={() => setSchedule(option)}>{option}</button>)}</div></label></>}</div><aside className="checkout-card"><p className="kicker">Your selection</p><h2>{item.title}</h2><p>{item.format} · {item.duration}</p><div className="checkout-total"><span>Total</span><strong>{item.priceLabel}</strong></div><button className="primary-cta full" onClick={() => setStep('review')}>Review order <ArrowRight size={16} /></button></aside></section> : <section className="review-card"><div><p className="kicker">ORDER REVIEW</p><h2>Everything looks right?</h2><p>{subject} · {goal} · {item.sessions ? `${mentor} · ${schedule}` : 'Digital access'}</p></div><div className="checkout-total"><span>Total due</span><strong>{item.priceLabel}</strong></div><button className="primary-cta full" onClick={pay}><CreditCard size={16} /> Pay with QRIS</button></section>}</main>
}
