export const COMPETITION_RECOGNITION_LOGO_BUCKET = 'marketing-editorial'
export const COMPETITION_RECOGNITION_LOGO_PREFIX = 'recognition-logos/'
export const COMPETITION_RECOGNITION_LOGO_WIDTH = 1000
export const COMPETITION_RECOGNITION_LOGO_HEIGHT = 800
export const COMPETITION_RECOGNITION_LOGO_ASPECT_RATIO =
  COMPETITION_RECOGNITION_LOGO_WIDTH / COMPETITION_RECOGNITION_LOGO_HEIGHT
export const COMPETITION_RECOGNITION_LOGO_MAX_FILE_SIZE = 5 * 1024 * 1024
export const COMPETITION_RECOGNITION_LOGO_ALLOWED_TYPES = new Set<string>([
  'image/jpeg',
  'image/png',
  'image/webp',
])
