'use client'

import { useEffect, useMemo, useState } from 'react'
import { Bell, CalendarDays, Check, ChevronRight, Clock3, LayoutDashboard, Menu, UsersRound, X } from 'lucide-react'
import { DemoOrder, readOrders, writeOrders } from '@/lib/demo-store'
import { DemoRoleSwitcher } from '@/components/demo-role-switcher'

const nav = ['Overview', 'Calendar', 'Assignments', 'My Mentees', 'Programs', 'Availability', 'Session History', 'Notifications', 'Profile']
const sessions = [{ time: '09:00', type: 'Private Mentoring', student: 'Aqil Farrukh', topic: 'Business Case' }, { time: '13:00', type: 'Intensive Mentoring', student: 'Sarah Rahman', topic: 'Module 3' }, { time: '19:00', type: 'Private Mentoring', student: 'Dimas Prakoso', topic: 'Pitch Deck Review' }]

export default function MentorDashboard() {
  const [section, setSection] = useState('Overview'); const [orders, setOrders] = useState<DemoOrder[]>([]); const [mobile, setMobile] = useState(false)
  useEffect(() => setOrders(readOrders()), [])
  const assignments = useMemo(() => orders.filter((order) => order.mentor === 'Albert L.'), [orders])
  const accept = (id: string) => { const next = orders.map((order) => order.id === id ? { ...order, status: 'MENTOR_ASSIGNED' as const } : order); writeOrders(next); setOrders(next) }
  return <div className="role-shell mentor-shell"><DemoRoleSwitcher /><aside className={`role-sidebar ${mobile ? 'open' : ''}`}><div className="role-brand"><span className="brand-mark">S</span> strativate <button onClick={() => setMobile(false)} className="role-close"><X /></button></div><div className="role-person"><span className="role-avatar blue">AL</span><div><strong>Albert L.</strong><small>Mentor account</small></div></div><nav>{nav.map((item) => <button className={section === item ? 'active' : ''} key={item} onClick={() => { setSection(item); setMobile(false) }}>{item === 'Overview' ? <LayoutDashboard /> : item === 'Calendar' ? <CalendarDays /> : item === 'My Mentees' ? <UsersRound /> : <Clock3 />}{item}{item === 'Assignments' && assignments.some((o) => o.status === 'ASSIGNMENT_PENDING') && <b>1</b>}</button>)}</nav><div className="role-sidebar-bottom"><button>Help & support</button><button onClick={() => window.location.href = '/'}>Log out</button></div></aside>{mobile && <button className="role-scrim" onClick={() => setMobile(false)} aria-label="Close menu" />}<main className="role-main"><header className="role-topbar"><button className="role-menu" onClick={() => setMobile(true)}><Menu /></button><span className="role-context">{section}</span><div className="role-actions"><Bell /><span className="role-avatar blue small">AL</span></div></header><div className="role-content"><div className="role-title"><div><p className="kicker">Tuesday, 17 August 2026</p><h1>Good afternoon, Albert.</h1><p>Here&apos;s the teaching schedule and student work that need your attention.</p></div><button className="button button-primary">Set availability</button></div>{section === 'Overview' && <MentorOverview assignments={assignments} />}{section === 'Assignments' && <AssignmentPanel assignments={assignments} accept={accept} />}{section === 'Calendar' && <CalendarPanel />}{section === 'My Mentees' && <MenteePanel assignments={assignments} />}{section === 'Availability' && <Availability />}{section === 'Programs' && <Programs />}{section === 'Session History' && <History />}{section === 'Notifications' && <Notifications />}{section === 'Profile' && <Profile />}</div></main></div>
}
function MentorOverview({ assignments }: { assignments: DemoOrder[] }) { return <><div className="metric-grid four"><Metric label="Today&apos;s sessions" value="2" /><Metric label="Upcoming this week" value="5" /><Metric label="Active mentees" value={String(Math.max(4, assignments.length))} /><Metric label="Available hours" value="8h" /></div><div className="role-grid mentor-grid"><section className="role-card"><div className="role-card-heading"><div><p className="kicker">Today&apos;s schedule</p><h2>Keep the day intentional.</h2></div><button className="text-link">View calendar <ChevronRight /></button></div><div className="session-timeline">{sessions.map((session) => <div className="mentor-session" key={session.time}><time>{session.time}</time><span className="session-dot" /><div><small>{session.type}</small><h3>{session.student}</h3><p>{session.topic}</p></div><button className="text-link">View <ChevronRight /></button></div>)}</div></section><section className="role-card mentor-note"><p className="kicker">Teaching note</p><h2>Strong questions create stronger competitors.</h2><p>Review the student&apos;s hypothesis before each session, then spend the first five minutes making the problem smaller.</p><button className="button button-outline">Open session notes</button></section></div></> }
function Metric({ label, value }: { label: string; value: string }) { return <section className="metric-card"><span>{label}</span><strong>{value}</strong><small>vs. last week <em>+12%</em></small></section> }
function AssignmentPanel({ assignments, accept }: { assignments: DemoOrder[]; accept: (id: string) => void }) { return <><RolePageTitle eyebrow="Assignment requests" title="Work worth preparing for." detail="Accept the students and programs that match your expertise and availability." /><div className="assignment-board">{assignments.map((order) => <section className="role-card assignment-card" key={order.id}><div><p className="kicker">{order.status === 'ASSIGNMENT_PENDING' ? 'New mentoring assignment' : 'Active assignment'}</p><h2>{order.customer}</h2><p>{order.title} · {order.sessions} sessions</p></div><span className="status-pill">{order.status.replaceAll('_', ' ')}</span><dl><div><dt>Competition</dt><dd>{order.subject}</dd></div><div><dt>Suggested start</dt><dd>{order.schedule}</dd></div><div><dt>Student goal</dt><dd>Sharper case structure and confident delivery.</dd></div></dl>{order.status === 'ASSIGNMENT_PENDING' && <div className="button-row"><button className="button button-primary" onClick={() => accept(order.id)}><Check /> Accept assignment</button><button className="button button-ghost">Decline</button></div>}</section>)}</div></> }
function CalendarPanel() { return <><RolePageTitle eyebrow="Calendar" title="A clear week, in one view." detail="Confirmed sessions, class teaching, blocked time, and your open capacity." /><section className="role-card week-calendar"><div className="calendar-toolbar"><button>‹</button><strong>17–23 August 2026</strong><button>›</button><span className="calendar-view active">Week</span><span className="calendar-view">Month</span><span className="calendar-view">Agenda</span></div><div className="week-grid">{['Mon 17', 'Tue 18', 'Wed 19', 'Thu 20', 'Fri 21', 'Sat 22'].map((day, i) => <div key={day}><small>{day}</small><div className={`calendar-block block-${i % 3}`} style={{ marginTop: `${42 + i * 18}px` }}><strong>{i % 2 ? 'Intensive Mentoring' : 'Private Mentoring'}</strong><span>{i % 2 ? '13:00' : '19:00'} · Aqil</span></div></div>)}</div></section></> }
function MenteePanel({ assignments }: { assignments: DemoOrder[] }) { return <><RolePageTitle eyebrow="My mentees" title="People you are helping move." detail="Only the mentoring context you need for meaningful sessions." /><div className="table-card"><div className="table-head"><span>Student</span><span>Program</span><span>Goal</span><span>Progress</span><span>Next session</span></div>{assignments.map((o) => <div className="table-row" key={o.id}><strong>{o.customer}</strong><span>{o.title}</span><span>{o.subject}</span><span>{o.completed}/{o.sessions} sessions</span><span>{o.schedule}</span></div>)}</div></> }
function Availability() { return <><RolePageTitle eyebrow="Availability" title="Make your best hours bookable." detail="Students and admins will only see slots you choose to open." /><section className="role-card availability-list">{['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'].map((day, i) => <div key={day}><strong>{day}</strong><span>{i === 1 ? 'Unavailable' : i === 5 ? '10:00–14:00' : '18:00–21:00'}</span><button className="text-link">Edit <ChevronRight /></button></div>)}</section></> }
function Programs() { return <><RolePageTitle eyebrow="Programs" title="Your teaching portfolio." detail="See the programs and formats where your expertise is currently active." /><div className="role-grid cards-3">{['Private Mentoring Assignments', 'Business Case Intensive', 'Business Case Big Class'].map((p, i) => <section className="role-card" key={p}><p className="kicker">{i === 0 ? '1:1 mentoring' : i === 1 ? 'Structured program' : 'Cohort class'}</p><h2>{p}</h2><p className="muted">{i + 2} active participants · {i + 1} upcoming sessions</p><button className="text-link">Open program <ChevronRight /></button></section>)}</div></> }
function History() { return <><RolePageTitle eyebrow="Session history" title="The work already done." detail="Review your recent sessions and keep a record of progress." /><div className="table-card"><div className="table-head"><span>Date</span><span>Student</span><span>Program</span><span>Topic</span><span>Status</span></div>{sessions.map((s, i) => <div className="table-row" key={s.student}><strong>0{i + 8} Aug 2026</strong><span>{s.student}</span><span>{s.type}</span><span>{s.topic}</span><span className="status-pill">Completed</span></div>)}</div></> }
function Notifications() { return <><RolePageTitle eyebrow="Notifications" title="Keep the handoffs clean." detail="Assignment, schedule, and student updates appear here." /><section className="role-card notification-stack">{['New mentoring assignment received', 'Aqil booked a session for Thursday', 'Big Class schedule updated'].map((n) => <div key={n}><Bell /><div><strong>{n}</strong><p>Today · 09:24</p></div><ChevronRight /></div>)}</section></> }
function Profile() { return <><RolePageTitle eyebrow="Profile" title="Your mentor profile." detail="Keep your expertise and teaching preferences current." /><section className="role-card profile-form"><span className="profile-large-avatar blue">AL</span><div><label>Name<input defaultValue="Albert L." /></label><label>Expertise<input defaultValue="Business Case, Marketing, Strategy" /></label><button className="button button-primary">Save profile</button></div></section></> }
function RolePageTitle({ eyebrow, title, detail }: { eyebrow: string; title: string; detail: string }) { return <div className="role-page-title"><p className="kicker">{eyebrow}</p><h2>{title}</h2><p>{detail}</p></div> }
