'use client'

import { ExternalLink, Pencil, Plus, Save, Trash2 } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useOperationalInvalidation } from '@/components/realtime/operational-realtime-provider'
import { createClient } from '@/lib/supabase/client'

type Preference={sessionId:string;parentId:string;kind:'private'|'intensive';topicStatus:string;requestedFocusId:string|null;requestedFocusName:string|null;requestedCustomFocus:string|null;requestedTopic:string|null;focusId:string|null;focusName:string|null;customFocus:string|null;topic:string|null;supportingMaterials:string[];mentorNotes:string|null;competitionNames:string[]}
type Focus={id:string;name:string}
type RpcClient={rpc:<T>(name:string,args:Record<string,unknown>)=>PromiseLike<{data:T|null;error:{message:string}|null}>}
const isUrl=(value:string)=>/^https?:\/\/\S+$/i.test(value)

export function MentoringSessionPreferences({kind,sessionId,role}:{kind:'private'|'intensive';sessionId:string;role:'mentee'|'admin'|'mentor'}){
 const supabase=useMemo(()=>createClient(),[]);const rpc=supabase as unknown as RpcClient
 const[data,setData]=useState<Preference|null>(null);const[focuses,setFocuses]=useState<Focus[]>([]);const[editing,setEditing]=useState(false);const[focusChoice,setFocusChoice]=useState('');const[customFocus,setCustomFocus]=useState('');const[topic,setTopic]=useState('');const[materials,setMaterials]=useState<string[]>([]);const[notes,setNotes]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('')
 const hydrate=useCallback((next:Preference)=>{setData(next);const focusId=role==='mentee'?next.requestedFocusId:next.focusId;const custom=role==='mentee'?next.requestedCustomFocus:next.customFocus;setFocusChoice(focusId??(custom?'custom':''));setCustomFocus(custom??'');setTopic((role==='mentee'?next.requestedTopic:next.topic)??'');setMaterials(next.supportingMaterials??[]);setNotes(next.mentorNotes??'')},[role])
 const load=useCallback(async()=>{const[result,catalog]=await Promise.all([rpc.rpc<Preference>('get_mentoring_session_preferences',{p_kind:kind,p_session_id:sessionId}),supabase.from('private_mentoring_session_focuses').select('id,name').eq('is_active',true).order('sort_order')]);if(!result.error&&result.data)hydrate(result.data);if(!catalog.error)setFocuses((catalog.data??[]) as Focus[])},[hydrate,kind,rpc,sessionId,supabase])
 useEffect(()=>{void load()},[load]);useOperationalInvalidation(['mentoring','admin-overview'],()=>{void load()})
 async function save(){setBusy(true);setMessage('');const result=await rpc.rpc<Preference>('save_mentoring_session_preferences',{p_kind:kind,p_session_id:sessionId,p_focus_id:focusChoice&&focusChoice!=='custom'?focusChoice:null,p_custom_focus:focusChoice==='custom'?customFocus.trim()||null:null,p_topic:topic.trim()||null,p_supporting_materials:materials.map(item=>item.trim()).filter(Boolean),p_mentor_notes:role==='admin'?notes.trim()||null:null});setBusy(false);if(result.error||!result.data){setMessage(result.error?.message||'Preferensi sesi belum dapat disimpan.');return}hydrate(result.data);setEditing(false);setMessage(role==='admin'?'Sesi sudah ditinjau dan preferensi tersimpan.':'Preferensi sesi dikirim ke Admin.')}
 function patchMaterial(index:number,value:string){setMaterials(current=>current.map((item,itemIndex)=>itemIndex===index?value:item))}
 const finalFocus=data?.customFocus||data?.focusName||null;const requestedFocus=data?.requestedCustomFocus||data?.requestedFocusName||null;const readOnly=role==='mentor'
 if(!data)return <section className="mentoring-preference-card"><p className="muted">Memuat preferensi sesi…</p></section>
 if(!editing)return <section className="mentoring-preference-card"><div className="mentoring-preference-card__head"><div><span>Fokus sesi (opsional)</span><strong>{finalFocus||requestedFocus||'Diserahkan ke Admin'}</strong></div>{!readOnly?<button className="button button-outline button-compact" type="button" onClick={()=>setEditing(true)}><Pencil aria-hidden="true"/>Edit preferensi</button>:null}</div><div><span>Nama lomba</span><div className="mentoring-chip-list">{data.competitionNames.length?data.competitionNames.map(item=><span className="mentoring-chip" key={item}>{item}</span>):<strong>Lengkapi nama lomba</strong>}</div></div><div className="mentoring-preference-grid"><div><span>Topik / scope sesi</span><strong>{data.topic||data.requestedTopic||'Diserahkan ke Admin'}</strong></div><div><span>File Pendukung (opsional)</span>{data.supportingMaterials.length?<ul className="mentoring-material-list">{data.supportingMaterials.map((item,index)=><li key={`${item}-${index}`}>{isUrl(item)?<a href={item} target="_blank" rel="noopener noreferrer">Buka file <ExternalLink aria-hidden="true"/></a>:item}</li>)}</ul>:<strong>Belum ada</strong>}</div></div>{role==='admin'?<details className="mentoring-audit-details"><summary>Permintaan awal & detail teknis</summary><dl><div><dt>Fokus yang diajukan</dt><dd>{requestedFocus||'Tidak ada'}</dd></div><div><dt>Topik yang diajukan</dt><dd>{data.requestedTopic||'Tidak ada'}</dd></div><div><dt>Status review</dt><dd>{data.topicStatus}</dd></div><div><dt>Session ID</dt><dd><code>{data.sessionId}</code></dd></div><div><dt>Catatan mentor</dt><dd>{data.mentorNotes||'Tidak ada'}</dd></div></dl></details>:null}{message?<small role="status">{message}</small>:null}</section>
 return <section className="mentoring-preference-card is-editing"><div className="ops-form-stack"><label className="ops-field"><span>Fokus sesi (opsional)</span><select value={focusChoice} onChange={event=>setFocusChoice(event.target.value)}><option value="">Serahkan ke Admin</option>{focuses.map(focus=><option value={focus.id} key={focus.id}>{focus.name}</option>)}<option value="custom">Fokus lain</option></select></label>{focusChoice==='custom'?<label className="ops-field"><span>Fokus lain</span><input value={customFocus} maxLength={300} onChange={event=>setCustomFocus(event.target.value)} placeholder="Tulis fokus khusus untuk sesi ini"/></label>:null}<label className="ops-field"><span>Topik / scope sesi (opsional)</span><textarea rows={4} value={topic} maxLength={3000} onChange={event=>setTopic(event.target.value)} placeholder="Boleh dikosongkan atau diserahkan ke Admin."/></label>{role==='admin'?<label className="ops-field"><span>Catatan untuk mentor (opsional)</span><textarea rows={3} value={notes} onChange={event=>setNotes(event.target.value)}/></label>:null}<fieldset className="mentoring-material-editor"><legend>File Pendukung (opsional)</legend><p>Tambahkan link Guidebook, Working Paper, Google Drive/Docs, deck, atau materi lain yang relevan.</p>{materials.map((item,index)=><div className="mentoring-material-row" key={index}><input value={item} maxLength={1000} onChange={event=>patchMaterial(index,event.target.value)} placeholder="https://… atau catatan materi"/><button type="button" className="ops-icon-button" onClick={()=>setMaterials(current=>current.filter((_,itemIndex)=>itemIndex!==index))} aria-label={`Hapus file pendukung ${index+1}`}><Trash2 aria-hidden="true"/></button></div>)}<button className="button button-outline button-compact" type="button" disabled={materials.length>=20} onClick={()=>setMaterials(current=>[...current,''])}><Plus aria-hidden="true"/>Tambah file pendukung</button></fieldset><div className="button-row"><button className="button button-primary" type="button" disabled={busy} onClick={()=>void save()}><Save aria-hidden="true"/>{busy?'Menyimpan…':role==='admin'?'Simpan & tandai ditinjau':'Kirim preferensi'}</button><button className="button button-outline" type="button" disabled={busy} onClick={()=>{hydrate(data);setEditing(false)}}>Batal</button></div>{message?<small className="form-error" role="alert">{message}</small>:null}</div></section>
}
