'use client'

import { Pencil, Save, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { MultiValueChipInput } from '@/components/mentoring/multi-value-chip-input'
import { useOperationalInvalidation } from '@/components/realtime/operational-realtime-provider'
import { createClient } from '@/lib/supabase/client'

type CompetitionContext={parentId:string;competitionNames:string[];competitionCategoryId:string|null}
type Category={id:string;name:string;is_active:boolean}
type RpcClient={rpc:<T>(name:string,args:Record<string,unknown>)=>PromiseLike<{data:T|null;error:{message:string}|null}>}

export function MentoringCompetitionEditor({kind,parentId,readOnly=false,compact=false,summary=false}:{kind:'private'|'intensive';parentId:string;readOnly?:boolean;compact?:boolean;summary?:boolean}){
 const supabase=useMemo(()=>createClient(),[]);const rpc=supabase as unknown as RpcClient
 const[data,setData]=useState<CompetitionContext|null>(null);const[names,setNames]=useState<string[]>([]);const[categoryId,setCategoryId]=useState('');const[categories,setCategories]=useState<Category[]>([]);const[editing,setEditing]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('')
 const load=useCallback(async()=>{const[result,catalog]=await Promise.all([rpc.rpc<CompetitionContext>('get_mentoring_competition_names',{p_kind:kind,p_parent_id:parentId}),supabase.from('competition_categories').select('id,name,is_active').order('sort_order')]);if(!result.error&&result.data){setData(result.data);setNames(result.data.competitionNames??[]);setCategoryId(result.data.competitionCategoryId??'')}if(!catalog.error)setCategories((catalog.data??[]) as Category[])},[kind,parentId,rpc,supabase])
 useEffect(()=>{void load()},[load]);useOperationalInvalidation(['mentoring','admin-overview'],()=>{void load()})
 async function save(){if(!names.length){setMessage('Tambahkan minimal satu nama lomba.');return}setBusy(true);setMessage('');const result=await rpc.rpc<CompetitionContext>('set_mentoring_competition_names',{p_kind:kind,p_parent_id:parentId,p_competition_names:names,p_competition_category_id:categoryId||null});setBusy(false);if(result.error||!result.data){setMessage(result.error?.message||'Nama lomba belum dapat disimpan.');return}setData(result.data);setNames(result.data.competitionNames);setEditing(false);setMessage('Nama lomba tersimpan.')}
 const values=data?.competitionNames??[]
 const savedCategory=categories.find(category=>category.id===data?.competitionCategoryId)
 if(!editing)return <section className={`mentoring-preference-card mentoring-competition-card${compact?' is-compact':''}${summary?' mentoring-competition-summary':''}`}><div className="mentoring-preference-card__head"><div><span>Nama lomba</span><div className="mentoring-chip-list">{values.length?values.map(item=><span className="mentoring-chip" key={item}>{item}</span>):<strong className="mentoring-empty-value">{readOnly?'Belum ditentukan':'Lengkapi nama lomba'}</strong>}{savedCategory?<span className="mentoring-chip mentoring-chip--category">{savedCategory.name}</span>:null}</div></div>{!readOnly?<button className={summary?'mentoring-summary-icon-action':'button button-outline button-compact'} type="button" onClick={()=>{setMessage('');setEditing(true)}} aria-label={values.length?'Edit nama lomba':'Lengkapi nama lomba'} title={values.length?'Edit nama lomba':'Lengkapi nama lomba'}><Pencil aria-hidden="true"/>{summary?null:values.length?'Edit':'Lengkapi nama lomba'}</button>:null}</div>{message?<small role="status">{message}</small>:null}</section>
 return <section className={`mentoring-preference-card mentoring-competition-card is-editing${summary?' mentoring-competition-summary mentoring-competition-summary--editing':''}`}><MultiValueChipInput label="Nama lomba" value={names} onChange={setNames}/><label className="ops-field"><span>Kategori kompetisi (opsional)</span><select value={categoryId} onChange={event=>setCategoryId(event.target.value)}><option value="">Tanpa kategori</option>{categories.filter(category=>category.is_active||category.id===categoryId).map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><div className="button-row"><button className="button button-primary" type="button" disabled={busy||!names.length} onClick={()=>void save()}><Save aria-hidden="true"/>{busy?'Menyimpan…':'Simpan nama lomba'}</button><button className="button button-outline" type="button" disabled={busy} onClick={()=>{setNames(values);setCategoryId(data?.competitionCategoryId??'');setMessage('');setEditing(false)}}><X aria-hidden="true"/>Batal</button></div>{message?<small className="form-error" role="alert">{message}</small>:null}</section>
}
