export type ProgramKind = 'Private Mentoring' | 'Intensive Mentoring' | 'Big Class' | 'Digital Product'
export type OrderStatus = 'PAYMENT_PENDING' | 'PAID' | 'ASSIGNMENT_PENDING' | 'MENTOR_ASSIGNED' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED'
export type PaymentStatus = 'Pending' | 'Paid' | 'Failed' | 'Refunded'
export type EnrollmentStatus = 'UPCOMING' | 'ACTIVE' | 'COMPLETED' | 'WAITING_FOR_MENTOR'

export type DemoOrder = {
  id: string; type: ProgramKind; program: ProgramKind; productId: string; title: string; subject: string; customer: string
  enrollmentId?: string; engagementId?: string; digitalPurchaseId?: string; parentOrderId?: string; status: OrderStatus
  fulfillmentStatus: EnrollmentStatus | 'DIGITAL_OWNED' | 'TOP_UP'; paymentStatus: PaymentStatus; paymentMethod?: 'QRIS' | 'Virtual Account' | 'E-Wallet'
  amount: number; price: string; purchasedAt: string; createdAt: string; sessions: number; completed: number; mentorId?: string; mentor: string
  schedule: string; goal?: string; packageLabel?: string; mentorPreference?: string; participantType?: 'Individual' | 'Team'; teamSize?: number
}
export type DemoEnrollment = { id: string; orderId: string; productId: string; type: ProgramKind; title: string; subject: string; status: EnrollmentStatus; purchasedAt: string; progress: number; totalUnits: number; cohortId?: string }
export type DemoEngagement = { id: string; enrollmentId: string; orderId: string; competition: string; learningGoal: string; packageLabel: string; mentorId?: string; mentor: string; assignmentStatus: 'Waiting for Mentor' | 'Assigned'; sessionsPurchased: number; sessionsCompleted: number; sessionsRemaining: number; status: EnrollmentStatus; nextSession?: string }
export type DemoDigitalPurchase = { id: string; orderId: string; productId: string; title: string; purchasedAt: string }
export type DemoAppointment = { id: string; enrollmentId: string; engagementId?: string; orderId: string; mentorId?: string; mentor: string; menteeId: string; serviceType: ProgramKind; competition: string; date: string; startTime: string; endTime: string; status: 'Scheduled' | 'Completed' | 'Cancelled' }
export type DemoNotification = { id: string; title: string; body: string; role: 'mentee' | 'mentor' | 'admin'; read: boolean; createdAt: string; orderId?: string; enrollmentId?: string }
export type DemoState = { version: 4; user: { id: string; name: string }; orders: DemoOrder[]; enrollments: DemoEnrollment[]; engagements: DemoEngagement[]; digitalPurchases: DemoDigitalPurchase[]; appointments: DemoAppointment[]; notifications: DemoNotification[] }

export const DEMO_STORE_KEY = 'strativate-demo-v4'
export const mentorOptions = ['Albert L.', 'Navira A.', 'Salsabila Putri', 'Raka Wijaya']
export const scheduleOptions = ['Kam, 20 Agu · 19:00 WIB', 'Sab, 22 Agu · 10:00 WIB', 'Sel, 25 Agu · 19:00 WIB']
export const programOptions = [
  { name: 'Private Mentoring' as const, title: 'Mentoring Privat', price: 'Rp 750 ribu', amount: 750000, detail: 'Tiga sesi berdurasi 75 menit bersama mentor kompetisi.', subjects: ['HSBC Business Case Competition', "L'Oréal Brandstorm", 'Pitch Deck Review', 'Business Plan Preparation'], sessions: 3 },
  { name: 'Intensive Mentoring' as const, title: 'Mentoring Intensif Kasus Bisnis', price: 'Rp 1,2 juta', amount: 1200000, detail: 'Lima sesi pendampingan dari ide awal hingga presentasi akhir.', subjects: ['Business Case Intensive', 'Case Structuring', 'Solution Development'], sessions: 5 },
  { name: 'Big Class' as const, title: 'Kelas Besar Kasus Bisnis', price: 'Rp 450 ribu', amount: 450000, detail: 'Belajar bersama satu angkatan melalui kelas langsung, materi, dan simulasi.', subjects: ['September 2026 Cohort', 'July 2026 Cohort', 'Case Simulation'], sessions: 8 },
  { name: 'Digital Product' as const, title: 'Panduan Pemecahan Kasus', price: 'Rp 79 ribu', amount: 79000, detail: 'Panduan PDF praktis untuk mempertajam analisis kasus.', subjects: ['Case Cracking Playbook', 'Pitch Deck Starter Kit'], sessions: 0 },
]

const starter: DemoState = {
  version: 4, user: { id: 'mentee-marsha', name: 'Marsha N.' },
  orders: [{ id: 'ST-2048', type: 'Private Mentoring', program: 'Private Mentoring', productId: 'private-hsbc', title: 'Mentoring Privat', subject: 'HSBC Business Case Competition', customer: 'Marsha N.', enrollmentId: 'PM-001', engagementId: 'ENG-001', status: 'ACTIVE', fulfillmentStatus: 'ACTIVE', paymentStatus: 'Paid', amount: 750000, price: 'Rp 750 ribu', purchasedAt: '12 Agu 2026', createdAt: '12 Agu 2026', sessions: 3, completed: 1, mentorId: 'albert', mentor: 'Albert L.', schedule: 'Kam, 20 Agu · 19:00 WIB', goal: 'Persiapan Kompetisi', packageLabel: '3 Sesi', mentorPreference: 'Albert L.', participantType: 'Individual' }],
  enrollments: [{ id: 'PM-001', orderId: 'ST-2048', productId: 'private-hsbc', type: 'Private Mentoring', title: 'Mentoring Privat', subject: 'HSBC Business Case Competition', status: 'ACTIVE', purchasedAt: '12 Agu 2026', progress: 1, totalUnits: 3 }],
  engagements: [{ id: 'ENG-001', enrollmentId: 'PM-001', orderId: 'ST-2048', competition: 'HSBC Business Case Competition', learningGoal: 'Persiapan Kompetisi', packageLabel: '3 Sesi', mentorId: 'albert', mentor: 'Albert L.', assignmentStatus: 'Assigned', sessionsPurchased: 3, sessionsCompleted: 1, sessionsRemaining: 2, status: 'ACTIVE', nextSession: 'Kam, 20 Agu · 19:00 WIB' }],
  digitalPurchases: [], appointments: [{ id: 'APT-001', enrollmentId: 'PM-001', engagementId: 'ENG-001', orderId: 'ST-2048', mentorId: 'albert', mentor: 'Albert L.', menteeId: 'mentee-marsha', serviceType: 'Private Mentoring', competition: 'HSBC Business Case Competition', date: '20 Agu 2026', startTime: '19:00', endTime: '20:15', status: 'Scheduled' }],
  notifications: [{ id: 'N-001', title: 'Albert L. ditugaskan untuk HSBC Business Case Competition.', body: 'Paket Mentoring Privat Anda memiliki sesi mendatang.', role: 'mentee', read: false, createdAt: 'Hari ini · 09:24', enrollmentId: 'PM-001' }],
}

function clone<T>(value: T): T { return JSON.parse(JSON.stringify(value)) }
export function readState(): DemoState { if (typeof window === 'undefined') return clone(starter); try { const raw = window.localStorage.getItem(DEMO_STORE_KEY); if (!raw) return clone(starter); const parsed = JSON.parse(raw); return parsed.version === 4 ? parsed : clone(starter) } catch { return clone(starter) } }
export function writeState(state: DemoState) { if (typeof window !== 'undefined') { window.localStorage.setItem(DEMO_STORE_KEY, JSON.stringify(state)); window.dispatchEvent(new CustomEvent('strativate-state-updated')) } }
export function resetDemoState() { if (typeof window !== 'undefined') writeState(clone(starter)) }
export function readOrders() { return readState().orders }
export function writeOrders(orders: DemoOrder[]) { const state = readState(); writeState({ ...state, orders }) }
export function readOrder() { return readOrders()[0] || null }
export function formatOrderDate() { return new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date()) }
export function uid(prefix: string) { return `${prefix}-${Date.now().toString(36).slice(-5)}-${Math.random().toString(36).slice(2, 6)}`.toUpperCase() }
export function createPendingOrder(input: { type: ProgramKind; title: string; productId: string; subject: string; price: string; amount: number; sessions: number; goal?: string; mentorPreference?: string; packageLabel?: string; parentOrderId?: string }) : DemoOrder { const id = uid('ST'); const engagementId = input.type === 'Private Mentoring' || input.type === 'Intensive Mentoring' ? uid('ENG') : undefined; const enrollmentId = input.type !== 'Digital Product' ? uid(input.type === 'Private Mentoring' ? 'PM' : input.type === 'Big Class' ? 'BC' : 'IN') : undefined; return { id, type: input.type, program: input.type, productId: input.productId, title: input.title, subject: input.subject, customer: 'Marsha N.', enrollmentId, engagementId, parentOrderId: input.parentOrderId, status: 'PAYMENT_PENDING', fulfillmentStatus: 'UPCOMING', paymentStatus: 'Pending', amount: input.amount, price: input.price, purchasedAt: formatOrderDate(), createdAt: formatOrderDate(), sessions: input.sessions, completed: 0, mentor: 'Belum ditugaskan', schedule: 'Belum dijadwalkan', goal: input.goal, packageLabel: input.packageLabel, mentorPreference: input.mentorPreference, participantType: 'Individual' } }
export function completePurchase(state: DemoState, order: DemoOrder, method: DemoOrder['paymentMethod'] = 'QRIS'): DemoState { const paid = { ...order, status: order.type === 'Digital Product' ? 'ACTIVE' as const : order.type === 'Private Mentoring' || order.type === 'Intensive Mentoring' ? 'ASSIGNMENT_PENDING' as const : 'ACTIVE' as const, fulfillmentStatus: order.type === 'Digital Product' ? 'DIGITAL_OWNED' as const : order.type === 'Private Mentoring' || order.type === 'Intensive Mentoring' ? 'WAITING_FOR_MENTOR' as const : 'UPCOMING' as const, paymentStatus: 'Paid' as const, paymentMethod: method }; const next = clone(state); next.orders = [paid, ...next.orders.filter((item) => item.id !== paid.id)]; if (paid.type !== 'Digital Product') { next.enrollments = [{ id: paid.enrollmentId!, orderId: paid.id, productId: paid.productId, type: paid.type, title: paid.title, subject: paid.subject, status: paid.fulfillmentStatus as EnrollmentStatus, purchasedAt: paid.purchasedAt, progress: 0, totalUnits: paid.sessions }, ...next.enrollments]; if (paid.engagementId) next.engagements = [{ id: paid.engagementId, enrollmentId: paid.enrollmentId!, orderId: paid.id, competition: paid.subject, learningGoal: paid.goal || 'Persiapan Kompetisi', packageLabel: paid.packageLabel || `${paid.sessions} Sesi`, mentor: 'Belum ditugaskan', assignmentStatus: 'Waiting for Mentor', sessionsPurchased: paid.sessions, sessionsCompleted: 0, sessionsRemaining: paid.sessions, status: 'WAITING_FOR_MENTOR', ...next.engagements[0] && {} }, ...next.engagements] } else next.digitalPurchases = [{ id: uid('DIG'), orderId: paid.id, productId: paid.productId, title: paid.title, purchasedAt: paid.purchasedAt }, ...next.digitalPurchases]; next.notifications = [{ id: uid('N'), title: `${paid.title} berhasil dibeli.`, body: paid.type === 'Digital Product' ? 'Produk Anda kini tersedia di Pustaka Saya.' : 'Program Anda siap untuk langkah berikutnya.', role: 'mentee', read: false, createdAt: 'Baru saja', orderId: paid.id }, ...next.notifications]; return next }
export function topUpEngagement(state: DemoState, engagementId: string, sessions: number): { state: DemoState; order: DemoOrder } { const engagement = state.engagements.find((item) => item.id === engagementId)!; const order = createPendingOrder({ type: 'Private Mentoring', title: 'Tambahan Sesi Mentoring Privat', productId: 'private-topup', subject: engagement.competition, price: `${sessions} Sesi`, amount: sessions * 250000, sessions, goal: engagement.learningGoal, mentorPreference: engagement.mentor, packageLabel: `${sessions} Sesi Tambahan`, parentOrderId: engagement.orderId }); order.engagementId = engagement.id; order.enrollmentId = engagement.enrollmentId; return { state, order } }
export function appointmentsFor(state: DemoState, engagementId?: string) { return state.appointments.filter((item) => !engagementId || item.engagementId === engagementId) }
export function demoAppointments(orders = readOrders()) { return orders.filter((o) => o.status === 'ACTIVE').map((o) => ({ id: `APT-${o.id}`, orderId: o.id, enrollmentId: o.enrollmentId || '', engagementId: o.engagementId, mentor: o.mentor, mentorId: o.mentorId, menteeId: 'mentee-marsha', serviceType: o.type, competition: o.subject, date: '20 Agu 2026', startTime: '19:00', endTime: '20:15', status: 'Scheduled' as const })) }
export function demoNotifications() { return readState().notifications }
export function programOptionsFor(type: ProgramKind) { return programOptions.find((item) => item.name === type) || programOptions[0] }
export const services = programOptions
export const starterState = starter
