'use client'

import { CalendarDays, Check, Clock3, Loader2, TriangleAlert, X } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { dateKeyInTimeZone } from '@/lib/calendar/slot-engine'

type Slot={mentorId:string;mentorName:string;timezone:string;start:string;end:string;menteeConflict:boolean}
type SlotPayload={context:{sessionId:string;focusName:string|null;durationMinutes:number;sessionNumber:number;purchasedSessions:number};slots:Slot[];mentorWarnings:string[];message:string}

export function AdminScheduleDialog({sessionId,onClose,onScheduled}:{sessionId:string|null;onClose:()=>void;onScheduled?:()=>void}){
 const ref=useRef<HTMLDialogElement>(null); const [payload,setPayload]=useState<SlotPayload|null>(null); const [selected,setSelected]=useState<Slot|null>(null); const [loading,setLoading]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('')
 useEffect(()=>{const dialog=ref.current;if(!dialog)return;if(sessionId&&!dialog.open)dialog.showModal();if(!sessionId&&dialog.open)dialog.close()},[sessionId])
 useEffect(()=>{if(!sessionId){setPayload(null);setSelected(null);return}let active=true;setLoading(true);setError('');setNotice('');fetch(`/api/admin/private-mentoring/sessions/${sessionId}/slots`,{cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||'Slot belum dapat dimuat.');if(active){setPayload(data);setSelected(null)}}).catch(err=>{if(active)setError(err.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[sessionId])
 const byDay=useMemo(()=>{const map=new Map<string,Map<string,Slot[]>>();for(const slot of payload?.slots??[]){const day=dateKeyInTimeZone(slot.start,slot.timezone);if(!map.has(day))map.set(day,new Map());const mentors=map.get(day)!;if(!mentors.has(slot.mentorId))mentors.set(slot.mentorId,[]);mentors.get(slot.mentorId)!.push(slot)}return [...map.entries()]},[payload])
 async function confirm(){if(!sessionId||!selected)return;setBusy(true);setError('');setNotice('');try{const response=await fetch(`/api/admin/private-mentoring/sessions/${sessionId}/schedule`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mentorId:selected.mentorId,start:selected.start})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Jadwal belum dapat disimpan.');setNotice(data.sync?.status==='failed'?'Jadwal tersimpan di Strativate, tetapi sinkronisasi Google gagal. Coba Retry dari detail kalender.':'Jadwal tersimpan dan sinkronisasi Google diproses.');onScheduled?.()}catch(err){setError(err instanceof Error?err.message:'Jadwal belum dapat disimpan.')}finally{setBusy(false)}}
 return <dialog ref={ref} className="calendar-dialog schedule-dialog" onCancel={event=>{event.preventDefault();onClose()}} onClose={onClose} aria-labelledby="schedule-dialog-title"><div className="calendar-dialog__head"><div><p className="kicker">Penjadwalan berbasis availability</p><h3 id="schedule-dialog-title">Jadwalkan Private Mentoring</h3>{payload?<p>Sesi {payload.context.sessionNumber}/{payload.context.purchasedSessions} · {payload.context.focusName||'Fokus belum dipilih'} · {payload.context.durationMinutes} menit</p>:null}</div><button type="button" className="icon-button" onClick={onClose} aria-label="Tutup penjadwalan"><X/></button></div>
 {loading?<p className="calendar-loading"><Loader2 className="spin"/>Menghitung slot aktual…</p>:null}
 {payload?.mentorWarnings?.length?<div className="calendar-warning" role="status"><TriangleAlert/ ><div><strong>Beberapa calendar belum dapat diverifikasi.</strong>{payload.mentorWarnings.map(item=><span key={item}>{item}</span>)}</div></div>:null}
 {!loading&&payload?.message?<p className="calendar-empty">{payload.message}</p>:null}
 <div className="schedule-slot-list">{byDay.map(([day,mentors])=><section key={day} className="schedule-day"><h4><CalendarDays/>{new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long'}).format(new Date(`${day}T12:00:00Z`))}</h4>{[...mentors.entries()].map(([mentorId,slots])=><div className="schedule-mentor" key={mentorId}><div><strong>{slots[0].mentorName}</strong><small>{slots[0].timezone}</small></div><div className="schedule-slots">{slots.map(slot=><button type="button" key={`${slot.mentorId}-${slot.start}`} aria-pressed={selected?.mentorId===slot.mentorId&&selected?.start===slot.start} className={selected?.mentorId===slot.mentorId&&selected?.start===slot.start?'is-selected':''} onClick={()=>setSelected(slot)}><Clock3/>{new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit',timeZone:slot.timezone}).format(new Date(slot.start))}–{new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit',timeZone:slot.timezone}).format(new Date(slot.end))}{slot.menteeConflict?<small>⚠ Bentrok agenda mentee</small>:null}</button>)}</div></div>)}</section>)}</div>
 {error?<p className="form-error" role="alert">{error}</p>:null}{notice?<p className="form-success" role="status">{notice}</p>:null}
 <div className="calendar-dialog__actions"><button type="button" className="button button-outline" onClick={onClose}>Batal</button><button type="button" className="button button-primary" disabled={!selected||busy} onClick={()=>void confirm()}>{busy?<Loader2 className="spin"/>:<Check/>}{busy?'Menyimpan…':'Konfirmasi slot'}</button></div></dialog>
}
