'use client'

import { Check, ChevronDown, Eye, Loader2, Search, ShieldAlert, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useRef, useState, type KeyboardEvent } from 'react'
import { SortableTableHeader, type SortDirection } from '@/components/admin/sortable-table-header'
import { TablePagination } from '@/components/admin/table-pagination'
import { useOperationalInvalidation } from '@/components/realtime/operational-realtime-provider'
import { DIGITAL_PRODUCT_IMAGE_BUCKET } from '@/lib/digital-products/config'
import { formatRupiah } from '@/lib/commerce/money'
import { createClient } from '@/lib/supabase/client'

type MenteeOption={user_id:string;email:string;display_name:string|null}
type CommerceOption={commerce_item_id:string;item_kind:string;name:string;slug:string;price_amount:number;description:string|null;image_path:string|null;owned_by_mentee:boolean;family_label:string|null;session_count:number|null}
type CartLinkRow={total_count:number;id:string;mentee_id:string;mentee_email:string;creator_email:string;status:string;item_count:number;created_at:string;claimed_at:string|null}
type ProductDetail={commerce_item_id:string;item_kind:string;name:string;slug:string;description:string|null;image_path:string|null;price_amount:number;is_available:boolean;session_count:number|null;mentor_tier_name:string|null;content_type:string|null}
type CompetitionCategory={id:string;name:string}
type RpcResult<T>=PromiseLike<{data:T|null;error:{message:string}|null}>
type UntypedClient={rpc:<T>(name:string,args?:Record<string,unknown>)=>RpcResult<T>}
type LinkSortKey='mentee'|'status'|'items'|'created_at'|'creator'|'claimed_at'
type CatalogTab='digital'|'private'|'intensive'
function kindLabel(kind:string){if(kind==='digital_product')return'Produk Digital';if(kind==='private_mentoring')return'Private Mentoring';if(kind==='intensive_mentoring_package')return'Program / package';if(kind==='intensive_mentoring_bundle')return'Bundle';if(kind==='intensive_mentoring_add_on')return'Add-on';return kind.replaceAll('_',' ')}
function linkStatusLabel(status:string){if(status==='active')return'Aktif';if(status==='claimed')return'Diklaim';if(status==='revoked')return'Dicabut';return status}
function tabFor(item:CommerceOption):CatalogTab{return item.item_kind==='digital_product'?'digital':item.item_kind==='private_mentoring'?'private':'intensive'}

export function CommerceCartLinkManagement(){
 const supabase=useMemo(()=>createClient(),[]);const client=supabase as unknown as UntypedClient
 const[menteeQuery,setMenteeQuery]=useState('');const[mentees,setMentees]=useState<MenteeOption[]>([]);const[menteeId,setMenteeId]=useState('');const[selectedMentee,setSelectedMentee]=useState<MenteeOption|null>(null);const[comboOpen,setComboOpen]=useState(false);const[activeIndex,setActiveIndex]=useState(0);const[menteeLoading,setMenteeLoading]=useState(false)
 const[productQuery,setProductQuery]=useState('');const[catalogTab,setCatalogTab]=useState<CatalogTab>('digital');const[items,setItems]=useState<CommerceOption[]>([]);const[itemIds,setItemIds]=useState<string[]>([]);const[selectedPrivateIds,setSelectedPrivateIds]=useState<string[]>([])
 const[historyQuery,setHistoryQuery]=useState('');const[historyStatus,setHistoryStatus]=useState('');const[links,setLinks]=useState<CartLinkRow[]>([]);const[totalLinks,setTotalLinks]=useState(0);const[page,setPage]=useState(0);const[pageSize,setPageSize]=useState(10);const[sortKey,setSortKey]=useState<LinkSortKey|null>(null);const[sortDirection,setSortDirection]=useState<SortDirection>(null)
 const[competitionCategories,setCompetitionCategories]=useState<CompetitionCategory[]>([]);const[competitionCategoryId,setCompetitionCategoryId]=useState('');const[competitionName,setCompetitionName]=useState('')
 const[generatedUrl,setGeneratedUrl]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[detail,setDetail]=useState<ProductDetail|null>(null)
 const comboRef=useRef<HTMLDivElement>(null);const dialogRef=useRef<HTMLDialogElement>(null)

 const loadMentees=useCallback(async()=>{setMenteeLoading(true);const result=await supabase.rpc('list_cart_link_mentees',{p_query:menteeQuery.trim()});setMenteeLoading(false);if(result.error){setMessage('Daftar mentee belum dapat dimuat.');return}setMentees((result.data??[]) as MenteeOption[]);setActiveIndex(0)},[menteeQuery,supabase])
 const loadItems=useCallback(async()=>{if(!menteeId){setItems([]);return}const result=await client.rpc<CommerceOption[]>('list_admin_cart_link_items',{p_mentee_id:menteeId,p_query:productQuery.trim()});if(result.error){setMessage('Daftar produk belum dapat dimuat.');return}setItems(result.data??[])},[client,menteeId,productQuery])
 const loadHistory=useCallback(async()=>{const result=await client.rpc<CartLinkRow[]>('list_admin_cart_links_page',{p_query:historyQuery.trim(),p_status:historyStatus,p_limit:pageSize,p_offset:page*pageSize});if(result.error){setMessage('Riwayat Cart Link belum dapat dimuat.');return}const rows=result.data??[];setLinks(rows);setTotalLinks(Number(rows[0]?.total_count??0))},[client,historyQuery,historyStatus,page,pageSize])
 const loadCompetitionCategories=useCallback(async()=>{const result=await supabase.from('competition_categories').select('id,name').eq('is_active',true).order('sort_order');if(!result.error)setCompetitionCategories((result.data??[]) as CompetitionCategory[])},[supabase])

 useEffect(()=>{const timer=setTimeout(()=>void loadMentees(),220);return()=>clearTimeout(timer)},[loadMentees])
 useEffect(()=>{const timer=setTimeout(()=>void loadItems(),220);return()=>clearTimeout(timer)},[loadItems])
 useEffect(()=>{const timer=setTimeout(()=>void loadHistory(),220);return()=>clearTimeout(timer)},[loadHistory])
 useOperationalInvalidation(['cart-links'],()=>{void loadHistory()})
 useEffect(()=>{void loadCompetitionCategories()},[loadCompetitionCategories])
 useEffect(()=>{const close=(event:PointerEvent)=>{if(comboRef.current&&!comboRef.current.contains(event.target as Node))setComboOpen(false)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[])
 useEffect(()=>{const dialog=dialogRef.current;if(!dialog)return;if(detail&&!dialog.open)dialog.showModal();if(!detail&&dialog.open)dialog.close()},[detail])

 const visibleItems=items.filter(item=>tabFor(item)===catalogTab)
 const privateFamilies=useMemo(()=>{const map=new Map<string,CommerceOption[]>();for(const item of visibleItems){const key=item.family_label||'Private Mentoring';map.set(key,[...(map.get(key)||[]),item])}return [...map.entries()]},[visibleItems])
 const intensiveGroups=useMemo(()=>{const order=['intensive_mentoring_package','intensive_mentoring_bundle','intensive_mentoring_add_on'];return order.map(kind=>[kind,visibleItems.filter(item=>item.item_kind===kind)] as const).filter(([,rows])=>rows.length)},[visibleItems])
 const hasSelectedPrivate=selectedPrivateIds.length>0
 const visibleLinks=useMemo(()=>{if(!sortKey||!sortDirection)return links;const sign=sortDirection==='asc'?1:-1;return[...links].sort((a,b)=>{if(sortKey==='items')return(a.item_count-b.item_count)*sign;if(sortKey==='created_at')return(new Date(a.created_at).getTime()-new Date(b.created_at).getTime())*sign;if(sortKey==='claimed_at')return((a.claimed_at?new Date(a.claimed_at).getTime():0)-(b.claimed_at?new Date(b.claimed_at).getTime():0))*sign;const left=sortKey==='mentee'?a.mentee_email:sortKey==='status'?linkStatusLabel(a.status):a.creator_email;const right=sortKey==='mentee'?b.mentee_email:sortKey==='status'?linkStatusLabel(b.status):b.creator_email;return left.localeCompare(right,'id-ID')*sign})},[links,sortDirection,sortKey])

 function selectMentee(mentee:MenteeOption){setSelectedMentee(mentee);setMenteeId(mentee.user_id);setMenteeQuery(mentee.display_name||mentee.email);setComboOpen(false);setItemIds([]);setSelectedPrivateIds([]);setProductQuery('');setCompetitionCategoryId('');setCompetitionName('')}
 function onComboKeyDown(event:KeyboardEvent<HTMLInputElement>){if(event.key==='ArrowDown'){event.preventDefault();setComboOpen(true);setActiveIndex(index=>Math.min(index+1,mentees.length-1))}else if(event.key==='ArrowUp'){event.preventDefault();setActiveIndex(index=>Math.max(0,index-1))}else if(event.key==='Enter'&&comboOpen&&mentees[activeIndex]){event.preventDefault();selectMentee(mentees[activeIndex])}else if(event.key==='Escape')setComboOpen(false)}
 function toggleItem(item:CommerceOption){
  if(item.owned_by_mentee)return
  const selected=itemIds.includes(item.commerce_item_id)
  setItemIds(current=>selected?current.filter(value=>value!==item.commerce_item_id):[...current,item.commerce_item_id])
  if(item.item_kind==='private_mentoring')setSelectedPrivateIds(current=>selected?current.filter(value=>value!==item.commerce_item_id):[...current,item.commerce_item_id])
}
 function productCard(item:CommerceOption){const selected=itemIds.includes(item.commerce_item_id);return <article className={'cart-link-product-card '+(selected?'is-selected':'')+(item.owned_by_mentee?' is-disabled':'')} key={item.commerce_item_id}>{item.image_path?<>{/* eslint-disable-next-line @next/next/no-img-element */}<img className="cart-link-product-card__cover" src={supabase.storage.from(DIGITAL_PRODUCT_IMAGE_BUCKET).getPublicUrl(item.image_path).data.publicUrl} alt={'Sampul '+item.name}/></>:<div className="cart-link-product-card__cover cart-link-product-card__cover--empty">{kindLabel(item.item_kind)}</div>}<button type="button" className="cart-link-product-card__select" disabled={item.owned_by_mentee} onClick={()=>toggleItem(item)} aria-pressed={selected}><span className="cart-link-product-card__check">{selected?<Check aria-hidden="true" size={15}/>:null}</span><small>{kindLabel(item.item_kind)}</small><strong>{item.name}</strong><b>{formatRupiah(item.price_amount)}</b>{item.owned_by_mentee?<span className="ops-status ops-status--neutral">Sudah dimiliki</span>:null}</button><button type="button" className="button button-outline" onClick={()=>void openDetail(item)}><Eye aria-hidden="true" size={15}/>Lihat Detail</button></article>}

 async function openDetail(item:CommerceOption){const result=await client.rpc<ProductDetail[]>('get_admin_commerce_item_detail',{p_commerce_item_id:item.commerce_item_id});if(result.error||!result.data?.[0]){setMessage('Detail produk belum dapat dimuat.');return}setDetail(result.data[0])}
 async function createLink(){if(!menteeId||itemIds.length===0){setMessage('Pilih satu mentee dan minimal satu item.');return}setBusy(true);setMessage('');setGeneratedUrl('');try{const response=await fetch('/api/admin/cart-links',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({menteeId,commerceItemIds:itemIds,competitionCategoryId:hasSelectedPrivate?(competitionCategoryId||null):null,competitionName:hasSelectedPrivate?(competitionName.trim()||null):null})});const body=await response.json() as{url?:string;error?:string};if(!response.ok||!body.url)throw new Error(body.error||'Cart Link gagal dibuat.');setGeneratedUrl(body.url);setMessage('Cart Link berhasil dibuat.');setItemIds([]);setSelectedPrivateIds([]);await loadHistory()}catch(error){setMessage(error instanceof Error?error.message:'Cart Link gagal dibuat.')}finally{setBusy(false)}}
 async function copyLink(){if(!generatedUrl)return;await navigator.clipboard.writeText(generatedUrl);setMessage('Cart Link disalin ke clipboard.')}
 function changeSort(key:string|null,direction:SortDirection){setSortKey(key as LinkSortKey|null);setSortDirection(direction)}
 const imageUrl=detail?.image_path?supabase.storage.from(DIGITAL_PRODUCT_IMAGE_BUCKET).getPublicUrl(detail.image_path).data.publicUrl:null

 return <div className="ops-page">
  <div className="role-page-title"><p className="kicker">Operasional · Shared Commerce</p><h2>Cart Links</h2><p>Pilih mentee, lalu susun item dari katalog commerce authoritative.</p></div>
  <section className="role-card cart-link-create">
   <div className="ops-section-heading"><div><p className="kicker">Langkah 1</p><h3>Pilih Mentee</h3><p>Cart Link hanya dapat diklaim akun tujuan.</p></div></div>
   <div ref={comboRef} className="ops-field ops-field--wide"><span>Cari mentee</span><div className="ops-input-with-icon"><Search aria-hidden="true" size={15}/><input role="combobox" aria-autocomplete="list" aria-expanded={comboOpen} aria-controls="cart-link-mentee-options" value={menteeQuery} onFocus={()=>setComboOpen(true)} onChange={event=>{setMenteeQuery(event.target.value);setSelectedMentee(null);setMenteeId('');setComboOpen(true)}} onKeyDown={onComboKeyDown} placeholder="Ketik nama atau email"/>{menteeLoading?<Loader2 className="spin" aria-hidden="true" size={15}/>:<ChevronDown aria-hidden="true" size={15}/>}</div>{comboOpen?<div id="cart-link-mentee-options" role="listbox" className="ops-combobox-options">{menteeLoading?<p>Memuat…</p>:mentees.length?mentees.map((mentee,index)=><button type="button" role="option" aria-selected={mentee.user_id===menteeId} className={index===activeIndex?'is-active':''} key={mentee.user_id} onMouseEnter={()=>setActiveIndex(index)} onClick={()=>selectMentee(mentee)}><strong>{mentee.display_name||'Mentee Strativate'}</strong><span>{mentee.email}</span></button>):<p>Tidak ada mentee yang cocok.</p>}</div>:null}</div>
   {selectedMentee?<p className="muted" role="status"><strong>Mentee terpilih:</strong> {selectedMentee.display_name||selectedMentee.email} · {selectedMentee.email}</p>:null}
   {hasSelectedPrivate?<section className="schedule-day"><div><p className="kicker">Prefill Private Mentoring (opsional)</p><h4>Competition / bidang lomba</h4><p className="muted">Boleh dikosongkan bila belum diketahui. Jika diisi, data akan diterapkan ke enrollment saat payment berhasil.</p></div><div className="ops-form-stack"><label className="ops-field"><span>Kategori</span><select value={competitionCategoryId} onChange={event=>setCompetitionCategoryId(event.target.value)}><option value="">Tanpa kategori</option>{competitionCategories.map(category=><option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label className="ops-field"><span>Nama lomba / bidang</span><input value={competitionName} maxLength={300} onChange={event=>setCompetitionName(event.target.value)} placeholder="Opsional"/></label></div></section>:null}

   <div className={'cart-link-products '+(menteeId?'':'is-disabled')} aria-disabled={!menteeId}>
    <div className="ops-section-heading"><div><p className="kicker">Langkah 2</p><h3>Pilih produk</h3><p>{menteeId?itemIds.length+' item dipilih.':'Pilih mentee untuk membuka katalog.'}</p></div></div>
    {menteeId?<><label className="ops-field ops-field--wide"><span>Cari produk</span><input value={productQuery} onChange={event=>setProductQuery(event.target.value)} placeholder="Nama produk"/></label><div className="calendar-view-switch" role="tablist" aria-label="Kategori produk"><button type="button" role="tab" aria-selected={catalogTab==='digital'} className={catalogTab==='digital'?'active':''} onClick={()=>setCatalogTab('digital')}>Produk Digital</button><button type="button" role="tab" aria-selected={catalogTab==='private'} className={catalogTab==='private'?'active':''} onClick={()=>setCatalogTab('private')}>Private Mentoring</button><button type="button" role="tab" aria-selected={catalogTab==='intensive'} className={catalogTab==='intensive'?'active':''} onClick={()=>setCatalogTab('intensive')}>Intensive Mentoring</button></div>
     {catalogTab==='digital'?<div className="cart-link-product-grid">{visibleItems.map(productCard)}</div>:null}
     {catalogTab==='private'?<div>{privateFamilies.map(([family,rows])=><section className="schedule-day" key={family}><div className="ops-section-heading"><div><p className="kicker">Mentor tier</p><h4>{family}</h4><p>Pilih package / jumlah sesi.</p></div></div><div className="cart-link-product-grid">{rows.map(productCard)}</div></section>)}</div>:null}
     {catalogTab==='intensive'?<div><div className="intensive-cart-legal-note"><ShieldAlert aria-hidden="true"/><div><strong>Item legal-blocked sengaja tidak dapat dipilih</strong><span>Win Guarantee Protection dan Competition Assurance tetap tercatat di katalog admin, tetapi tidak muncul sebagai item checkout sampai persetujuan legal/business selesai.</span></div></div>{intensiveGroups.map(([kind,rows])=><section className="schedule-day" key={kind}><h4>{kindLabel(kind)}</h4><div className="cart-link-product-grid">{rows.map(productCard)}</div></section>)}</div>:null}
     {visibleItems.length===0?<p className="muted">Tidak ada produk yang cocok di kategori ini.</p>:null}
    </>:<div className="cart-link-products__locked">Pilih mentee di atas sebelum memilih produk.</div>}
   </div>
   <div className="button-row"><button className="button button-primary" type="button" disabled={busy||!menteeId||itemIds.length===0} onClick={()=>void createLink()}>{busy?'Membuat…':'Buat Cart Link'}</button></div>
   {generatedUrl?<div className="cart-link-result"><p className="kicker">Tautan baru</p><p>{generatedUrl}</p><button className="button button-outline" type="button" onClick={()=>void copyLink()}>Copy Cart Link</button></div>:null}{message?<p className="muted" role="status">{message}</p>:null}
  </section>

  <section className="role-card ops-table-section"><div className="ops-section-heading"><div><p className="kicker">Riwayat Cart Link</p><h3>Riwayat Cart Link</h3></div><span>{totalLinks} data</span></div><div className="ops-filter-bar"><label className="ops-field ops-field--wide"><span>Cari riwayat</span><input value={historyQuery} onChange={event=>{setHistoryQuery(event.target.value);setPage(0)}} placeholder="Mentee, creator, atau ID"/></label><label className="ops-field"><span>Status</span><select value={historyStatus} onChange={event=>{setHistoryStatus(event.target.value);setPage(0)}}><option value="">Semua</option><option value="active">Aktif</option><option value="claimed">Diklaim</option><option value="revoked">Dicabut</option></select></label><label className="ops-field"><span>Per halaman</span><select value={pageSize} onChange={event=>{setPageSize(Number(event.target.value));setPage(0)}}>{[5,10,20].map(size=><option key={size}>{size}</option>)}</select></label></div><div className="ops-table-wrap"><table className="ops-table"><thead><tr><SortableTableHeader label="Mentee" sortKey="mentee" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Status" sortKey="status" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Item" sortKey="items" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Dibuat" sortKey="created_at" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Creator" sortKey="creator" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Diklaim" sortKey="claimed_at" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/></tr></thead><tbody>{visibleLinks.length?visibleLinks.map(link=><tr key={link.id}><td><strong>{link.mentee_email}</strong><small>{link.id}</small></td><td><span className={'ops-status ops-status--'+(link.status==='claimed'?'positive':link.status==='active'?'info':'neutral')}>{linkStatusLabel(link.status)}</span></td><td>{link.item_count}</td><td>{new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(link.created_at))}</td><td>{link.creator_email||'—'}</td><td>{link.claimed_at?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(link.claimed_at)):'—'}</td></tr>):<tr><td colSpan={6}>Belum ada Cart Link yang cocok.</td></tr>}</tbody></table></div><TablePagination page={page} pageSize={pageSize} totalItems={totalLinks} onPageChange={setPage} label="Pagination riwayat Cart Link"/></section>

  <dialog ref={dialogRef} className="ops-dialog" aria-labelledby="cart-link-product-detail-title" onClose={()=>setDetail(null)}>{detail?<div className="ops-dialog__surface"><header className="ops-dialog__header"><div><p className="kicker">Detail produk</p><h2 id="cart-link-product-detail-title">{detail.name}</h2><p>{kindLabel(detail.item_kind)}</p></div><button type="button" className="ops-icon-button" onClick={()=>setDetail(null)} aria-label="Tutup detail produk"><X/></button></header>{imageUrl?<>{/* eslint-disable-next-line @next/next/no-img-element */}<img className="cart-link-detail-cover" src={imageUrl} alt={'Sampul '+detail.name}/></>:null}<div className="ops-detail-grid"><div><span>Harga</span><strong>{formatRupiah(detail.price_amount)}</strong></div><div><span>Status</span><strong>{detail.is_available?'Aktif / dapat dibeli':'Tidak tersedia'}</strong></div>{detail.session_count?<div><span>Jumlah sesi</span><strong>{detail.session_count}</strong></div>:null}{detail.mentor_tier_name?<div><span>Tier mentor</span><strong>{detail.mentor_tier_name}</strong></div>:null}</div>{detail.description?<section className="ops-dialog__section"><h3>Deskripsi</h3><p>{detail.description}</p></section>:null}</div>:null}</dialog>
 </div>
}
