/* eslint-disable @typescript-eslint/no-explicit-any -- Catalog tables/RPCs are intentionally accessed through the existing ungenerated Supabase boundary. */
'use client'

import { Pencil, Plus, Search, Trash2, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react'

import { adminFormError as formError } from '@/lib/auth/errors'
import { createClient } from '@/lib/supabase/client'
import dataStyles from './data-management.module.css'
import styles from './mentoring-catalog-management.module.css'
import { SortableTableHeader, type SortDirection } from './sortable-table-header'
import { TablePagination } from './table-pagination'

type Category = { id:string; code:string; slug:string; name:string; sort_order:number; is_active:boolean }
const PAGE_SIZE=10

export function CompetitionCategoryManagement(){
 const db=useMemo(()=>createClient() as any,[])
 const[rows,setRows]=useState<Category[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(0)
 const[sortKey,setSortKey]=useState<string|null>(null),[sortDirection,setSortDirection]=useState<SortDirection>(null)
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const[editing,setEditing]=useState<Category|'new'|null>(null);const dialogRef=useRef<HTMLDialogElement>(null);const initialFormRef=useRef('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const{data,error:loadError}=await db.from('competition_categories').select('*').order('sort_order').order('id');if(loadError)throw loadError;setRows(data??[])}catch(caught){setError(formError(caught,'Unable to load competition categories.'))}finally{setLoading(false)}},[db])
 useEffect(()=>{void load()},[load]);useEffect(()=>{const dialog=dialogRef.current;if(!dialog)return;if(editing&&!dialog.open){dialog.showModal();const form=dialog.querySelector('form');initialFormRef.current=form?JSON.stringify(Array.from(new FormData(form).entries())):''}if(!editing&&dialog.open)dialog.close()},[editing])
 const visible=useMemo(()=>{let result=rows.filter(row=>(!query.trim()||row.name.toLowerCase().includes(query.trim().toLowerCase()))&&(status==='all'||row.is_active===(status==='active')));if(sortKey&&sortDirection){const sign=sortDirection==='asc'?1:-1;result=[...result].sort((a,b)=>{const av=sortKey==='name'?a.name:sortKey==='status'?Number(a.is_active):a.sort_order;const bv=sortKey==='name'?b.name:sortKey==='status'?Number(b.is_active):b.sort_order;return(typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv),'id-ID'))*sign})}return result},[query,rows,sortDirection,sortKey,status])
 useEffect(()=>{const lastPage=Math.max(0,Math.ceil(visible.length/PAGE_SIZE)-1);if(page>lastPage)setPage(lastPage)},[page,visible.length])
 const pageRows=visible.slice(page*PAGE_SIZE,page*PAGE_SIZE+PAGE_SIZE)
 function closeEditor(){if(busy)return;const form=dialogRef.current?.querySelector('form');const dirty=form&&JSON.stringify(Array.from(new FormData(form).entries()))!==initialFormRef.current;if(dirty&&!window.confirm('Discard unsaved category changes?'))return;dialogRef.current?.close()}
 function changeSort(key:string|null,direction:SortDirection){setSortKey(key);setSortDirection(direction);setPage(0)}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');const form=new FormData(event.currentTarget);try{const{error:saveError}=await db.rpc('admin_upsert_competition_category',{p_id:editing&&editing!=='new'?editing.id:null,p_name:String(form.get('name')||'').trim(),p_sort_order:Number(form.get('sort_order')),p_is_active:form.get('is_active')==='on'});if(saveError)throw saveError;setEditing(null);setMessage('Competition category saved.');await load()}catch(caught){setError(formError(caught,'Unable to save the competition category.'))}finally{setBusy(false)}}
 async function remove(row:Category){if(busy||!window.confirm(`Delete ${row.name}? Categories already in use are retained for historical records.`))return;setBusy(true);setError('');setMessage('');try{const{data,error:deleteError}=await db.rpc('admin_delete_mentoring_master',{p_table:'competition_categories',p_id:row.id});if(deleteError)throw deleteError;if(data==='deactivate_required')setMessage(`${row.name} is used by an enrollment. Deactivate it through Manage to preserve its history.`);else if(data==='deleted')setMessage(`${row.name} deleted.`);else setMessage('The category no longer exists.');await load()}catch(caught){setError(formError(caught,'Unable to delete the competition category.'))}finally{setBusy(false)}}
 const draft=editing&&editing!=='new'?editing:null
 return <div className={styles.page}><header className={styles.header}><div className={styles.headerCopy}><h2>Competition Categories</h2></div></header>
 <section className={dataStyles.surface}><div className={styles.surfaceHeading}><div><h3>Categories</h3><p>Categories are shared by Private and Intensive Mentoring. Changing their status affects the public catalog.</p></div><button type="button" className="button button-primary" disabled={busy} onClick={()=>setEditing('new')}><Plus size={15} aria-hidden="true"/>Add category</button></div>
 <div className={dataStyles.toolbar}><label className={dataStyles.searchField}>Search categories<span className={dataStyles.searchControl}><Search aria-hidden="true"/><input type="search" value={query} onChange={event=>{setQuery(event.target.value);setPage(0)}} placeholder="Category name"/></span></label><label className={dataStyles.filterField}>Status<select value={status} onChange={event=>{setStatus(event.target.value);setPage(0)}}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div>
 {error?<p className={`${styles.feedback} ${styles.error}`} role="alert">{error}</p>:null}{message?<p className={`${styles.feedback} ${styles.success}`} role="status">{message}</p>:null}
 <div className={dataStyles.tableScroll}><table className={dataStyles.table}><thead><tr><SortableTableHeader label="Category" sortKey="name" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Display order" sortKey="sort" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Status" sortKey="status" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><th className={dataStyles.actionCell}>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={4}>Loading categories…</td></tr>:pageRows.length===0?<tr><td colSpan={4}>No categories found.</td></tr>:pageRows.map(row=><tr key={row.id}><td><strong>{row.name}</strong></td><td>{row.sort_order}</td><td><span className={row.is_active?styles.statusActive:styles.statusInactive}>{row.is_active?'Active':'Inactive'}</span></td><td className={dataStyles.actionCell}><div className={styles.actions}><button type="button" className={`button button-outline ${dataStyles.actionButton}`} disabled={busy} onClick={()=>setEditing(row)}><Pencil size={14} aria-hidden="true"/>Manage</button><button type="button" className={`button button-outline ${dataStyles.actionButton} ${styles.danger}`} disabled={busy} onClick={()=>void remove(row)}><Trash2 size={14} aria-hidden="true"/>Delete</button></div></td></tr>)}</tbody></table></div><TablePagination language="en" page={page} pageSize={PAGE_SIZE} totalItems={visible.length} onPageChange={setPage} disabled={loading||busy} label="Pagination Competition Categories"/></section>
 <dialog ref={dialogRef} className={`${styles.dialog} ${dataStyles.compactDialog}`} onClose={()=>setEditing(null)} onCancel={event=>{event.preventDefault();closeEditor()}} onClick={event=>{if(event.target===event.currentTarget)closeEditor()}} aria-labelledby="competition-category-heading">{editing?<div className={styles.dialogPanel}><header className={styles.dialogHeader}><div><h2 id="competition-category-heading">{draft?`Edit ${draft.name}`:'Add competition category'}</h2></div><button type="button" className={styles.close} disabled={busy} onClick={closeEditor} aria-label="Close dialog"><X size={17}/></button></header><form className={styles.dialogBody} onSubmit={event=>void save(event)}><fieldset className={dataStyles.editableFields} disabled={busy}>{error?<p className={`${styles.feedback} ${styles.error}`} role="alert">{error}</p>:null}<div className={styles.formGrid}><label className={`${styles.field} ${styles.full}`}>Name<input name="name" required maxLength={160} defaultValue={draft?.name??''}/></label><label className={styles.field}>Display order<input name="sort_order" type="number" min="0" required defaultValue={draft?.sort_order??0}/></label><label className={`${styles.field} ${styles.checkbox}`}><input name="is_active" type="checkbox" defaultChecked={draft?.is_active??true}/> Active</label></div><div className={styles.actions}><button type="button" className="button button-outline" disabled={busy} onClick={closeEditor}>Cancel</button><button className="button button-primary" disabled={busy}>Save</button></div></fieldset></form></div>:null}</dialog></div>
}
