'use client'

import { Pencil, Plus, Search, Trash2, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react'

import { formError } from '@/lib/auth/errors'
import { createClient } from '@/lib/supabase/client'
import dataStyles from './data-management.module.css'
import styles from './mentoring-catalog-management.module.css'
import { SortableTableHeader, type SortDirection } from './sortable-table-header'
import { TablePagination } from './table-pagination'

type Category = { id:string; code:string; slug:string; name:string; sort_order:number; is_active:boolean }
const PAGE_SIZE=10

export function CompetitionCategoryManagement(){
 const db=useMemo(()=>createClient() as any,[])
 const[rows,setRows]=useState<Category[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(0)
 const[sortKey,setSortKey]=useState<string|null>(null),[sortDirection,setSortDirection]=useState<SortDirection>(null)
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const[editing,setEditing]=useState<Category|'new'|null>(null);const dialogRef=useRef<HTMLDialogElement>(null)
 const load=useCallback(async()=>{setLoading(true);setError('');try{const{data,error:loadError}=await db.from('competition_categories').select('*').order('sort_order').order('id');if(loadError)throw loadError;setRows(data??[])}catch(caught){setError(formError(caught,'Competition Categories belum dapat dimuat.'))}finally{setLoading(false)}},[db])
 useEffect(()=>{void load()},[load]);useEffect(()=>{const dialog=dialogRef.current;if(!dialog)return;if(editing&&!dialog.open)dialog.showModal();if(!editing&&dialog.open)dialog.close()},[editing])
 const visible=useMemo(()=>{let result=rows.filter(row=>(!query.trim()||row.name.toLowerCase().includes(query.trim().toLowerCase()))&&(status==='all'||row.is_active===(status==='active')));if(sortKey&&sortDirection){const sign=sortDirection==='asc'?1:-1;result=[...result].sort((a,b)=>{const av=sortKey==='name'?a.name:sortKey==='status'?Number(a.is_active):a.sort_order;const bv=sortKey==='name'?b.name:sortKey==='status'?Number(b.is_active):b.sort_order;return(typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv),'id-ID'))*sign})}return result},[query,rows,sortDirection,sortKey,status])
 const pageRows=visible.slice(page*PAGE_SIZE,page*PAGE_SIZE+PAGE_SIZE)
 function changeSort(key:string|null,direction:SortDirection){setSortKey(key);setSortDirection(direction);setPage(0)}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setMessage('');const form=new FormData(event.currentTarget);try{const{error:saveError}=await db.rpc('admin_upsert_competition_category',{p_id:editing&&editing!=='new'?editing.id:null,p_name:String(form.get('name')||'').trim(),p_sort_order:Number(form.get('sort_order')),p_is_active:form.get('is_active')==='on'});if(saveError)throw saveError;setEditing(null);setMessage('Competition Category tersimpan.');await load()}catch(caught){setError(formError(caught,'Competition Category belum dapat disimpan.'))}finally{setBusy(false)}}
 async function remove(row:Category){if(!window.confirm(`Hapus ${row.name}? Kategori yang sudah dipakai akan dipertahankan untuk histori.`))return;setBusy(true);setError('');setMessage('');try{const{data,error:deleteError}=await db.rpc('admin_delete_mentoring_master',{p_table:'competition_categories',p_id:row.id});if(deleteError)throw deleteError;if(data==='deactivate_required')setMessage(`${row.name} sudah dipakai oleh enrollment. Nonaktifkan melalui Kelola agar histori tetap aman.`);else if(data==='deleted')setMessage(`${row.name} dihapus.`);else setMessage('Kategori sudah tidak ditemukan.');await load()}catch(caught){setError(formError(caught,'Competition Category belum dapat dihapus.'))}finally{setBusy(false)}}
 const draft=editing&&editing!=='new'?editing:null
 return <div className={styles.page}><header className={styles.header}><div className={styles.headerCopy}><p className="kicker">Produk · Shared Master</p><h2>Competition Categories</h2><p>Kategori ini digunakan bersama oleh Private Mentoring dan Intensive Mentoring. Perubahan aktif/nonaktif langsung memengaruhi katalog publik.</p></div></header>
 <section className={dataStyles.surface}><div className={styles.surfaceHeading}><div><p className="kicker">Kategori kompetisi</p><h3>Shared Competition Master</h3><p>Kelola nama, urutan, dan status kategori tanpa menduplikasi taxonomy per program.</p></div><button type="button" className="button button-primary" onClick={()=>setEditing('new')}><Plus size={15} aria-hidden="true"/>Tambah Kategori</button></div>
 <div className={dataStyles.toolbar}><label className={dataStyles.searchField}>Cari kategori<span className={dataStyles.searchControl}><Search aria-hidden="true"/><input type="search" value={query} onChange={event=>{setQuery(event.target.value);setPage(0)}} placeholder="Nama kategori"/></span></label><label className={dataStyles.filterField}>Status<select value={status} onChange={event=>{setStatus(event.target.value);setPage(0)}}><option value="all">Semua status</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select></label></div>
 {error?<p className={`${styles.feedback} ${styles.error}`} role="alert">{error}</p>:null}{message?<p className={`${styles.feedback} ${styles.success}`} role="status">{message}</p>:null}
 <div className={dataStyles.tableScroll}><table className={dataStyles.table}><thead><tr><SortableTableHeader label="Kategori" sortKey="name" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Urutan" sortKey="sort" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Status" sortKey="status" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><th className={dataStyles.actionCell}>Aksi</th></tr></thead><tbody>{loading?<tr><td colSpan={4}>Memuat kategori…</td></tr>:pageRows.length===0?<tr><td colSpan={4}>Kategori tidak ditemukan.</td></tr>:pageRows.map(row=><tr key={row.id}><td><strong>{row.name}</strong><small className={styles.mono}>{row.slug}</small></td><td>{row.sort_order}</td><td><span className={row.is_active?styles.statusActive:styles.statusInactive}>{row.is_active?'Aktif':'Nonaktif'}</span></td><td className={dataStyles.actionCell}><div className={styles.actions}><button type="button" className={`button button-outline ${dataStyles.actionButton}`} onClick={()=>setEditing(row)}><Pencil size={14} aria-hidden="true"/>Kelola</button><button type="button" className={`button button-outline ${dataStyles.actionButton} ${styles.danger}`} disabled={busy} onClick={()=>void remove(row)}><Trash2 size={14} aria-hidden="true"/>Hapus</button></div></td></tr>)}</tbody></table></div><TablePagination page={page} pageSize={PAGE_SIZE} totalItems={visible.length} onPageChange={setPage} disabled={loading||busy} label="Pagination Competition Categories"/></section>
 <dialog ref={dialogRef} className={styles.dialog} onClose={()=>setEditing(null)} onClick={event=>{if(event.target===event.currentTarget)event.currentTarget.close()}}>{editing?<div className={styles.dialogPanel}><header className={styles.dialogHeader}><div><p className="kicker">Competition Category</p><h2>{draft?`Edit ${draft.name}`:'Tambah Competition Category'}</h2></div><button type="button" className={styles.close} onClick={()=>dialogRef.current?.close()} aria-label="Tutup dialog"><X size={17}/></button></header><form className={styles.dialogBody} onSubmit={event=>void save(event)}><div className={styles.formGrid}><label className={`${styles.field} ${styles.full}`}>Nama<input name="name" required maxLength={160} defaultValue={draft?.name??''}/></label><label className={styles.field}>Urutan<input name="sort_order" type="number" min="0" required defaultValue={draft?.sort_order??0}/></label><label className={`${styles.field} ${styles.checkbox}`}><input name="is_active" type="checkbox" defaultChecked={draft?.is_active??true}/> Aktif</label></div><div className={styles.actions}><button type="button" className="button button-outline" onClick={()=>dialogRef.current?.close()}>Batal</button><button className="button button-primary" disabled={busy}>Simpan</button></div></form></div>:null}</dialog></div>
}
