'use client'

import { Eye, EyeOff, FileText, LoaderCircle, Star, X } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { formError } from '@/lib/auth/errors'
import { createClient } from '@/lib/supabase/client'
import type { AdminDigitalProductReview, DigitalProduct } from '@/lib/supabase/database.types'
import { PeekRating } from '@/components/digital-products/peek-rating'
import { AggregateRating } from '@/components/digital-products/aggregate-rating'
import styles from './digital-product-rating-management.module.css'

type RatingRow = AdminDigitalProductReview
type Sort = 'newest' | 'oldest' | 'highest' | 'lowest'
export function DigitalProductRatingManagement({ product, onClose, onVisibilityChange }: { product: DigitalProduct; onClose: () => void; onVisibilityChange: (value: boolean) => void }) {
  const supabase = useMemo(() => createClient(), [])
  const [rows, setRows] = useState<RatingRow[]>([])
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [query, setQuery] = useState('')
  const [ratingFilter, setRatingFilter] = useState('all')
  const [commentFilter, setCommentFilter] = useState('all')
  const [sort, setSort] = useState<Sort>('newest')
  const [showRating, setShowRating] = useState(product.show_rating ?? false)
  const [detail, setDetail] = useState<RatingRow | null>(null)
  const dialogRef = useRef<HTMLDialogElement>(null)
  useEffect(() => { const dialog = dialogRef.current; dialog?.showModal(); const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = old; dialog?.close() } }, [])
  useEffect(() => { let active = true; async function load() { const { data, error: loadError } = await supabase.rpc('list_admin_digital_product_reviews', { p_product_id: product.id }); if (!active) return; if (loadError) setError(formError(loadError, 'Rating belum dapat dimuat.')); setRows(data ?? []); setLoading(false) }; void load(); return () => { active = false } }, [product.id, supabase])
  const average = rows.length ? rows.reduce((sum, row) => sum + row.rating, 0) / rows.length : 0
  const withFeedback = rows.filter(row => Boolean(row.comment)).length
  const filtered = useMemo(() => rows.filter(row => (!query.trim() || `${row.customer_name} ${row.comment ?? ''}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())) && (ratingFilter === 'all' || row.rating === Number(ratingFilter)) && (commentFilter === 'all' || commentFilter === 'with' && row.comment || commentFilter === 'without' && !row.comment)).sort((a, b) => sort === 'oldest' ? a.created_at.localeCompare(b.created_at) : sort === 'highest' ? b.rating - a.rating : sort === 'lowest' ? a.rating - b.rating : b.updated_at.localeCompare(a.updated_at)), [commentFilter, query, ratingFilter, rows, sort])
  async function toggleVisibility() { if (busy) return; const next = !showRating; setBusy(true); const { error: updateError } = await supabase.rpc('set_digital_product_rating_visibility', { p_product_id: product.id, p_show_rating: next }); if (updateError) setError(formError(updateError, 'Visibilitas rating belum dapat diubah.')); else { setShowRating(next); onVisibilityChange(next) }; setBusy(false) }
  const distribution = [5, 4, 3, 2, 1].map(value => ({ value, count: rows.filter(row => row.rating === value).length }))
  return <dialog ref={dialogRef} className={styles.dialog} aria-labelledby="rating-review-heading" onCancel={onClose} onClick={event => { if (event.target === event.currentTarget) onClose() }}><div className={styles.panel}><header className={styles.header}><div><p className="kicker">Ratings & Reviews</p><h2 id="rating-review-heading">{product.name}</h2><span className={styles.meta}><FileText size={13}/> {product.content_type?.toUpperCase() ?? 'DIGITAL PRODUCT'} · {product.is_published ? 'Published' : 'Draft'}</span></div><button type="button" className={`role-close ${styles.close}`} onClick={onClose} aria-label="Close ratings and reviews"><X/></button></header><div className={styles.body}>
    <section className={styles.metrics} aria-label="Rating summary"><Metric value={rows.length ? <AggregateRating averageRating={average} ratingCount={rows.length} variant="admin"/> : '—'} label="Average rating"/><Metric value={rows.length.toLocaleString()} label="Total ratings"/><Metric value={withFeedback.toLocaleString()} label="With feedback"/><Metric value={showRating ? 'Visible' : 'Hidden'} label="Public display"/></section>
    {rows.length === 0 ? <section className={styles.empty}><Star aria-hidden="true"/><h3>No ratings yet</h3><p>This Digital Product has not received customer feedback yet. Ratings from verified buyers will appear here.</p></section> : <section className={styles.overview}><div className={styles.section}><div className={styles.sectionHeading}><h3>Rating distribution</h3><p>Verified owner ratings only.</p></div><div className={styles.distribution}>{distribution.map(item => <div className={styles.distributionRow} key={item.value}><span>{item.value} <Star size={12} fill="currentColor"/></span><span className={styles.track}><i style={{ width: `${rows.length ? item.count / rows.length * 100 : 0}%` }}/></span><strong>{item.count}</strong></div>)}</div></div><div className={`${styles.section} ${styles.visibility}`}><div className={styles.sectionHeading}><h3>Public visibility</h3><p>This controls the compact aggregate only. Written feedback is always private.</p></div><button type="button" className={styles.toggle} onClick={() => void toggleVisibility()} disabled={busy} aria-pressed={showRating}><span>{showRating ? <Eye size={16}/> : <EyeOff size={16}/>} Show rating publicly</span><b className={showRating ? styles.toggleOn : ''}>{busy ? '…' : showRating ? 'ON' : 'OFF'}</b></button>{showRating ? <p className={styles.preview}>★ {average.toFixed(1)} · {rows.length} ratings</p> : null}</div></section>}
    <section className={styles.feedback}><div className={styles.sectionHeading}><h3>Customer feedback</h3><p>Admin-only view. Customer comments and identities never appear on public pages.</p></div><div className={styles.toolbar}><label className={styles.search}>Search feedback<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Name or comment"/></label><label>Rating<select value={ratingFilter} onChange={event => setRatingFilter(event.target.value)}><option value="all">All ratings</option>{[5,4,3,2,1].map(value => <option key={value} value={value}>{value} stars</option>)}</select></label><label>Feedback<select value={commentFilter} onChange={event => setCommentFilter(event.target.value)}><option value="all">All</option><option value="with">With comment</option><option value="without">Rating only</option></select></label><label>Sort<select value={sort} onChange={event => setSort(event.target.value as Sort)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="highest">Highest rating</option><option value="lowest">Lowest rating</option></select></label></div>{loading ? <div className={styles.loading}><LoaderCircle className="is-spinning"/> Loading feedback…</div> : error ? <p className={styles.error} role="alert">{error}</p> : filtered.length === 0 ? <div className={styles.noResults}>No feedback matches these filters.</div> : <><div className={styles.tableWrap}><table><thead><tr><th>Customer</th><th>Rating</th><th>Feedback</th><th>Updated</th></tr></thead><tbody>{filtered.map(row => <tr key={row.id}><td>{row.customer_name}</td><td><span className={styles.stars} aria-label={`${row.rating} out of 5`}>{'★'.repeat(row.rating)}<span>{'★'.repeat(5 - row.rating)}</span></span></td><td><div className={styles.previewText}>{row.comment || '—'}</div>{row.comment ? <button type="button" className={styles.view} onClick={() => setDetail(row)}>View</button> : null}</td><td><time dateTime={row.updated_at}>{new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(row.updated_at))}</time></td></tr>)}</tbody></table></div><div className={styles.mobileList}>{filtered.map(row => <article key={row.id}><div><span className={styles.stars} aria-label={`${row.rating} out of 5`}>{'★'.repeat(row.rating)}<span>{'★'.repeat(5 - row.rating)}</span></span><time dateTime={row.updated_at}>{new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric' }).format(new Date(row.updated_at))}</time></div><strong>{row.customer_name}</strong><p>{row.comment || 'Rating only'}</p>{row.comment ? <button type="button" className={styles.view} onClick={() => setDetail(row)}>View feedback</button> : null}</article>)}</div></>}</section>
  </div></div>{detail ? <div className={styles.detailBackdrop} role="presentation" onClick={() => setDetail(null)}><section className={styles.detail} role="dialog" aria-modal="true" aria-labelledby="feedback-detail-heading" onClick={event => event.stopPropagation()}><button type="button" className={styles.detailClose} onClick={() => setDetail(null)} aria-label="Close feedback detail"><X/></button><h3 id="feedback-detail-heading">Feedback detail</h3><PeekRating value={detail.rating} readOnly size={24}/><dl><div><dt>Customer</dt><dd>{detail.customer_name}</dd></div><div><dt>Updated</dt><dd>{new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(new Date(detail.updated_at))}</dd></div></dl><p className={styles.detailComment}>{detail.comment}</p><small>Private admin analysis · read-only</small></section></div> : null}</dialog>
}
function Metric({ value, label }: { value: React.ReactNode; label: string }) { return <div className={styles.metric}><strong>{value}</strong><span>{label}</span></div> }
