/* eslint-disable @typescript-eslint/no-explicit-any -- Catalog tables/RPCs are intentionally accessed through the existing ungenerated Supabase boundary. */
'use client'

import { Minus, Pencil, Plus, Search, Trash2, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { adminFormError as formError } from '@/lib/auth/errors'
import { formatRupiah } from '@/lib/commerce/money'
import { createClient } from '@/lib/supabase/client'
import dataStyles from './data-management.module.css'
import styles from './mentoring-catalog-management.module.css'
import { SortableTableHeader, type SortDirection } from './sortable-table-header'
import { TablePagination } from './table-pagination'

type Tab='packages'|'add-ons'|'bundles'
type PackageRow={id:string;code:string;slug:string;name:string;description:string;competition_scope:'national'|'international';sessions_per_month:number|null;pricing_mode:'fixed'|'consultation';price_amount:number|null;reference_price_amount:number|null;sort_order:number;is_active:boolean}
type PackageFeature={id:string;package_id:string;text:string;sort_order:number;is_active:boolean}
type AddOnRow={id:string;code:string;slug:string;name:string;description:string;price_amount:number;terms_note:string|null;sort_order:number;is_active:boolean}
type AddOnFeature={id:string;add_on_id:string;text:string;sort_order:number;is_active:boolean}
type BundleRow={id:string;code:string;slug:string;name:string;description:string;price_amount:number;badge_text:string|null;sort_order:number;is_active:boolean}
type BundleItem={id:string;bundle_id:string;item_type:'package'|'add_on'|'feature';package_id:string|null;add_on_id:string|null;feature_text:string|null;sort_order:number;is_active:boolean}
type Editing={kind:'package';row:PackageRow|null}|{kind:'add-on';row:AddOnRow|null}|{kind:'bundle';row:BundleRow|null}
type BundleDraft={itemType:'package'|'add_on'|'feature';referenceId:string;text:string}
type Row=PackageRow|AddOnRow|BundleRow
const PAGE_SIZE=8

function compare(a:string|number,b:string|number,d:SortDirection){const v=typeof a==='number'&&typeof b==='number'?a-b:String(a).localeCompare(String(b),'id-ID');return d==='desc'?-v:v}

export function IntensiveMentoringManagement(){
 const db=useMemo(()=>createClient() as any,[])
 const[tab,setTab]=useState<Tab>('packages'),[packages,setPackages]=useState<PackageRow[]>([]),[packageFeatures,setPackageFeatures]=useState<PackageFeature[]>([]),[addOns,setAddOns]=useState<AddOnRow[]>([]),[addOnFeatures,setAddOnFeatures]=useState<AddOnFeature[]>([]),[bundles,setBundles]=useState<BundleRow[]>([]),[bundleItems,setBundleItems]=useState<BundleItem[]>([])
 const[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(0),[sortKey,setSortKey]=useState<string|null>(null),[sortDirection,setSortDirection]=useState<SortDirection>(null)
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[editing,setEditing]=useState<Editing|null>(null),[featureDrafts,setFeatureDrafts]=useState<string[]>([]),[bundleDrafts,setBundleDrafts]=useState<BundleDraft[]>([])
 const dialogRef=useRef<HTMLDialogElement>(null)
 const editorDirtyRef=useRef(false)
 const initializedEditorRef=useRef<Editing|null>(null)
 function closeEditor(){if(busy)return;if(editorDirtyRef.current&&!window.confirm('Discard unsaved catalog changes?'))return;setEditing(null)}
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await Promise.all([db.from('intensive_mentoring_packages').select('*').order('sort_order').order('id'),db.from('intensive_mentoring_package_features').select('*').order('sort_order').order('id'),db.from('intensive_mentoring_add_ons').select('*').order('sort_order').order('id'),db.from('intensive_mentoring_add_on_features').select('*').order('sort_order').order('id'),db.from('intensive_mentoring_bundles').select('*').order('sort_order').order('id'),db.from('intensive_mentoring_bundle_items').select('*').order('sort_order').order('id')]);const failed=r.find(x=>x.error);if(failed?.error)throw failed.error;setPackages(r[0].data??[]);setPackageFeatures(r[1].data??[]);setAddOns(r[2].data??[]);setAddOnFeatures(r[3].data??[]);setBundles(r[4].data??[]);setBundleItems(r[5].data??[])}catch(e){setError(formError(e,'Unable to load the Intensive Mentoring catalog.'))}finally{setLoading(false)}},[db])
 useEffect(()=>{void load()},[load]);useEffect(()=>{setPage(0);setQuery('');setStatus('all');setSortKey(null);setSortDirection(null)},[tab]);useEffect(()=>{const d=dialogRef.current;if(!d)return;if(editing&&!d.open)d.showModal();if(!editing&&d.open)d.close();if(!editing){initializedEditorRef.current=null;setFeatureDrafts([]);setBundleDrafts([]);return}if(initializedEditorRef.current===editing)return;initializedEditorRef.current=editing;editorDirtyRef.current=false;if(editing.kind==='package')setFeatureDrafts(editing.row?packageFeatures.filter(x=>x.package_id===editing.row!.id&&x.is_active).map(x=>x.text):['']);else if(editing.kind==='add-on')setFeatureDrafts(editing.row?addOnFeatures.filter(x=>x.add_on_id===editing.row!.id&&x.is_active).map(x=>x.text):['']);else setBundleDrafts(editing.row?bundleItems.filter(x=>x.bundle_id===editing.row!.id&&x.is_active).map(x=>({itemType:x.item_type,referenceId:x.package_id??x.add_on_id??'',text:x.feature_text??''})):[])},[addOnFeatures,bundleItems,editing,packageFeatures])
 const raw:Row[]=tab==='packages'?packages:tab==='add-ons'?addOns:bundles
 const visible=useMemo(()=>{let rows=raw.filter(r=>(!query.trim()||`${r.name} ${r.description}`.toLowerCase().includes(query.trim().toLowerCase()))&&(status==='all'||r.is_active===(status==='active')));if(sortKey&&sortDirection)rows=[...rows].sort((a,b)=>{const value=(r:Row)=>sortKey==='name'?r.name:sortKey==='price'?Number(r.price_amount??0):sortKey==='status'?Number(r.is_active):r.sort_order;return compare(value(a),value(b),sortDirection)});return rows},[query,raw,sortDirection,sortKey,status])
 const currentPage=Math.min(page,Math.max(0,Math.ceil(visible.length/PAGE_SIZE)-1)),pageRows=visible.slice(currentPage*PAGE_SIZE,currentPage*PAGE_SIZE+PAGE_SIZE),title=tab==='packages'?'Main Packages':tab==='add-ons'?'Add-On':'Bundles'
 function changeSort(k:string|null,d:SortDirection){setSortKey(k);setSortDirection(d);setPage(0)}
 function openCreate(){setEditing(tab==='packages'?{kind:'package',row:null}:tab==='add-ons'?{kind:'add-on',row:null}:{kind:'bundle',row:null})}
 async function savePackage(event:FormEvent<HTMLFormElement>,row:PackageRow|null){event.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(event.currentTarget),name=String(f.get('name')||'').trim(),mode=String(f.get('pricing_mode')) as PackageRow['pricing_mode'];try{const result=await db.rpc('admin_save_intensive_package',{p_id:row?.id??null,p_name:name,p_description:String(f.get('description')||'').trim(),p_competition_scope:String(f.get('competition_scope')),p_sessions_per_month:String(f.get('sessions_per_month')||'')?Number(f.get('sessions_per_month')):null,p_pricing_mode:mode,p_price_amount:mode==='consultation'?null:Number(f.get('price_amount')),p_reference_price_amount:mode==='consultation'||!String(f.get('reference_price_amount')||'')?null:Number(f.get('reference_price_amount')),p_sort_order:Number(f.get('sort_order')),p_is_active:f.get('is_active')==='on',p_features:featureDrafts.map(text=>({text:text.trim()})).filter(item=>item.text)});if(result.error)throw result.error;setEditing(null);setMessage('Intensive Mentoring package saved.');await load()}catch(e){await load();setError(formError(e,'Unable to save the Intensive Mentoring package.'))}finally{setBusy(false)}}
 async function saveAddOn(event:FormEvent<HTMLFormElement>,row:AddOnRow|null){event.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(event.currentTarget),active=f.get('is_active')==='on';try{const result=await db.rpc('admin_save_intensive_add_on',{p_id:row?.id??null,p_name:String(f.get('name')||'').trim(),p_description:String(f.get('description')||'').trim(),p_price_amount:Number(f.get('price_amount')),p_terms_note:String(f.get('terms_note')||'').trim()||null,p_sort_order:Number(f.get('sort_order')),p_is_active:active,p_features:featureDrafts.map(text=>({text:text.trim()})).filter(item=>item.text)});if(result.error)throw result.error;setEditing(null);setMessage('Add-on saved.');await load()}catch(e){await load();setError(formError(e,'Unable to save the add-on.'))}finally{setBusy(false)}}
 async function saveBundle(event:FormEvent<HTMLFormElement>,row:BundleRow|null){event.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(event.currentTarget),active=f.get('is_active')==='on';const items=bundleDrafts.filter(x=>x.itemType==='feature'?x.text.trim():x.referenceId);if(active&&items.some(x=>x.itemType==='package'?packages.find(p=>p.id===x.referenceId)?.is_active!==true:x.itemType==='add_on'?addOns.find(a=>a.id===x.referenceId)?.is_active!==true:false)){setError('Active bundles can only include active packages and add-ons.');setBusy(false);return}try{const result=await db.rpc('admin_save_intensive_bundle',{p_id:row?.id??null,p_name:String(f.get('name')||'').trim(),p_description:String(f.get('description')||'').trim(),p_price_amount:Number(f.get('price_amount')),p_badge_text:String(f.get('badge_text')||'').trim()||null,p_sort_order:Number(f.get('sort_order')),p_is_active:active,p_items:items.map(item=>({item_type:item.itemType,reference_id:item.itemType==='feature'?null:item.referenceId,text:item.itemType==='feature'?item.text.trim():null}))});if(result.error)throw result.error;setEditing(null);setMessage('Bundle saved.');await load()}catch(e){await load();setError(formError(e,'Unable to save the bundle.'))}finally{setBusy(false)}}
 async function remove(kind:'package'|'add-on'|'bundle',id:string,name:string){if(busy)return;if(!window.confirm(`Delete ${name}?`))return;setBusy(true);setError('');try{const table=kind==='package'?'intensive_mentoring_packages':kind==='add-on'?'intensive_mentoring_add_ons':'intensive_mentoring_bundles',r=await db.from(table).delete().eq('id',id);if(r.error){if(r.error.code==='23503')throw{code:'P0001',message:'This item is used by a bundle. Deactivate it or update the bundle first.'};throw r.error}setMessage(`${name} deleted.`);await load()}catch(e){setError(formError(e,'Unable to delete the record.'))}finally{setBusy(false)}}
 return <div className={styles.page}><header className={styles.header}><div className={styles.headerCopy}><h2>Intensive Mentoring Catalog</h2></div></header><div className={styles.tabs} role="tablist" aria-label="Intensive Mentoring catalog sections">{([['packages','Main Packages'],['add-ons','Add-ons'],['bundles','Bundles']] as const).map(([id,label])=><button type="button" role="tab" aria-selected={tab===id} className={`${styles.tab} ${tab===id?styles.tabActive:''}`} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 <section className={dataStyles.surface}><div className={styles.surfaceHeading}><div><h3>Manage {title}</h3></div><button type="button" className="button button-primary" onClick={openCreate}><Plus size={15} aria-hidden="true"/>Add {tab==='packages'?'Package':tab==='add-ons'?'Add-On':'Bundle'}</button></div><div className={dataStyles.toolbar}><label className={dataStyles.searchField}>Search<span className={dataStyles.searchControl}><Search aria-hidden="true"/><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder={`Search ${title.toLowerCase()}`}/></span></label><label className={dataStyles.filterField}>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div>{error?<p className={`${styles.feedback} ${styles.error}`} role="alert">{error}</p>:null}{message?<p className={`${styles.feedback} ${styles.success}`} role="status">{message}</p>:null}<CatalogTable tab={tab} rows={pageRows} loading={loading} sortKey={sortKey} sortDirection={sortDirection} changeSort={changeSort} packageFeatures={packageFeatures} addOnFeatures={addOnFeatures} bundleItems={bundleItems} setEditing={setEditing} remove={remove}/><TablePagination language="en" page={currentPage} pageSize={PAGE_SIZE} totalItems={visible.length} onPageChange={setPage} disabled={loading||busy} label={`Pagination Intensive ${tab}`}/></section>
 <dialog ref={dialogRef} className={styles.dialog} onClose={()=>setEditing(null)} onCancel={e=>{e.preventDefault();closeEditor()}} onClick={e=>{if(e.target===e.currentTarget)closeEditor()}} onChangeCapture={()=>{editorDirtyRef.current=true}}>{editing?<Editor editing={editing} error={error} busy={busy} packages={packages} addOns={addOns} featureDrafts={featureDrafts} setFeatureDrafts={value=>{editorDirtyRef.current=true;setFeatureDrafts(value)}} bundleDrafts={bundleDrafts} setBundleDrafts={value=>{editorDirtyRef.current=true;setBundleDrafts(value)}} close={closeEditor} savePackage={savePackage} saveAddOn={saveAddOn} saveBundle={saveBundle}/>:null}</dialog></div>
}

function CatalogTable({tab,rows,loading,sortKey,sortDirection,changeSort,packageFeatures,addOnFeatures,bundleItems,setEditing,remove}:{tab:Tab;rows:Row[];loading:boolean;sortKey:string|null;sortDirection:SortDirection;changeSort:(k:string|null,d:SortDirection)=>void;packageFeatures:PackageFeature[];addOnFeatures:AddOnFeature[];bundleItems:BundleItem[];setEditing:(e:Editing)=>void;remove:(kind:'package'|'add-on'|'bundle',id:string,name:string)=>void}){
 const count=tab==='packages'?7:tab==='add-ons'?5:6
 return <div className={dataStyles.tableScroll}><table className={`${dataStyles.table} ${dataStyles.productTable}`}><thead><tr><SortableTableHeader label={tab==='packages'?'Program':tab==='add-ons'?'Add-On':'Bundle'} sortKey="name" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/>{tab==='packages'?<><th>Sessions / month</th><SortableTableHeader label="Price" sortKey="price" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><th>Regular price</th><th>Mode</th></>:tab==='add-ons'?<><SortableTableHeader label="Price" sortKey="price" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><th>Benefits</th></>:<><SortableTableHeader label="Price" sortKey="price" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><th>Badge</th><th>Items</th></>}<SortableTableHeader label="Status" sortKey="status" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><th className={dataStyles.actionCell}>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={count}>Loading data…</td></tr>:rows.length===0?<tr><td colSpan={count}>No records found.</td></tr>:rows.map(row=>tab==='packages'?<PackageTableRow key={row.id} row={row as PackageRow} setEditing={setEditing} remove={remove}/>:tab==='add-ons'?<AddOnTableRow key={row.id} row={row as AddOnRow} count={addOnFeatures.filter(x=>x.add_on_id===row.id&&x.is_active).length} setEditing={setEditing} remove={remove}/>:<BundleTableRow key={row.id} row={row as BundleRow} count={bundleItems.filter(x=>x.bundle_id===row.id&&x.is_active).length} setEditing={setEditing} remove={remove}/>)}</tbody></table></div>
}
function PackageTableRow({row,setEditing,remove}:{row:PackageRow;setEditing:(e:Editing)=>void;remove:(k:'package',id:string,n:string)=>void}){return <tr><td><strong>{row.name}</strong><span className={styles.description}>{row.description}</span></td><td>{row.sessions_per_month??'Custom'}</td><td>{row.price_amount?formatRupiah(row.price_amount):'Consultation'}</td><td>{row.reference_price_amount?formatRupiah(row.reference_price_amount):'—'}</td><td><span className={row.pricing_mode==='consultation'?styles.statusConsultation:styles.statusActive}>{row.pricing_mode==='consultation'?'Consultation':'Fixed price'}</span></td><td><Status active={row.is_active}/></td><td className={dataStyles.actionCell}><Actions onEdit={()=>setEditing({kind:'package',row})} onDelete={()=>void remove('package',row.id,row.name)}/></td></tr>}
function AddOnTableRow({row,count,setEditing,remove}:{row:AddOnRow;count:number;setEditing:(e:Editing)=>void;remove:(k:'add-on',id:string,n:string)=>void}){return <tr><td><strong>{row.name}</strong><span className={styles.description}>{row.description}</span></td><td>+{formatRupiah(row.price_amount)}</td><td>{count}</td><td><Status active={row.is_active}/></td><td className={dataStyles.actionCell}><Actions onEdit={()=>setEditing({kind:'add-on',row})} onDelete={()=>void remove('add-on',row.id,row.name)}/></td></tr>}
function BundleTableRow({row,count,setEditing,remove}:{row:BundleRow;count:number;setEditing:(e:Editing)=>void;remove:(k:'bundle',id:string,n:string)=>void}){return <tr><td><strong>{row.name}</strong><span className={styles.description}>{row.description}</span></td><td>{formatRupiah(row.price_amount)}</td><td>{row.badge_text??'—'}</td><td>{count}</td><td><Status active={row.is_active}/></td><td className={dataStyles.actionCell}><Actions onEdit={()=>setEditing({kind:'bundle',row})} onDelete={()=>void remove('bundle',row.id,row.name)}/></td></tr>}
function Status({active}:{active:boolean}){return <span className={active?styles.statusActive:styles.statusInactive}>{active?'Active':'Inactive'}</span>}
function Actions({onEdit,onDelete}:{onEdit:()=>void;onDelete:()=>void}){return <div className={styles.actions}><button type="button" className={`button button-outline ${dataStyles.actionButton}`} onClick={onEdit}><Pencil size={14}/>Manage</button><button type="button" className={`button button-outline ${dataStyles.actionButton} ${styles.danger}`} onClick={onDelete}><Trash2 size={14}/>Delete</button></div>}

function Editor({editing,error,busy,packages,addOns,featureDrafts,setFeatureDrafts,bundleDrafts,setBundleDrafts,close,savePackage,saveAddOn,saveBundle}:{editing:Editing;error:string;busy:boolean;packages:PackageRow[];addOns:AddOnRow[];featureDrafts:string[];setFeatureDrafts:(v:string[]|((x:string[])=>string[]))=>void;bundleDrafts:BundleDraft[];setBundleDrafts:(v:BundleDraft[]|((x:BundleDraft[])=>BundleDraft[]))=>void;close:()=>void;savePackage:(e:FormEvent<HTMLFormElement>,r:PackageRow|null)=>void;saveAddOn:(e:FormEvent<HTMLFormElement>,r:AddOnRow|null)=>void;saveBundle:(e:FormEvent<HTMLFormElement>,r:BundleRow|null)=>void}){
 const row=editing.row
 const heading=row?`Edit ${row.name}`:`Add ${editing.kind==='package'?'Package':editing.kind==='add-on'?'Add-On':'Bundle'}`
 return <div className={styles.dialogPanel}><header className={styles.dialogHeader}><div><h2>{heading}</h2></div><button type="button" className={styles.close} onClick={close} disabled={busy} aria-label="Close dialog"><X size={17}/></button></header>{editing.kind==='package'?<PackageForm row={editing.row} error={error} busy={busy} features={featureDrafts} setFeatures={setFeatureDrafts} close={close} save={savePackage}/>:editing.kind==='add-on'?<AddOnForm row={editing.row} error={error} busy={busy} features={featureDrafts} setFeatures={setFeatureDrafts} close={close} save={saveAddOn}/>:<BundleForm row={editing.row} error={error} busy={busy} packages={packages} addOns={addOns} items={bundleDrafts} setItems={setBundleDrafts} close={close} save={saveBundle}/>}</div>
}
function CommonFields({row}:{row:PackageRow|AddOnRow|BundleRow|null}){return <><label className={`${styles.field} ${styles.full}`}>Name<input name="name" required maxLength={160} defaultValue={row?.name??''}/></label><label className={`${styles.field} ${styles.full}`}>Description<textarea name="description" required defaultValue={row?.description??''}/></label></>}
function FormActions({busy,close}:{busy:boolean;close:()=>void}){return <div className={styles.actions}><button type="button" className="button button-outline" disabled={busy} onClick={close}>Cancel</button><button className="button button-primary" disabled={busy}>Save</button></div>}
function PackageForm({row,error,busy,features,setFeatures,close,save}:{row:PackageRow|null;error:string;busy:boolean;features:string[];setFeatures:(v:string[]|((x:string[])=>string[]))=>void;close:()=>void;save:(e:FormEvent<HTMLFormElement>,r:PackageRow|null)=>void}){return <form className={styles.dialogBody} onSubmit={e=>void save(e,row)}><fieldset disabled={busy} style={{border:0,margin:0,padding:0,minWidth:0,display:'grid',gap:16}}>{error?<p className={`${styles.feedback} ${styles.error}`} role="alert">{error}</p>:null}<div className={styles.formGrid}><CommonFields row={row}/><label className={styles.field}>Scope<select name="competition_scope" defaultValue={row?.competition_scope??'national'}><option value="national">National competition</option><option value="international">International competition</option></select></label><label className={styles.field}>Sessions / month<input name="sessions_per_month" type="number" min="1" defaultValue={row?.sessions_per_month??''}/></label><label className={styles.field}>Pricing mode<select name="pricing_mode" defaultValue={row?.pricing_mode??'fixed'}><option value="fixed">Fixed price</option><option value="consultation">Consultation</option></select></label><label className={styles.field}>Price<input name="price_amount" type="number" min="1" defaultValue={row?.price_amount??''}/></label><label className={styles.field}>Regular price<input name="reference_price_amount" type="number" min="1" defaultValue={row?.reference_price_amount??''}/></label><OrderActive row={row}/></div><FeatureEditor items={features} setItems={setFeatures}/><FormActions busy={busy} close={close}/></fieldset></form>}
function AddOnForm({row,error,busy,features,setFeatures,close,save}:{row:AddOnRow|null;error:string;busy:boolean;features:string[];setFeatures:(v:string[]|((x:string[])=>string[]))=>void;close:()=>void;save:(e:FormEvent<HTMLFormElement>,r:AddOnRow|null)=>void}){return <form className={styles.dialogBody} onSubmit={e=>void save(e,row)}><fieldset disabled={busy} style={{border:0,margin:0,padding:0,minWidth:0,display:'grid',gap:16}}>{error?<p className={`${styles.feedback} ${styles.error}`} role="alert">{error}</p>:null}<div className={styles.formGrid}><CommonFields row={row}/><label className={styles.field}>Add-on price<input name="price_amount" type="number" min="1" required defaultValue={row?.price_amount??''}/></label><label className={`${styles.field} ${styles.full}`}>Terms note<textarea name="terms_note" defaultValue={row?.terms_note??''}/></label><OrderActive row={row}/></div>{row?.code==='WIN_GUARANTEE_PROTECTION'?<p className={styles.notice}>Terms and eligibility assessment apply. This setting does not automatically issue refunds or program credits.</p>:null}<FeatureEditor items={features} setItems={setFeatures}/><FormActions busy={busy} close={close}/></fieldset></form>}
function BundleForm({row,error,busy,packages,addOns,items,setItems,close,save}:{row:BundleRow|null;error:string;busy:boolean;packages:PackageRow[];addOns:AddOnRow[];items:BundleDraft[];setItems:(v:BundleDraft[]|((x:BundleDraft[])=>BundleDraft[]))=>void;close:()=>void;save:(e:FormEvent<HTMLFormElement>,r:BundleRow|null)=>void}){const patch=(i:number,p:Partial<BundleDraft>)=>setItems(x=>x.map((v,n)=>n===i?{...v,...p}:v));return <form className={styles.dialogBody} onSubmit={e=>void save(e,row)}><fieldset disabled={busy} style={{border:0,margin:0,padding:0,minWidth:0,display:'grid',gap:16}}>{error?<p className={`${styles.feedback} ${styles.error}`} role="alert">{error}</p>:null}<div className={styles.formGrid}><CommonFields row={row}/><label className={styles.field}>Price<input name="price_amount" type="number" min="1" required defaultValue={row?.price_amount??''}/></label><label className={styles.field}>Badge<input name="badge_text" maxLength={120} defaultValue={row?.badge_text??''}/></label><OrderActive row={row}/></div>{row?.code==='COMPETITION_ASSURANCE'?<p className={styles.notice}>This bundle requires active Win Guarantee Protection. The bundle price is used, rather than the sum of its components.</p>:null}<div className={styles.repeatable}><div className={styles.repeatableHeader}><strong>Bundle items</strong><button type="button" className="button button-outline" onClick={()=>setItems(x=>[...x,{itemType:'feature',referenceId:'',text:''}])}><Plus size={14}/>Add item</button></div>{items.map((item,i)=><div className={styles.bundleRow} key={i}><select value={item.itemType} onChange={e=>patch(i,{itemType:e.target.value as BundleDraft['itemType'],referenceId:'',text:''})}><option value="package">Package</option><option value="add_on">Add-On</option><option value="feature">Text benefit</option></select>{item.itemType==='package'?<select value={item.referenceId} onChange={e=>patch(i,{referenceId:e.target.value})}><option value="">Select a package</option>{packages.map(p=><option key={p.id} value={p.id}>{p.name}{p.is_active?'':' · inactive'}</option>)}</select>:item.itemType==='add_on'?<select value={item.referenceId} onChange={e=>patch(i,{referenceId:e.target.value})}><option value="">Select an add-on</option>{addOns.map(a=><option key={a.id} value={a.id}>{a.name}{a.is_active?'':' · inactive'}</option>)}</select>:<input value={item.text} onChange={e=>patch(i,{text:e.target.value})} placeholder="Benefit"/>}<button type="button" className="button button-outline" onClick={()=>setItems(x=>x.filter((_,n)=>n!==i))} aria-label="Remove item"><Minus size={14}/></button></div>)}</div><FormActions busy={busy} close={close}/></fieldset></form>}
function OrderActive({row}:{row:{sort_order:number;is_active:boolean}|null}){return <><label className={styles.field}>Display order<input name="sort_order" type="number" min="0" required defaultValue={row?.sort_order??0}/></label><label className={`${styles.field} ${styles.checkbox}`}><input name="is_active" type="checkbox" defaultChecked={row?.is_active??true}/> Active</label></>}
function FeatureEditor({items,setItems}:{items:string[];setItems:(v:string[]|((x:string[])=>string[]))=>void}){return <div className={styles.repeatable}><div className={styles.repeatableHeader}><strong>Benefits / features</strong><button type="button" className="button button-outline" onClick={()=>setItems(x=>[...x,''])}><Plus size={14}/>Add benefit</button></div>{items.map((item,i)=><div className={styles.repeatableRow} key={i}><input value={item} onChange={e=>setItems(x=>x.map((v,n)=>n===i?e.target.value:v))} placeholder="Enter a benefit"/><button type="button" className="button button-outline" onClick={()=>setItems(x=>x.filter((_,n)=>n!==i))} aria-label="Remove benefit"><Minus size={14}/></button></div>)}</div>}
