'use client'

import {Check,Loader2,Pencil,Plus,Search,ShoppingCart,X} from 'lucide-react'
import {useCallback,useEffect,useRef,useState} from 'react'
import {formatRupiah} from '@/lib/commerce/money'
import {createClient} from '@/lib/supabase/client'

type Mentee={user_id:string;email:string;display_name:string|null}
type AddOn={id:string;name:string;code:string}
type Category={id:string;name:string}
type Offer={offer_id:string;intended_mentee_id:string;mentee_name:string|null;mentee_email:string;title:string;competition_category_id:string|null;competition_category_name:string|null;competition_name:string;baseline_sessions_per_month:number|null;final_price_amount:number;status:string;expires_at:string|null;created_at:string;updated_at:string;included_add_ons:AddOn[];benefits:string[]}
type RpcClient={rpc<T=unknown>(name:string,args?:Record<string,unknown>):Promise<{data:T|null;error:{message:string}|null}>}
type Mode='create'|'view'|'edit'

export function IntensiveInternationalOfferManagement(){
 const[supabase]=useState(()=>createClient());const rpc=supabase as unknown as RpcClient
 const[offers,setOffers]=useState<Offer[]>([]),[addOns,setAddOns]=useState<AddOn[]>([]),[categories,setCategories]=useState<Category[]>([])
 const[mode,setMode]=useState<Mode>('view'),[activeOffer,setActiveOffer]=useState<Offer|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[generatedUrl,setGeneratedUrl]=useState('')
 const[menteeQuery,setMenteeQuery]=useState(''),[mentees,setMentees]=useState<Mentee[]>([]),[menteeId,setMenteeId]=useState(''),[selectedMentee,setSelectedMentee]=useState<Mentee|null>(null),[menteeLoading,setMenteeLoading]=useState(false)
 const[competitionName,setCompetitionName]=useState(''),[categoryId,setCategoryId]=useState(''),[baseline,setBaseline]=useState(''),[price,setPrice]=useState(''),[expiresAt,setExpiresAt]=useState(''),[selectedAddOns,setSelectedAddOns]=useState<string[]>([]),[benefits,setBenefits]=useState<string[]>([''])
 const dialogRef=useRef<HTMLDialogElement>(null)
 const load=useCallback(async()=>{const [offerResult,addOnResult,categoryResult]=await Promise.all([rpc.rpc<Offer[]>('list_admin_intensive_custom_offers'),supabase.from('intensive_mentoring_add_ons').select('id,name,code').eq('is_active',true).order('sort_order'),supabase.from('competition_categories').select('id,name').eq('is_active',true).order('sort_order')]);if(offerResult.error)setError(offerResult.error.message);else setOffers(offerResult.data??[]);if(!addOnResult.error)setAddOns((addOnResult.data??[]) as AddOn[]);if(!categoryResult.error)setCategories((categoryResult.data??[]) as Category[])},[rpc,supabase])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{const dialog=dialogRef.current;if(!dialog)return;if(open&&!dialog.open)dialog.showModal();if(!open&&dialog.open)dialog.close()},[open])
 useEffect(()=>{if(!open||mode==='view')return;const timer=setTimeout(async()=>{setMenteeLoading(true);const result=await rpc.rpc<Mentee[]>('list_cart_link_mentees',{p_query:menteeQuery.trim()});setMenteeLoading(false);if(!result.error)setMentees(result.data??[])},220);return()=>clearTimeout(timer)},[menteeQuery,mode,open,rpc])
 function resetDraft(){setMenteeQuery('');setMentees([]);setMenteeId('');setSelectedMentee(null);setCompetitionName('');setCategoryId('');setBaseline('');setPrice('');setExpiresAt('');setSelectedAddOns([]);setBenefits(['']);setError('');setMessage('');setGeneratedUrl('')}
 function applyOffer(o:Offer){setMenteeId(o.intended_mentee_id);setSelectedMentee({user_id:o.intended_mentee_id,email:o.mentee_email,display_name:o.mentee_name});setMenteeQuery(o.mentee_name||o.mentee_email);setCompetitionName(o.competition_name);setCategoryId(o.competition_category_id??'');setBaseline(o.baseline_sessions_per_month?.toString()??'');setPrice(o.final_price_amount.toString());setExpiresAt(o.expires_at?new Date(o.expires_at).toISOString().slice(0,16):'');setSelectedAddOns(o.included_add_ons.map(x=>x.id));setBenefits(o.benefits.length?o.benefits:['']);setError('');setMessage('');setGeneratedUrl('')}
 function openCreate(){resetDraft();setActiveOffer(null);setMode('create');setOpen(true)}
 function openView(o:Offer){setActiveOffer(o);applyOffer(o);setMode('view');setOpen(true)}
 function close(){setOpen(false);setActiveOffer(null);setMode('view');resetDraft()}
 function cancelEdit(){if(activeOffer){applyOffer(activeOffer);setMode('view')}else close()}
 function chooseMentee(m:Mentee){setSelectedMentee(m);setMenteeId(m.user_id);setMenteeQuery(m.display_name||m.email);setMentees([])}
 function toggleAddOn(id:string){setSelectedAddOns(xs=>xs.includes(id)?xs.filter(x=>x!==id):[...xs,id])}
 async function save(){const amount=Number(price),base=baseline?Number(baseline):null;if(!menteeId||competitionName.trim().length<2){setError('Pilih mentee dan isi nama kompetisi.');return}if(!Number.isSafeInteger(amount)||amount<=0){setError('Harga kesepakatan harus berupa Rupiah integer positif.');return}if(base!==null&&(!Number.isInteger(base)||base<1||base>100)){setError('Baseline harus 1–100 sesi/bulan atau dikosongkan.');return}setBusy(true);setError('');const result=await rpc.rpc<string>('admin_save_intensive_custom_offer',{p_id:activeOffer?.offer_id??null,p_mentee_id:menteeId,p_competition_category_id:categoryId||null,p_competition_name:competitionName.trim(),p_baseline_sessions_per_month:base,p_final_price_amount:amount,p_expires_at:expiresAt?new Date(expiresAt).toISOString():null,p_add_on_ids:selectedAddOns,p_benefits:benefits.map(x=>x.trim()).filter(Boolean)});setBusy(false);if(result.error||!result.data){setError(result.error?.message||'Penawaran belum dapat disimpan.');return}const list=await rpc.rpc<Offer[]>('list_admin_intensive_custom_offers');const saved=(list.data??[]).find(x=>x.offer_id===result.data);setOffers(list.data??[]);if(saved){setActiveOffer(saved);applyOffer(saved);setMode('view');setMessage('Penawaran internasional tersimpan.')}}
 async function createCartLink(){if(!activeOffer)return;setBusy(true);setError('');setGeneratedUrl('');try{const response=await fetch('/api/admin/cart-links',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({menteeId:activeOffer.intended_mentee_id,commerceItemIds:[activeOffer.offer_id]})});const body=await response.json() as{url?:string;error?:string};if(!response.ok||!body.url)throw new Error(body.error||'Cart Link belum dapat dibuat.');setGeneratedUrl(body.url);setMessage('Cart Link untuk penawaran internasional berhasil dibuat.')}catch(e){setError(e instanceof Error?e.message:'Cart Link belum dapat dibuat.')}finally{setBusy(false)}}
 return <section className="role-card intensive-custom-offers"><div className="ops-section-heading intensive-custom-offers__heading"><div><p className="kicker">International custom commerce</p><h3>Penawaran Internasional</h3><p>Harga negosiasi menjadi source of truth domain Intensive, sementara checkout tetap memakai Shared Commerce.</p></div><button type="button" className="button button-outline" onClick={openCreate}><Plus aria-hidden="true" size={15}/>Penawaran Internasional</button></div>
  <div className="ops-table-wrap"><table className="ops-table intensive-custom-offer-table"><thead><tr><th>Mentee</th><th>Kompetisi</th><th>Baseline</th><th>Harga</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{offers.length?offers.map(o=><tr key={o.offer_id}><td data-label="Mentee"><strong>{o.mentee_name||o.mentee_email}</strong><small>{o.mentee_email}</small></td><td data-label="Kompetisi"><strong>{o.competition_name}</strong><small>{o.competition_category_name||'Kategori fleksibel'}</small></td><td data-label="Baseline">{o.baseline_sessions_per_month?o.baseline_sessions_per_month+' sesi/bln':'Fleksibel'}</td><td data-label="Harga"><strong>{formatRupiah(o.final_price_amount)}</strong></td><td data-label="Status"><span className="ops-status ops-status--info">{o.status}</span></td><td data-label="Aksi"><button type="button" className="button button-outline button-compact" onClick={()=>openView(o)}>Lihat</button></td></tr>):<tr><td colSpan={6}>Belum ada penawaran internasional custom.</td></tr>}</tbody></table></div>
  <dialog ref={dialogRef} className="ops-dialog intensive-custom-offer-dialog" aria-labelledby="international-offer-title" onCancel={e=>{e.preventDefault();close()}} onClose={()=>setOpen(false)}>{open?<div className="ops-dialog__surface intensive-custom-offer-dialog__surface"><header className="ops-dialog__header"><div><p className="kicker">Penawaran Intensive Internasional</p><h2 id="international-offer-title">{mode==='create'?'Buat penawaran custom':activeOffer?.competition_name||'Penawaran internasional'}</h2><p>{mode==='view'?'Detail tersimpan read-only sampai Edit dipilih.':'Harga final adalah nilai negosiasi authoritative, bukan penjumlahan otomatis komponen.'}</p></div><button type="button" className="ops-icon-button" onClick={close} aria-label="Tutup penawaran internasional"><X aria-hidden="true"/></button></header>
   {error?<p className="form-error" role="alert">{error}</p>:null}{message?<p className="form-success" role="status">{message}</p>:null}
   {mode==='view'&&activeOffer?<><div className="intensive-offer-read-grid"><div className="ops-readonly-field"><span>Mentee</span><strong>{activeOffer.mentee_name||activeOffer.mentee_email}</strong><small>{activeOffer.mentee_email}</small></div><div className="ops-readonly-field"><span>Nama kompetisi</span><strong>{activeOffer.competition_name}</strong><small>{activeOffer.competition_category_name||'Kategori fleksibel'}</small></div><div className="ops-readonly-field"><span>Baseline</span><strong>{activeOffer.baseline_sessions_per_month?activeOffer.baseline_sessions_per_month+' sesi/bulan':'Fleksibel'}</strong></div><div className="ops-readonly-field"><span>Harga kesepakatan</span><strong>{formatRupiah(activeOffer.final_price_amount)}</strong></div><div className="ops-readonly-field"><span>Status</span><strong>{activeOffer.status}</strong></div><div className="ops-readonly-field"><span>Berlaku sampai</span><strong>{activeOffer.expires_at?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(activeOffer.expires_at)):'Tanpa batas khusus'}</strong></div></div><section className="ops-dialog__section"><h3>Included support</h3><div className="intensive-config-chips">{activeOffer.included_add_ons.map(x=><span className="intensive-addon-chip" key={x.id}>{x.name}</span>)}</div>{activeOffer.benefits.length?<><h3>Benefit tambahan</h3><div className="intensive-config-chips">{activeOffer.benefits.map((x,i)=><span className="intensive-addon-chip" key={x+i}>{x}</span>)}</div></>:null}</section><div className="intensive-config-actions"><button type="button" className="button button-outline" disabled={activeOffer.status!=='active'} onClick={()=>{applyOffer(activeOffer);setMode('edit')}}><Pencil aria-hidden="true" size={15}/>Edit</button><button type="button" className="button button-primary" disabled={busy||activeOffer.status!=='active'} onClick={()=>void createCartLink()}><ShoppingCart aria-hidden="true" size={15}/>{busy?'Membuat…':'Buat Cart Link'}</button></div>{generatedUrl?<div className="cart-link-result"><p>{generatedUrl}</p><button type="button" className="button button-outline" onClick={()=>void navigator.clipboard.writeText(generatedUrl)}>Copy Cart Link</button></div>:null}</>:<div className="intensive-offer-form">
    <label className="ops-field ops-field--wide"><span>Mentee</span><div className="ops-input-with-icon"><Search aria-hidden="true" size={15}/><input value={menteeQuery} onChange={e=>{setMenteeQuery(e.target.value);setMenteeId('');setSelectedMentee(null)}} placeholder="Cari nama atau email"/>{menteeLoading?<Loader2 className="spin" aria-hidden="true" size={15}/>:null}</div>{selectedMentee?<small>Terpilih: {selectedMentee.display_name||selectedMentee.email} · {selectedMentee.email}</small>:null}{mentees.length?<div className="ops-combobox-options" role="listbox" aria-label="Hasil pencarian mentee">{mentees.map(m=><button type="button" role="option" aria-selected={m.user_id===menteeId} onClick={()=>chooseMentee(m)} key={m.user_id}><strong>{m.display_name||'Mentee Strativate'}</strong><span>{m.email}</span></button>)}</div>:null}</label>
    <div className="intensive-offer-form__grid"><label className="ops-field"><span>Nama kompetisi</span><input maxLength={300} value={competitionName} onChange={e=>setCompetitionName(e.target.value)} placeholder="Harvard Global Case Competition"/></label><label className="ops-field"><span>Kategori <small>opsional</small></span><select value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Tanpa kategori</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="ops-field"><span>Baseline / intensitas <small>opsional</small></span><input type="number" min={1} max={100} value={baseline} onChange={e=>setBaseline(e.target.value)}/><small>sesi / bulan</small></label><label className="ops-field"><span>Harga kesepakatan</span><input type="number" min={1} step={1} value={price} onChange={e=>setPrice(e.target.value)}/><small>Rupiah integer; harga final tidak dijumlah otomatis.</small></label><label className="ops-field"><span>Berlaku sampai <small>opsional</small></span><input type="datetime-local" value={expiresAt} onChange={e=>setExpiresAt(e.target.value)}/></label></div>
    <fieldset className="intensive-offer-support"><legend>Included support</legend>{addOns.map(a=><label key={a.id} className="intensive-offer-support__item"><input type="checkbox" checked={selectedAddOns.includes(a.id)} onChange={()=>toggleAddOn(a.id)}/><span className="intensive-offer-support__check">{selectedAddOns.includes(a.id)?<Check aria-hidden="true" size={13}/>:null}</span><span>{a.name}</span></label>)}</fieldset>
    <section className="intensive-offer-benefits"><div className="intensive-config-card__heading"><div><span>Custom support</span><h3>Benefit tambahan</h3></div><button type="button" className="button button-outline button-compact" onClick={()=>setBenefits(xs=>[...xs,''])}><Plus aria-hidden="true" size={14}/>Tambah benefit</button></div>{benefits.map((b,i)=><div className="intensive-offer-benefit-row" key={i}><label className="ops-field"><span>Benefit {i+1}</span><input maxLength={500} value={b} onChange={e=>setBenefits(xs=>xs.map((x,n)=>n===i?e.target.value:x))} placeholder="International pitch deck review"/></label><button type="button" className="ops-icon-button" aria-label={'Hapus benefit '+(i+1)} onClick={()=>setBenefits(xs=>xs.filter((_,n)=>n!==i))}><X aria-hidden="true" size={15}/></button></div>)}</section>
    <div className="intensive-config-actions"><button type="button" className="button button-primary" disabled={busy||!menteeId||!competitionName.trim()||!price} onClick={()=>void save()}>{busy?'Menyimpan…':'Simpan penawaran'}</button><button type="button" className="button button-outline" disabled={busy} onClick={mode==='edit'?cancelEdit:close}>Batal</button></div>
   </div>}
  </div>:null}</dialog>
 </section>
}