'use client'

import {CalendarDays,Eye,Pencil,Plus,RefreshCw,Save,ShieldAlert,UserRound,X} from 'lucide-react'
import {useCallback,useEffect,useRef,useState} from 'react'
import {CopyTextButton} from '@/components/dashboard/copy-text-button'
import {useOperationalInvalidation} from '@/components/realtime/operational-realtime-provider'
import {createClient} from '@/lib/supabase/client'
import {intensiveStageLabels,type IntensiveProgramStage,type IntensiveSessionView} from '@/lib/intensive-mentoring/types'
import {AdminScheduleDialog} from './admin-schedule-dialog'
import {AdminSessionOperations} from './private-mentoring-session-operations'

type AddOn={entitlementId:string|null;name:string;code:string;status?:string;createdAt?:string;source?:'attached'|'bundle'|'custom_offer';supportType?:'add_on'|'benefit'}
type AdminSession=IntensiveSessionView&{providerSyncStatus?:string;creationReason?:string|null}
type Engagement={engagement_id:string;mentee_id:string;mentee_name:string|null;mentee_email:string;base_entitlement_id:string;base_kind:'package'|'bundle'|'custom_offer';program_name:string;status:string;baseline_sessions_per_month:number|null;primary_mentor_id:string|null;primary_mentor_name:string|null;program_stage:IntensiveProgramStage;current_activity:string|null;progress_summary:string|null;created_at:string;add_ons:AddOn[];sessions:AdminSession[];unassigned_add_ons:AddOn[]}
type Mentor={id:string;name:string}
type Focus={id:string;name:string}
type RpcClient={rpc<T=unknown>(name:string,args?:Record<string,unknown>):Promise<{data:T|null;error:{message:string}|null}>}
const STAGES=Object.entries(intensiveStageLabels) as [IntensiveProgramStage,string][]
const typeLabel=(kind:Engagement['base_kind'])=>kind==='bundle'?'Bundle':kind==='custom_offer'?'Custom':'Package'
const topicStatusLabel=(status:string)=>status==='confirmed'?'Confirmed':status.replaceAll('_',' ')
function scheduleLabel(item:AdminSession){
 if(!item.scheduledStartAt)return'Belum dijadwalkan'
 const zone='Asia/Jakarta',date=new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric',timeZone:zone}).format(new Date(item.scheduledStartAt))
 const time=new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit',hourCycle:'h23',timeZone:zone})
 const start=time.format(new Date(item.scheduledStartAt)).replace('.',':'),end=item.scheduledEndAt?time.format(new Date(item.scheduledEndAt)).replace('.',':'):null
 return`${date} · ${start}${end?'–'+end:''} WIB`
}

export function IntensiveMentoringSessionManagement(){
 const[supabase]=useState(()=>createClient())
 const rpc=supabase as unknown as RpcClient
 const[rows,setRows]=useState<Engagement[]>([]),[mentors,setMentors]=useState<Mentor[]>([]),[focuses,setFocuses]=useState<Focus[]>([])
 const[selectedId,setSelectedId]=useState(''),[session,setSession]=useState<AdminSession|null>(null),[scheduleId,setScheduleId]=useState<string|null>(null)
 const[configOpen,setConfigOpen]=useState(false),[editingDedicatedMentor,setEditingDedicatedMentor]=useState(false),[editingProgramProgress,setEditingProgramProgress]=useState(false),[addingSession,setAddingSession]=useState(false)
 const[editingSessionTopic,setEditingSessionTopic]=useState(false),[editingSessionMentor,setEditingSessionMentor]=useState(false)
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('')
 const[primaryMentor,setPrimaryMentor]=useState(''),[mentorReason,setMentorReason]=useState('')
 const[stage,setStage]=useState<IntensiveProgramStage>('goal_setting'),[currentActivity,setCurrentActivity]=useState(''),[progress,setProgress]=useState('')
 const[duration,setDuration]=useState(''),[sessionReason,setSessionReason]=useState('')
 const[topicFocus,setTopicFocus]=useState(''),[resolvedTopic,setResolvedTopic]=useState(''),[sessionMentor,setSessionMentor]=useState(''),[sessionMentorReason,setSessionMentorReason]=useState('')
 const configRef=useRef<HTMLDialogElement>(null),dialogRef=useRef<HTMLDialogElement>(null)
 const selected=rows.find(row=>row.engagement_id===selectedId)??rows[0]??null

 const load=useCallback(async()=>{
  setError('')
  const [engagements,mentorRows,focusRows]=await Promise.all([
   rpc.rpc<Engagement[]>('list_admin_intensive_mentoring_engagements'),
   supabase.from('mentor_profiles').select('user_id,is_active').eq('is_active',true),
   supabase.from('private_mentoring_session_focuses').select('id,name').eq('is_active',true).order('sort_order'),
  ])
  if(engagements.error){setError(engagements.error.message);setRows([])}
  else{const next=engagements.data??[];setRows(next);setSelectedId(current=>current&&next.some(row=>row.engagement_id===current)?current:next[0]?.engagement_id??'');setSession(current=>current?next.flatMap(row=>row.sessions).find(item=>item.sessionId===current.sessionId)??null:null)}
  if(!mentorRows.error&&mentorRows.data?.length){const ids=mentorRows.data.map(row=>row.user_id),profiles=await supabase.from('profiles').select('id,first_name,last_name,username').in('id',ids);if(!profiles.error)setMentors((profiles.data??[]).map(row=>({id:row.id,name:[row.first_name,row.last_name].filter(Boolean).join(' ')||row.username||'Mentor Strativate'})).sort((a,b)=>a.name.localeCompare(b.name,'id-ID')))}
  if(!focusRows.error)setFocuses((focusRows.data??[]) as Focus[])
  setLoading(false)
 },[rpc,supabase])

 useEffect(()=>{void load()},[load])
 useEffect(()=>{if(!selected)return;setPrimaryMentor(selected.primary_mentor_id??'');setMentorReason('');setStage(selected.program_stage);setCurrentActivity(selected.current_activity??'');setProgress(selected.progress_summary??'')},[selected])
 useEffect(()=>{const d=configRef.current;if(!d)return;if(configOpen&&!d.open)d.showModal();if(!configOpen&&d.open)d.close()},[configOpen])
 useEffect(()=>{const d=dialogRef.current;if(!d)return;if(session&&!d.open)d.showModal();if(!session&&d.open)d.close();if(session){setTopicFocus(session.focusId??'');setResolvedTopic(session.resolvedTopic??session.menteeTopicRequest??'');setSessionMentor(session.mentorId??selected?.primary_mentor_id??'');setSessionMentorReason('')}},[selected,session])
 useOperationalInvalidation(['mentoring', 'provider'],()=>{void load()})

 async function run(key:string,name:string,args:Record<string,unknown>,success:string){setBusy(key);setError('');setMessage('');const result=await rpc.rpc(name,args);setBusy('');if(result.error){setError(result.error.message);return false}setMessage(success);await load();return true}
 function resetMentorDraft(){if(!selected)return;setPrimaryMentor(selected.primary_mentor_id??'');setMentorReason('');setEditingDedicatedMentor(false)}
 function resetProgressDraft(){if(!selected)return;setStage(selected.program_stage);setCurrentActivity(selected.current_activity??'');setProgress(selected.progress_summary??'');setEditingProgramProgress(false)}
 function resetSessionTopicDraft(){if(!session)return;setTopicFocus(session.focusId??'');setResolvedTopic(session.resolvedTopic??session.menteeTopicRequest??'');setEditingSessionTopic(false)}
 function resetSessionMentorDraft(){if(!session)return;setSessionMentor(session.mentorId??selected?.primary_mentor_id??'');setSessionMentorReason('');setEditingSessionMentor(false)}
 function closeSessionDetail(){setEditingSessionTopic(false);setEditingSessionMentor(false);setSession(null)}
 function closeConfig(){resetMentorDraft();resetProgressDraft();setAddingSession(false);setDuration('');setSessionReason('');setConfigOpen(false)}
 async function savePrimary(){if(!selected||!primaryMentor)return;const ok=await run('primary','admin_set_intensive_primary_mentor',{p_engagement_id:selected.engagement_id,p_mentor_id:primaryMentor,p_reason:mentorReason.trim()||null},'Dedicated Mentor diperbarui.');if(ok){setMentorReason('');setEditingDedicatedMentor(false)}}
 async function saveStage(){if(!selected)return;const ok=await run('stage','admin_set_intensive_program_stage',{p_engagement_id:selected.engagement_id,p_stage:stage,p_progress_summary:progress.trim()||null,p_current_activity:currentActivity.trim()||null},'Tahap program, aktivitas saat ini, dan ringkasan progres diperbarui.');if(ok)setEditingProgramProgress(false)}
 async function addSession(){if(!selected)return;const minutes=Number(duration);if(!Number.isInteger(minutes)||minutes<15||minutes>240){setError('Masukkan durasi sesi 15–240 menit. Durasi tidak diasumsikan dari paket.');return}const ok=await run('add','admin_add_intensive_mentoring_session',{p_engagement_id:selected.engagement_id,p_duration_minutes:minutes,p_reason:sessionReason.trim()||null},'Sesi baru ditambahkan tanpa mengubah nilai order atau invoice.');if(ok){setDuration('');setSessionReason('');setAddingSession(false)}}
 async function attachAddOn(entitlementId:string){if(!selected)return;await run('addon:'+entitlementId,'admin_attach_intensive_add_on',{p_entitlement_id:entitlementId,p_engagement_id:selected.engagement_id,p_note:'Admin reconciliation from Intensive Mentoring operations.'},'Add-on ditautkan ke engagement.')}
 async function resolveTopic(){if(!session||!topicFocus||resolvedTopic.trim().length<2){setError('Pilih fokus dan isi topik final.');return}const nextFocus=focuses.find(focus=>focus.id===topicFocus);const ok=await run('topic','admin_resolve_intensive_mentoring_topic',{p_session_id:session.sessionId,p_focus_id:topicFocus,p_resolved_topic:resolvedTopic.trim(),p_note:null},'Topik sesi dikonfirmasi.');if(ok){setSession(current=>current?{...current,focusId:topicFocus,focusName:nextFocus?.name??current.focusName,resolvedTopic:resolvedTopic.trim(),topicStatus:'confirmed'}:current);setEditingSessionTopic(false)}}
 async function assignSessionMentor(){if(!session||!sessionMentor)return;const nextMentor=mentors.find(mentor=>mentor.id===sessionMentor);const ok=await run('mentor','admin_assign_intensive_session_mentor',{p_session_id:session.sessionId,p_mentor_id:sessionMentor,p_reason:sessionMentorReason.trim()||null},'Mentor sesi diperbarui dan tercatat di audit.');if(ok){setSession(current=>current?{...current,mentorId:sessionMentor,mentorName:nextMentor?.name??current.mentorName}:current);setSessionMentorReason('');setEditingSessionMentor(false)}}
 async function cancelSession(){if(!session||!window.confirm('Batalkan sesi Intensive Mentoring ini?'))return;setBusy('cancel');setError('');const response=await fetch('/api/admin/intensive-mentoring/sessions/'+session.sessionId+'/cancel',{method:'POST'}),body=await response.json() as{error?:string};setBusy('');if(!response.ok){setError(body.error||'Sesi belum dapat dibatalkan.');return}setMessage('Sesi dibatalkan dan Zoom/Calendar direconcile.');setSession(null);await load()}

 if(loading)return <section className="role-card"><p className="muted">Memuat Intensive Mentoring operations…</p></section>
 return <div className="intensive-admin-operations">
  <div className="role-page-title intensive-operations-heading"><div><p className="kicker">Intensive Mentoring</p><h2>Engagement & session operations</h2><p>Baseline paket adalah intensitas layanan, bukan hard cap. Admin dapat menambah sesi sesuai kebutuhan tanpa mengubah order.</p></div><button type="button" className="button button-outline intensive-reload-button" onClick={()=>void load()}><RefreshCw aria-hidden="true" size={16}/><span>Muat ulang</span></button></div>
  {error?<p className="form-error" role="alert">{error}</p>:null}{message?<p className="form-success" role="status">{message}</p>:null}
  {!rows.length?<section className="role-card"><h3>Belum ada engagement Intensive Mentoring.</h3><p className="muted">Engagement dibuat dari entitlement paid package, bundle, atau penawaran internasional custom.</p></section>:<>
   <section className="role-card ops-table-section intensive-engagement-section"><div className="ops-section-heading"><div><p className="kicker">Operational engagements</p><h3>Paid Intensive engagements</h3><p>Pilih engagement untuk menjaga Sessions table di bawah tetap relevan.</p></div><span>{rows.length} data</span></div><div className="ops-table-wrap"><table className="ops-table intensive-engagement-table"><thead><tr><th>Mentee</th><th>Program</th><th>Tipe</th><th>Baseline</th><th>Sesi</th><th>Dedicated Mentor</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.map(row=><tr key={row.engagement_id} className={selected?.engagement_id===row.engagement_id?'is-selected':''}><td data-label="Mentee"><strong>{row.mentee_name||row.mentee_email}</strong><small>{row.mentee_email}</small></td><td data-label="Program"><strong>{row.program_name}</strong></td><td data-label="Tipe">{typeLabel(row.base_kind)}</td><td data-label="Baseline">{row.baseline_sessions_per_month?row.baseline_sessions_per_month+' sesi/bln':'Fleksibel'}</td><td data-label="Sesi">{row.sessions.length}</td><td data-label="Dedicated Mentor">{row.primary_mentor_name||'Belum ditetapkan'}</td><td data-label="Status"><span className="ops-status ops-status--info">{row.status}</span></td><td data-label="Aksi"><div className="intensive-engagement-actions"><button type="button" className="button button-outline button-compact" aria-pressed={selected?.engagement_id===row.engagement_id} onClick={()=>setSelectedId(row.engagement_id)}>Lihat sesi</button><button type="button" className="button button-primary button-compact" onClick={()=>{setSelectedId(row.engagement_id);setConfigOpen(true)}}>Kelola</button></div></td></tr>)}</tbody></table></div></section>
   {selected?<><section className="role-card intensive-selected-summary"><div><p className="kicker">Selected engagement</p><h3>{selected.program_name}</h3><p>{selected.mentee_name||selected.mentee_email} · {typeLabel(selected.base_kind)} · {selected.baseline_sessions_per_month?selected.baseline_sessions_per_month+' sesi/bulan':'Baseline fleksibel'}</p></div><div><span className="ops-status ops-status--info">{selected.status}</span><button type="button" className="button button-outline" onClick={()=>setConfigOpen(true)}><Pencil aria-hidden="true" size={15}/>Kelola program</button></div></section>
    <section className="role-card"><div className="ops-section-heading"><div><p className="kicker">Sessions</p><h3>{selected.sessions.length} sesi operasional</h3><p>Jumlah aktual boleh melampaui baseline dan tidak mengubah invoice.</p></div></div><div className="ops-table-wrap"><table className="ops-table mentee-session-table"><thead><tr><th>Sesi</th><th>Topik / Fokus</th><th>Mentor</th><th>Jadwal</th><th>Status</th><th>Zoom</th><th>Detail</th></tr></thead><tbody>{selected.sessions.length?selected.sessions.map(item=><tr key={item.sessionId}><td data-label="Sesi"><strong>Sesi {item.sessionNumber}</strong><small>{item.durationMinutes} menit · {item.creationSource==='admin_added'?'Admin added':'Baseline'}</small></td><td data-label="Topik / Fokus"><strong>{item.resolvedTopic||item.focusName||item.menteeTopicRequest||'Belum diajukan'}</strong><small>{item.topicStatus}</small></td><td data-label="Mentor">{item.mentorName||selected.primary_mentor_name||'Belum ditetapkan'}</td><td data-label="Jadwal">{item.scheduledStartAt?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.scheduledStartAt)):'Belum dijadwalkan'}</td><td data-label="Status"><span className="ops-status ops-status--info">{item.status.replaceAll('_',' ')}</span></td><td data-label="Zoom">{item.status==='scheduled'&&item.meetingUrl?<a className="button button-primary button-compact" href={item.meetingUrl} target="_blank" rel="noopener noreferrer">Zoom</a>:<span className="muted">Belum tersedia</span>}</td><td data-label="Detail"><button type="button" className="button button-outline button-compact" onClick={()=>setSession(item)}><Eye/>Kelola</button></td></tr>):<tr className="responsive-table-empty"><td colSpan={7}>Belum ada sesi. Gunakan Tambah sesi dari Program Configuration.</td></tr>}</tbody></table></div></section>
   </>:null}
  </>}

  <dialog ref={configRef} className="ops-dialog intensive-config-dialog" onCancel={e=>{e.preventDefault();closeConfig()}} onClose={()=>{if(configOpen)closeConfig()}} aria-labelledby="intensive-program-config-title">{selected&&configOpen?<div className="ops-dialog__surface intensive-config-dialog__surface"><header className="ops-dialog__header intensive-config-dialog__header"><div><p className="kicker">Program Configuration</p><h2 id="intensive-program-config-title">{selected.program_name}</h2><p>{selected.mentee_name||selected.mentee_email} · {selected.status} · {selected.baseline_sessions_per_month?'Baseline '+selected.baseline_sessions_per_month+' sesi/bulan':'Baseline fleksibel'}</p></div><button type="button" className="ops-icon-button" onClick={closeConfig} aria-label="Tutup Program Configuration"><X aria-hidden="true"/></button></header>
   <div className="intensive-config-dialog__body"><div className="intensive-config-grid">
    <section className="intensive-config-card"><div className="intensive-config-card__heading"><div><span>Default mentor</span><h3>Dedicated Mentor</h3></div>{!editingDedicatedMentor?<button type="button" className="button button-outline button-compact" onClick={()=>setEditingDedicatedMentor(true)}>{selected.primary_mentor_id?'Edit mentor':'Set mentor'}</button>:null}</div><p className="intensive-config-helper">Mentor default yang mendampingi peserta sepanjang program. Mentor pada sesi tertentu tetap dapat dioverride bila diperlukan.</p>{editingDedicatedMentor?<div className="ops-form-stack"><label className="ops-field"><span>Dedicated Mentor</span><select value={primaryMentor} onChange={e=>setPrimaryMentor(e.target.value)}><option value="">Pilih mentor</option>{mentors.map(mentor=><option key={mentor.id} value={mentor.id}>{mentor.name}</option>)}</select></label><label className="ops-field"><span>Alasan perubahan <small>opsional</small></span><input value={mentorReason} onChange={e=>setMentorReason(e.target.value)} placeholder="Konteks perubahan mentor"/></label><div className="intensive-config-actions"><button type="button" className="button button-primary" disabled={!primaryMentor||busy==='primary'||primaryMentor===selected.primary_mentor_id} onClick={()=>void savePrimary()}><UserRound aria-hidden="true" size={15}/>{busy==='primary'?'Menyimpan…':'Simpan mentor'}</button><button type="button" className="button button-outline" disabled={busy==='primary'} onClick={resetMentorDraft}>Batal</button></div></div>:<div className="intensive-read-value"><span>Dedicated Mentor</span><strong>{selected.primary_mentor_name||'Belum ditetapkan'}</strong><small>Default untuk sesi baru.</small></div>}</section>
    <section className="intensive-config-card"><div className="intensive-config-card__heading"><div><span>Program tracking</span><h3>Program Progress</h3></div>{!editingProgramProgress?<button type="button" className="button button-outline button-compact" onClick={()=>setEditingProgramProgress(true)}>Edit progres</button>:null}</div>{editingProgramProgress?<div className="ops-form-stack"><label className="ops-field"><span>Tahap Program</span><select value={stage} onChange={e=>setStage(e.target.value as IntensiveProgramStage)}>{STAGES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="ops-field"><span>Aktivitas saat ini <small>opsional</small></span><input maxLength={500} value={currentActivity} onChange={e=>setCurrentActivity(e.target.value)} placeholder="Contoh: Final pitch deck refinement"/></label><label className="ops-field"><span>Ringkasan progres <small>opsional</small></span><textarea rows={4} maxLength={3000} value={progress} onChange={e=>setProgress(e.target.value)}/></label><div className="intensive-config-actions"><button type="button" className="button button-primary" disabled={busy==='stage'||(stage===selected.program_stage&&currentActivity.trim()===(selected.current_activity??'')&&progress.trim()===(selected.progress_summary??''))} onClick={()=>void saveStage()}><Save aria-hidden="true" size={15}/>{busy==='stage'?'Menyimpan…':'Simpan progres'}</button><button type="button" className="button button-outline" disabled={busy==='stage'} onClick={resetProgressDraft}>Batal</button></div></div>:<div className="intensive-progress-read"><div className="intensive-read-value"><span>Tahap Program</span><strong>{intensiveStageLabels[selected.program_stage]}</strong></div><div className="intensive-read-value"><span>Aktivitas saat ini</span><strong>{selected.current_activity||'Belum dicatat'}</strong></div><div className="intensive-read-value"><span>Ringkasan progres</span><strong>{selected.progress_summary||'Belum ada ringkasan.'}</strong></div></div>}</section>
    <section className="intensive-config-card intensive-add-session-card"><div className="intensive-config-card__heading"><div><span>Session capacity</span><h3>Tambah Sesi</h3></div></div><p className="intensive-config-helper">Tambahkan sesi operasional sesuai kebutuhan program. Baseline bukan hard cap.</p>{addingSession?<div className="ops-form-stack"><label className="ops-field"><span>Durasi sesi baru (menit)</span><input type="number" min={15} max={240} value={duration} onChange={e=>setDuration(e.target.value)} placeholder=""/><small>15–240 menit</small></label><label className="ops-field"><span>Alasan / catatan <small>opsional</small></span><input value={sessionReason} onChange={e=>setSessionReason(e.target.value)} placeholder="Konteks operasional"/></label><div className="intensive-config-actions"><button type="button" className="button button-primary" disabled={!duration||busy==='add'} onClick={()=>void addSession()}><Plus aria-hidden="true" size={15}/>{busy==='add'?'Menambahkan…':'Tambah sesi'}</button><button type="button" className="button button-outline" disabled={busy==='add'} onClick={()=>{setDuration('');setSessionReason('');setAddingSession(false)}}>Batal</button></div></div>:<button type="button" className="button button-primary intensive-add-session-trigger" onClick={()=>{setDuration('');setSessionReason('');setAddingSession(true)}}><Plus aria-hidden="true" size={15}/>Tambah sesi</button>}</section>
   </div><section className="intensive-config-support"><div><p className="kicker">Included support</p><h3>Add-on terpasang</h3></div><div className="intensive-config-chips">{selected.add_ons.filter(item=>item.supportType!=='benefit').length?selected.add_ons.filter(item=>item.supportType!=='benefit').map(addon=><span className="intensive-addon-chip" key={addon.entitlementId??addon.code+addon.name}>{addon.name}</span>):<span className="muted">Belum ada add-on terpasang.</span>}</div>{selected.add_ons.some(item=>item.supportType==='benefit')?<><h4>Benefit custom</h4><div className="intensive-config-chips">{selected.add_ons.filter(item=>item.supportType==='benefit').map(addon=><span className="intensive-addon-chip" key={addon.code+addon.name}>{addon.name}</span>)}</div></>:null}{selected.unassigned_add_ons.length?<div className="intensive-unassigned-addons"><ShieldAlert aria-hidden="true"/><div><strong>Add-on belum terasosiasi</strong><p>Riwayat ambigu tidak ditebak otomatis. Tautkan hanya jika engagement ini memang benar.</p><div className="button-row">{selected.unassigned_add_ons.map(addon=><button type="button" className="button button-outline button-compact" disabled={!addon.entitlementId||busy==='addon:'+addon.entitlementId} onClick={()=>addon.entitlementId&&void attachAddOn(addon.entitlementId)} key={addon.entitlementId??addon.code}>Tautkan {addon.name}</button>)}</div></div></div>:null}</section></div>
  </div>:null}</dialog>
  <AdminScheduleDialog sessionId={scheduleId} mentoringKind="intensive" onClose={()=>setScheduleId(null)} onScheduled={async()=>{setScheduleId(null);await load()}}/>
  <dialog ref={dialogRef} className="ops-dialog intensive-session-detail-dialog" onCancel={e=>{e.preventDefault();closeSessionDetail()}} onClose={closeSessionDetail} aria-labelledby="intensive-admin-session-title">{session?<div className="ops-dialog__surface intensive-session-detail-dialog__surface"><header className="ops-dialog__header"><div><p className="kicker">Intensive Mentoring</p><h2 id="intensive-admin-session-title">Kelola sesi {session.sessionNumber}</h2><p>{selected?.program_name} · {selected?.mentee_name||selected?.mentee_email}</p></div><button type="button" className="ops-icon-button" onClick={closeSessionDetail} aria-label="Tutup detail sesi"><X/></button></header>
   <div className="session-reference-row"><div><span>Session ID</span><strong>{session.sessionId}</strong></div><CopyTextButton value={session.sessionId} label="Salin Session ID"/></div>
   <section className="intensive-session-section"><div className="intensive-session-section__heading"><h3>Topik dan scope</h3>{!editingSessionTopic?<button type="button" className="button button-outline button-compact" disabled={session.status==='completed'||session.status==='cancelled'} onClick={()=>setEditingSessionTopic(true)}><Pencil aria-hidden="true"/>Edit topik</button>:null}</div>{editingSessionTopic?<div className="ops-form-stack intensive-session-form-stack"><label className="ops-field"><span>Fokus</span><select value={topicFocus} onChange={e=>setTopicFocus(e.target.value)}><option value="">Pilih fokus</option>{focuses.map(focus=><option key={focus.id} value={focus.id}>{focus.name}</option>)}</select></label><label className="ops-field"><span>Topik final</span><textarea rows={4} value={resolvedTopic} onChange={e=>setResolvedTopic(e.target.value)} placeholder={session.menteeTopicRequest||'Tinjau permintaan mentee lalu tetapkan scope final.'}/></label><div className="intensive-session-action-row"><button type="button" className="button button-primary" disabled={!topicFocus||resolvedTopic.trim().length<2||busy==='topic'||(topicFocus===(session.focusId??'')&&resolvedTopic.trim()===(session.resolvedTopic??session.menteeTopicRequest??''))} onClick={()=>void resolveTopic()}><Save aria-hidden="true"/>{busy==='topic'?'Menyimpan…':'Simpan topik'}</button><button type="button" className="button button-outline" disabled={busy==='topic'} onClick={resetSessionTopicDraft}>Batal</button></div></div>:<div className="intensive-session-read-grid"><div className="intensive-session-read-field"><span>Fokus</span><strong>{session.focusName||'Belum ditetapkan'}</strong></div><div className="intensive-session-read-field intensive-session-read-field--wide"><span>Topik final</span><strong>{session.resolvedTopic||session.menteeTopicRequest||'Belum ditetapkan'}</strong></div><div className="intensive-session-read-field"><span>Status topik</span><strong>{topicStatusLabel(session.topicStatus)}</strong></div></div>}</section>
   <section className="intensive-session-section"><div className="intensive-session-section__heading"><h3>Mentor & jadwal</h3></div>{editingSessionMentor?<div className="ops-form-stack intensive-session-form-stack"><label className="ops-field"><span>Mentor sesi</span><select value={sessionMentor} onChange={e=>setSessionMentor(e.target.value)}><option value="">Pilih mentor</option>{mentors.map(mentor=><option key={mentor.id} value={mentor.id}>{mentor.name}</option>)}</select></label><label className="ops-field"><span>Alasan override <small>opsional</small></span><input value={sessionMentorReason} onChange={e=>setSessionMentorReason(e.target.value)} placeholder="Konteks perubahan mentor sesi"/></label><div className="intensive-session-action-row"><button type="button" className="button button-primary" disabled={!sessionMentor||sessionMentor===(session.mentorId??selected?.primary_mentor_id??'')||session.status==='completed'||session.status==='cancelled'||busy==='mentor'} onClick={()=>void assignSessionMentor()}><UserRound aria-hidden="true"/>{busy==='mentor'?'Menyimpan…':'Simpan mentor sesi'}</button><button type="button" className="button button-outline" disabled={busy==='mentor'} onClick={resetSessionMentorDraft}>Batal</button></div></div>:<><div className="intensive-session-read-grid"><div className="intensive-session-read-field"><span>Mentor sesi</span><strong>{session.mentorName||selected?.primary_mentor_name||'Belum ditetapkan'}</strong></div><div className="intensive-session-read-field intensive-session-read-field--wide"><span>Jadwal</span><strong>{scheduleLabel(session)}</strong></div></div><div className="intensive-session-action-row intensive-session-action-row--operations"><button type="button" className="button button-outline" disabled={session.status==='completed'||session.status==='cancelled'} onClick={()=>setEditingSessionMentor(true)}><Pencil aria-hidden="true"/>Edit mentor</button><button type="button" className="button button-primary" disabled={session.topicStatus!=='confirmed'||session.status==='completed'||session.status==='cancelled'} onClick={()=>{setScheduleId(session.sessionId);closeSessionDetail()}}><CalendarDays aria-hidden="true"/>{session.status==='scheduled'?'Ubah jadwal':'Jadwalkan'}</button><button type="button" className="button mentoring-session-cancel-trigger" disabled={session.status==='completed'||session.status==='cancelled'||busy==='cancel'} onClick={()=>void cancelSession()}>Batalkan sesi</button></div></>}</section>
   <AdminSessionOperations mentoringKind="intensive" showSessionReference={false} sessionId={session.sessionId} status={session.status} menteeName={selected?.mentee_name||selected?.mentee_email||'Mentee'} sessionNumber={session.sessionNumber} mentorName={session.mentorName} scheduledStartAt={session.scheduledStartAt} onChanged={async()=>{await load()}}/>
  </div>:null}</dialog>
 </div>
}
