'use client'

import { CalendarDays, CheckCircle2, Eye, RefreshCw, Search, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

import { createClient } from '@/lib/supabase/client'
import type { MentorTier, PrivateMentoringPackage } from '@/lib/supabase/database.types'
import { AdminScheduleDialog } from './admin-schedule-dialog'
import { SortableTableHeader, type SortDirection } from './sortable-table-header'
import { TablePagination } from './table-pagination'

type EnrollmentRow = { total_count:number; enrollment_id:string; mentee_id:string; mentee_email:string; mentee_username:string; mentee_name:string; package_id:string; package_name:string; mentor_tier_id:string; mentor_tier_name:string; purchased_sessions:number; awaiting_focus_sessions:number; awaiting_scheduling_sessions:number; scheduled_sessions:number; completed_sessions:number; configured_sessions:number; purchased_at:string }
type SessionRow = { session_id:string; session_number:number; status:string; focus_name:string|null; mentor_name:string|null; scheduled_start_at:string|null; scheduled_end_at:string|null; purchased_sessions:number; google_sync_status:string; google_sync_error:string|null }
type RpcClient = { rpc<T = unknown>(name:string,args?:Record<string,unknown>):Promise<{data:T|null;error:{message:string}|null}> }
type EnrollmentSortKey = 'user'|'email'|'package'|'purchased_at'|'progress'|'status'
const DATE = new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'})
const DATE_TIME = new Intl.DateTimeFormat('id-ID',{dateStyle:'full',timeStyle:'short'})

function enrollmentStatus(row:EnrollmentRow){if(row.completed_sessions===row.purchased_sessions)return'Selesai';if(row.awaiting_focus_sessions>0)return'Menunggu fokus';if(row.awaiting_scheduling_sessions>0)return'Perlu dijadwalkan';if(row.configured_sessions===row.purchased_sessions)return'Semua sesi sudah diatur';return'Berjalan'}
function sessionStatus(value:string){if(value==='awaiting_focus')return'Menunggu fokus';if(value==='awaiting_scheduling')return'Menunggu admin';if(value==='scheduled')return'Terjadwal';if(value==='completed')return'Selesai';if(value==='cancelled')return'Dibatalkan';return value.replaceAll('_',' ')}
function packageLabel(pkg:PrivateMentoringPackage,tiers:MentorTier[]){const tier=tiers.find(item=>item.id===pkg.mentor_tier_id);return`${tier?.name??'Private Mentoring'} · ${pkg.session_count} sesi`}

export function PrivateMentoringSessionManagement(){
  const supabase=useMemo(()=>createClient(),[]);const rpc=useMemo(()=>supabase as unknown as RpcClient,[supabase]);const dialogRef=useRef<HTMLDialogElement>(null);const cancelDialogRef=useRef<HTMLDialogElement>(null)
  const[query,setQuery]=useState('');const[packageId,setPackageId]=useState('');const[tierId,setTierId]=useState('');const[progress,setProgress]=useState('all');const[fromDate,setFromDate]=useState('');const[toDate,setToDate]=useState('');const[page,setPage]=useState(0);const[pageSize,setPageSize]=useState(10);const[total,setTotal]=useState(0);const[sortKey,setSortKey]=useState<EnrollmentSortKey|null>(null);const[sortDirection,setSortDirection]=useState<SortDirection>(null)
  const[rows,setRows]=useState<EnrollmentRow[]>([]);const[packages,setPackages]=useState<PrivateMentoringPackage[]>([]);const[tiers,setTiers]=useState<MentorTier[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[message,setMessage]=useState('');const[warning,setWarning]=useState('');const[selected,setSelected]=useState<EnrollmentRow|null>(null);const[sessions,setSessions]=useState<SessionRow[]>([]);const[scheduleId,setScheduleId]=useState<string|null>(null);const[cancelTarget,setCancelTarget]=useState<SessionRow|null>(null);const[busyId,setBusyId]=useState<string|null>(null)

  const loadCatalog=useCallback(async()=>{const[packagesResult,tiersResult]=await Promise.all([supabase.from('private_mentoring_packages').select('*').order('sort_order').order('id'),supabase.from('mentor_tiers').select('*').eq('is_active',true).order('sort_order').order('name')]);if(packagesResult.error||tiersResult.error){setError('Filter Private Mentoring belum dapat dimuat.');return}setPackages(packagesResult.data??[]);setTiers(tiersResult.data??[])},[supabase])
  const load=useCallback(async()=>{setLoading(true);setError('');const{data,error:loadError}=await rpc.rpc<EnrollmentRow[]>('list_admin_private_mentoring_enrollments_page',{p_query:query.trim(),p_package_id:packageId||null,p_tier_id:tierId||null,p_progress:progress,p_from:fromDate||null,p_to:toDate||null,p_limit:pageSize,p_offset:page*pageSize});if(loadError){setError('Daftar pesanan Private Mentoring belum dapat dimuat.');setLoading(false);return}const next=data??[];if(next.length===0&&page>0){setPage(value=>Math.max(0,value-1));setLoading(false);return}setRows(next);setTotal(Number(next[0]?.total_count??0));setLoading(false)},[fromDate,packageId,page,pageSize,progress,query,rpc,tierId,toDate])
  const loadSessions=useCallback(async(enrollmentId:string)=>{const{data,error:sessionError}=await rpc.rpc<SessionRow[]>('get_admin_private_mentoring_enrollment_sessions',{p_enrollment_id:enrollmentId});if(sessionError){setError('Detail sesi belum dapat dimuat.');setSessions([]);return}setSessions(data??[])},[rpc])
  useEffect(()=>{void loadCatalog()},[loadCatalog]);useEffect(()=>{const timer=setTimeout(()=>{void load()},220);return()=>clearTimeout(timer)},[load]);useEffect(()=>{const dialog=dialogRef.current;if(!dialog)return;if(selected&&!dialog.open)dialog.showModal();if(!selected&&dialog.open)dialog.close()},[selected]);useEffect(()=>{const dialog=cancelDialogRef.current;if(!dialog)return;if(cancelTarget&&!dialog.open)dialog.showModal();if(!cancelTarget&&dialog.open)dialog.close()},[cancelTarget])

  const visibleRows=useMemo(()=>{if(!sortKey||!sortDirection)return rows;const sign=sortDirection==='asc'?1:-1;return[...rows].sort((left,right)=>{if(sortKey==='purchased_at')return(new Date(left.purchased_at).getTime()-new Date(right.purchased_at).getTime())*sign;if(sortKey==='progress')return(left.configured_sessions/Math.max(1,left.purchased_sessions)-right.configured_sessions/Math.max(1,right.purchased_sessions))*sign;const leftValue=sortKey==='user'?left.mentee_name:sortKey==='email'?left.mentee_email:sortKey==='package'?left.package_name:enrollmentStatus(left);const rightValue=sortKey==='user'?right.mentee_name:sortKey==='email'?right.mentee_email:sortKey==='package'?right.package_name:enrollmentStatus(right);return leftValue.localeCompare(rightValue,'id-ID')*sign})},[rows,sortDirection,sortKey])
  function changeSort(key:string|null,direction:SortDirection){setSortKey(key as EnrollmentSortKey|null);setSortDirection(direction)}
  function resetFilters(){setQuery('');setPackageId('');setTierId('');setProgress('all');setFromDate('');setToDate('');setPage(0)}
  async function open(row:EnrollmentRow){setSelected(row);setMessage('');setWarning('');setError('');await loadSessions(row.enrollment_id)}
  async function refresh(){if(selected)await loadSessions(selected.enrollment_id);await load()}
  async function complete(sessionId:string){setBusyId(sessionId);setError('');setWarning('');const{error:completeError}=await rpc.rpc('admin_set_private_mentoring_session_status',{p_session_id:sessionId,p_status:'completed'});if(completeError)setError(completeError.message);else{setMessage('Sesi ditandai selesai.');await refresh()}setBusyId(null)}
  async function cancelSession(session:SessionRow){setBusyId(session.session_id);setError('');setMessage('');setWarning('');try{const response=await fetch(`/api/admin/private-mentoring/sessions/${session.session_id}/cancel`,{method:'POST'});const result=await response.json() as{error?:string;sync?:{status?:string}};if(!response.ok)throw new Error(result.error||'Sesi belum dapat dibatalkan.');setCancelTarget(null);if(result.sync?.status==='failed')setWarning('Sesi sudah dibatalkan di Strativate, tetapi Google Calendar belum berhasil disinkronkan. Coba ulangi sinkronisasi.');else setMessage('Sesi dibatalkan dan undangan Google Calendar sudah disinkronkan.');await refresh()}catch(cancelError){setError(cancelError instanceof Error?cancelError.message:'Sesi belum dapat dibatalkan.')}finally{setBusyId(null)}}
  async function retryCancellation(session:SessionRow){setBusyId(session.session_id);setError('');setMessage('');setWarning('');try{const response=await fetch(`/api/admin/private-mentoring/sessions/${session.session_id}/sync`,{method:'POST'});const result=await response.json() as{error?:string;status?:string};if(!response.ok)throw new Error(result.error||'Sinkronisasi pembatalan belum berhasil.');if(result.status==='failed')setWarning('Sesi tetap dibatalkan di Strativate, tetapi Google Calendar masih belum berhasil disinkronkan.');else setMessage('Pembatalan Google Calendar sudah tersinkron.');await refresh()}catch(syncError){setError(syncError instanceof Error?syncError.message:'Sinkronisasi pembatalan belum berhasil.')}finally{setBusyId(null)}}

  return <div className="ops-page mentoring-enrollment-page">
    <div className="role-page-title"><p className="kicker">Operasional · Private Mentoring</p><h2>Mentoring Sessions</h2><p>Admin memilih slot tersedia dari availability mentor. Input waktu manual tidak lagi menjadi sumber penjadwalan.</p></div>
    <div className="ops-filter-bar mentoring-enrollment-filters"><label className="ops-field ops-field--wide"><span>Cari user</span><div className="ops-input-with-icon"><Search size={15} aria-hidden="true"/><input type="search" value={query} onChange={event=>{setQuery(event.target.value);setPage(0)}} placeholder="Nama, username, email, atau paket"/></div></label><label className="ops-field"><span>Paket</span><select value={packageId} onChange={event=>{setPackageId(event.target.value);setPage(0)}}><option value="">Semua paket</option>{packages.map(pkg=><option value={pkg.id} key={pkg.id}>{packageLabel(pkg,tiers)}</option>)}</select></label><label className="ops-field"><span>Tier</span><select value={tierId} onChange={event=>{setTierId(event.target.value);setPage(0)}}><option value="">Semua tier</option>{tiers.map(tier=><option key={tier.id} value={tier.id}>{tier.name}</option>)}</select></label><label className="ops-field"><span>Progress</span><select value={progress} onChange={event=>{setProgress(event.target.value);setPage(0)}}><option value="all">Semua</option><option value="needs_focus">Menunggu fokus</option><option value="needs_scheduling">Perlu dijadwalkan</option><option value="configured">Semua sesi diatur</option><option value="in_progress">Berjalan</option><option value="completed">Selesai</option></select></label><label className="ops-field"><span>Dari tanggal beli</span><input type="date" value={fromDate} onChange={event=>{setFromDate(event.target.value);setPage(0)}}/></label><label className="ops-field"><span>Sampai</span><input type="date" value={toDate} onChange={event=>{setToDate(event.target.value);setPage(0)}}/></label><label className="ops-field"><span>Per halaman</span><select value={pageSize} onChange={event=>{setPageSize(Number(event.target.value));setPage(0)}}><option value={10}>10</option><option value={20}>20</option><option value={50}>50</option></select></label><button className="button button-outline" type="button" onClick={resetFilters}>Reset</button></div>
    {error&&!selected?<p className="form-error" role="alert">{error}</p>:null}
    <section className="role-card ops-table-section"><div className="ops-section-heading"><div><p className="kicker">Pesanan mentoring</p><h3>{total} paket</h3><p>Satu row mewakili satu enrollment/paket.</p></div></div><div className="ops-table-wrap"><table className="ops-table mentoring-enrollment-table"><thead><tr><SortableTableHeader label="User" sortKey="user" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Email" sortKey="email" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Paket" sortKey="package" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Tanggal beli" sortKey="purchased_at" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Progress" sortKey="progress" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><SortableTableHeader label="Status" sortKey="status" activeKey={sortKey} direction={sortDirection} onSortChange={changeSort}/><th>Aksi</th></tr></thead><tbody>{visibleRows.map(row=><tr key={row.enrollment_id}><td><strong>{row.mentee_name}</strong><small className="ops-table-secondary">@{row.mentee_username||'username-belum-diatur'}</small></td><td>{row.mentee_email}</td><td><strong>{row.package_name}</strong><small className="ops-table-secondary">{row.mentor_tier_name}</small></td><td>{DATE.format(new Date(row.purchased_at))}</td><td>{row.configured_sessions}/{row.purchased_sessions} diatur · {row.completed_sessions} selesai</td><td><span className="ops-status ops-status--info">{enrollmentStatus(row)}</span></td><td><button className="icon-button" type="button" onClick={()=>void open(row)} aria-label={`Lihat detail ${row.mentee_name}`}><Eye aria-hidden="true"/></button></td></tr>)}</tbody></table>{!loading&&visibleRows.length===0?<p className="calendar-empty">Tidak ada enrollment yang cocok.</p>:null}{loading?<p className="calendar-loading">Memuat…</p>:null}</div><TablePagination page={page} pageSize={pageSize} totalItems={total} onPageChange={setPage} disabled={loading} label="Pagination enrollment Private Mentoring"/></section>
    <dialog ref={dialogRef} className="calendar-dialog" onCancel={event=>{event.preventDefault();setSelected(null)}} onClose={()=>setSelected(null)}>{selected?<><div className="calendar-dialog__head"><div><p className="kicker">Kelola sesi</p><h3>{selected.mentee_name} · {selected.package_name}</h3><p>{selected.mentee_email} · {selected.mentor_tier_name}</p></div><button type="button" className="icon-button" onClick={()=>setSelected(null)} aria-label="Tutup detail"><X aria-hidden="true"/></button></div><div className="schedule-slot-list">{sessions.map(session=><article className="schedule-day" key={session.session_id}><span className="sr-only">Session Information · Mentor Assignment · Schedule · Status / Action</span><div className="mentoring-session-detail-row"><div><p className="kicker">Sesi {session.session_number}/{session.purchased_sessions}</p><h4>{session.focus_name||'Fokus belum dipilih'}</h4><p>{session.mentor_name||'Mentor belum ditetapkan'} · {session.scheduled_start_at?DATE_TIME.format(new Date(session.scheduled_start_at)):'Belum terjadwal'}</p>{session.status==='cancelled'&&session.google_sync_status==='failed'?<small className="form-error">Google sync: {session.google_sync_error||'Pembatalan belum tersinkron.'}</small>:null}</div><span className="ops-status ops-status--info">{sessionStatus(session.status)}</span></div><div className="button-row">{session.status==='awaiting_scheduling'||session.status==='scheduled'?<button className="button button-primary" type="button" onClick={()=>setScheduleId(session.session_id)}><CalendarDays aria-hidden="true"/>{session.status==='scheduled'?'Ubah jadwal':'Jadwalkan sesi'}</button>:null}{session.status==='scheduled'?<button className="button button-outline" type="button" disabled={busyId===session.session_id} onClick={()=>void complete(session.session_id)}><CheckCircle2 aria-hidden="true"/>Tandai selesai</button>:null}{session.status==='scheduled'?<button className="button button-ghost" type="button" disabled={busyId===session.session_id} onClick={()=>setCancelTarget(session)}><X aria-hidden="true"/>Batalkan sesi</button>:null}{session.status==='cancelled'&&session.google_sync_status==='failed'?<button className="button button-outline" type="button" disabled={busyId===session.session_id} onClick={()=>void retryCancellation(session)}><RefreshCw aria-hidden="true"/>Sinkronkan pembatalan</button>:null}</div></article>)}</div>{error?<p className="form-error" role="alert">{error}</p>:null}{warning?<p className="calendar-warning" role="status">{warning}</p>:null}{message?<p className="form-success" role="status">{message}</p>:null}</>:null}</dialog>
    <dialog ref={cancelDialogRef} className="calendar-dialog" onCancel={event=>{event.preventDefault();setCancelTarget(null)}} onClose={()=>setCancelTarget(null)}>{cancelTarget?<><div className="calendar-dialog__head"><div><p className="kicker">Konfirmasi pembatalan</p><h3>Batalkan sesi {cancelTarget.session_number}?</h3></div><button type="button" className="icon-button" onClick={()=>setCancelTarget(null)} aria-label="Tutup konfirmasi"><X aria-hidden="true"/></button></div><p>Sesi Strativate akan dibatalkan dan undangan Google Calendar terkait akan dibatalkan. Mentor dan mentee mungkin menerima update pembatalan dari Google.</p><div className="button-row"><button className="button button-outline" type="button" onClick={()=>setCancelTarget(null)}>Kembali</button><button className="button button-primary" type="button" disabled={busyId===cancelTarget.session_id} onClick={()=>void cancelSession(cancelTarget)}>Ya, batalkan sesi</button></div></>:null}</dialog>
    <AdminScheduleDialog sessionId={scheduleId} onClose={()=>setScheduleId(null)} onScheduled={()=>{setScheduleId(null);void refresh()}}/>
  </div>
}
