-- Replace Zoom API provisioning with an Admin-managed pool of reusable Zoom rooms.
-- Existing provider columns remain as legacy audit data, but active runtime links resolve
-- from manual_meeting_url or the assigned managed room.

create table public.mentoring_zoom_rooms (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(btrim(name)) between 2 and 120),
  meeting_url text not null check (meeting_url ~* '^https://[^[:space:]]+$'),
  is_active boolean not null default true,
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index mentoring_zoom_rooms_normalized_url_key
  on public.mentoring_zoom_rooms (lower(regexp_replace(btrim(meeting_url), '/+$', '')));
create index mentoring_zoom_rooms_active_order_idx
  on public.mentoring_zoom_rooms (is_active desc, sort_order, name, id);

create trigger mentoring_zoom_rooms_touch_updated_at
before update on public.mentoring_zoom_rooms
for each row execute function public.touch_updated_at();

create table public.mentoring_zoom_room_allocations (
  id uuid primary key default gen_random_uuid(),
  zoom_room_id uuid not null references public.mentoring_zoom_rooms(id) on delete restrict,
  private_session_id uuid references public.private_mentoring_sessions(id) on delete restrict,
  intensive_session_id uuid references public.intensive_mentoring_sessions(id) on delete restrict,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  released_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (num_nonnulls(private_session_id, intensive_session_id) = 1),
  check (ends_at > starts_at)
);

create unique index mentoring_zoom_room_allocations_private_session_key
  on public.mentoring_zoom_room_allocations(private_session_id)
  where private_session_id is not null;
create unique index mentoring_zoom_room_allocations_intensive_session_key
  on public.mentoring_zoom_room_allocations(intensive_session_id)
  where intensive_session_id is not null;
create index mentoring_zoom_room_allocations_room_time_idx
  on public.mentoring_zoom_room_allocations(zoom_room_id, starts_at, ends_at)
  where released_at is null;

alter table public.mentoring_zoom_room_allocations
  add constraint mentoring_zoom_room_allocations_no_overlap
  exclude using gist (
    zoom_room_id extensions.gist_uuid_ops with =,
    tstzrange(starts_at, ends_at, '[)') with &&
  ) where (released_at is null);

create trigger mentoring_zoom_room_allocations_touch_updated_at
before update on public.mentoring_zoom_room_allocations
for each row execute function public.touch_updated_at();

alter table public.mentoring_zoom_rooms enable row level security;
alter table public.mentoring_zoom_room_allocations enable row level security;

create policy mentoring_zoom_rooms_admin_read
on public.mentoring_zoom_rooms for select to authenticated
using (public.is_admin());

create policy mentoring_zoom_room_allocations_admin_read
on public.mentoring_zoom_room_allocations for select to authenticated
using (public.is_admin());

revoke all on public.mentoring_zoom_rooms, public.mentoring_zoom_room_allocations
from public, anon, authenticated;
grant select on public.mentoring_zoom_rooms, public.mentoring_zoom_room_allocations
to authenticated;
grant all on public.mentoring_zoom_rooms, public.mentoring_zoom_room_allocations
to service_role;

-- Preserve every working upcoming URL generated by the retired provider integration.
update public.private_mentoring_session_calendar_integrations ci
set manual_meeting_url = coalesce(ci.manual_meeting_url, ci.provider_meeting_url)
from public.private_mentoring_sessions s
where s.id = ci.session_id
  and s.status = 'scheduled'
  and ci.provider_meeting_url is not null;

update public.intensive_mentoring_session_calendar_integrations ci
set manual_meeting_url = coalesce(ci.manual_meeting_url, ci.provider_meeting_url)
from public.intensive_mentoring_sessions s
where s.id = ci.session_id
  and s.status = 'scheduled'
  and ci.provider_meeting_url is not null;

create or replace function public.admin_list_mentoring_zoom_rooms()
returns table (
  id uuid,
  name text,
  meeting_url text,
  is_active boolean,
  sort_order integer,
  current_usage_count bigint,
  upcoming_usage_count bigint,
  next_usage_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  return query
  select r.id, r.name, r.meeting_url, r.is_active, r.sort_order,
    count(a.id) filter (where a.released_at is null and a.starts_at <= now() and a.ends_at > now()),
    count(a.id) filter (where a.released_at is null and a.ends_at > now()),
    min(a.starts_at) filter (where a.released_at is null and a.ends_at > now()),
    r.created_at, r.updated_at
  from public.mentoring_zoom_rooms r
  left join public.mentoring_zoom_room_allocations a on a.zoom_room_id = r.id
  group by r.id
  order by r.sort_order, r.name, r.id;
end;
$$;

create or replace function public.admin_upsert_mentoring_zoom_room(
  p_id uuid,
  p_name text,
  p_meeting_url text,
  p_is_active boolean default true,
  p_sort_order integer default 0
)
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_name text := nullif(btrim(coalesce(p_name, '')), '');
  v_url text := regexp_replace(btrim(coalesce(p_meeting_url, '')), '/+$', '');
  v_previous public.mentoring_zoom_rooms;
  v_room public.mentoring_zoom_rooms;
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  if v_name is null or char_length(v_name) not between 2 and 120 then
    raise exception 'Nama Zoom room wajib 2-120 karakter' using errcode = '22023';
  end if;
  if v_url !~* '^https://[^[:space:]]+$' then
    raise exception 'Zoom URL harus menggunakan HTTPS' using errcode = '22023';
  end if;
  if coalesce(p_sort_order, 0) < 0 then
    raise exception 'Urutan Zoom room tidak valid' using errcode = '22023';
  end if;

  if p_id is null then
    insert into public.mentoring_zoom_rooms(name, meeting_url, is_active, sort_order)
    values(v_name, v_url, coalesce(p_is_active, true), coalesce(p_sort_order, 0))
    returning * into v_room;
  else
    select * into v_previous from public.mentoring_zoom_rooms where id = p_id for update;
    if not found then raise exception 'Zoom room tidak ditemukan' using errcode = '22023'; end if;
    if v_previous.is_active and not coalesce(p_is_active, true) and exists (
      select 1 from public.mentoring_zoom_room_allocations a
      where a.zoom_room_id = p_id and a.released_at is null and a.ends_at > now()
    ) then
      raise exception 'Zoom room masih digunakan sesi aktif atau mendatang. Ganti room sesi terkait sebelum menonaktifkan.' using errcode = '23503';
    end if;
    update public.mentoring_zoom_rooms
    set name = v_name,
        meeting_url = v_url,
        is_active = coalesce(p_is_active, true),
        sort_order = coalesce(p_sort_order, 0)
    where id = p_id
    returning * into v_room;

    if v_previous.meeting_url is distinct from v_room.meeting_url then
      update public.private_mentoring_session_calendar_integrations ci
      set sync_status = 'pending', sync_error = null
      from public.mentoring_zoom_room_allocations a
      join public.private_mentoring_sessions s on s.id = a.private_session_id
      where a.zoom_room_id = v_room.id
        and a.released_at is null
        and a.ends_at > now()
        and s.status = 'scheduled'
        and ci.session_id = s.id;

      update public.intensive_mentoring_session_calendar_integrations ci
      set sync_status = 'pending', sync_error = null
      from public.mentoring_zoom_room_allocations a
      join public.intensive_mentoring_sessions s on s.id = a.intensive_session_id
      where a.zoom_room_id = v_room.id
        and a.released_at is null
        and a.ends_at > now()
        and s.status = 'scheduled'
        and ci.session_id = s.id;
    end if;
  end if;

  return jsonb_build_object(
    'room', to_jsonb(v_room),
    'urlChanged', p_id is not null and v_previous.meeting_url is distinct from v_room.meeting_url
  );
exception
  when unique_violation then
    raise exception 'Zoom URL sudah terdaftar' using errcode = '23505';
end;
$$;

create or replace function public.admin_delete_mentoring_zoom_room(p_id uuid)
returns uuid
language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  if exists (select 1 from public.mentoring_zoom_room_allocations where zoom_room_id = p_id) then
    raise exception 'Zoom room memiliki riwayat sesi dan tidak dapat dihapus. Nonaktifkan room ini.' using errcode = '23503';
  end if;
  delete from public.mentoring_zoom_rooms where id = p_id;
  if not found then raise exception 'Zoom room tidak ditemukan' using errcode = '22023'; end if;
  return p_id;
end;
$$;

create or replace function public.admin_get_mentoring_zoom_room_pool(
  p_from timestamptz,
  p_to timestamptz,
  p_private_session_id uuid default null,
  p_intensive_session_id uuid default null
)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_result jsonb;
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  if p_from is null or p_to is null or p_to <= p_from then
    raise exception 'Rentang ketersediaan Zoom room tidak valid' using errcode = '22023';
  end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', r.id,
    'name', r.name,
    'meetingUrl', r.meeting_url,
    'sortOrder', r.sort_order,
    'busy', coalesce((
      select jsonb_agg(jsonb_build_object('start', a.starts_at, 'end', a.ends_at) order by a.starts_at)
      from public.mentoring_zoom_room_allocations a
      where a.zoom_room_id = r.id
        and a.released_at is null
        and not (
          a.private_session_id is not distinct from p_private_session_id
          and a.intensive_session_id is not distinct from p_intensive_session_id
        )
        and tstzrange(a.starts_at, a.ends_at, '[)') && tstzrange(p_from, p_to, '[)')
    ), '[]'::jsonb)
  ) order by r.sort_order, r.name, r.id), '[]'::jsonb)
  into v_result
  from public.mentoring_zoom_rooms r
  where r.is_active;
  return v_result;
end;
$$;

create or replace function public.reserve_mentoring_zoom_room(
  p_private_session_id uuid,
  p_intensive_session_id uuid,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_requested_room_id uuid default null
)
returns uuid
language plpgsql security definer set search_path = '' as $$
declare
  v_room_id uuid;
  v_existing_room_id uuid;
begin
  if num_nonnulls(p_private_session_id, p_intensive_session_id) <> 1 then
    raise exception 'Exactly one mentoring session is required' using errcode = '22023';
  end if;
  if p_starts_at is null or p_ends_at is null or p_ends_at <= p_starts_at then
    raise exception 'Jadwal sesi tidak valid' using errcode = '22023';
  end if;

  select a.zoom_room_id into v_existing_room_id
  from public.mentoring_zoom_room_allocations a
  where a.private_session_id is not distinct from p_private_session_id
    and a.intensive_session_id is not distinct from p_intensive_session_id;

  if p_requested_room_id is not null then
    select r.id into v_room_id
    from public.mentoring_zoom_rooms r
    where r.id = p_requested_room_id and r.is_active
    for update;
    if v_room_id is null then
      raise exception 'Zoom room tidak aktif atau tidak ditemukan' using errcode = '22023';
    end if;
    if exists (
      select 1 from public.mentoring_zoom_room_allocations a
      where a.zoom_room_id = v_room_id
        and a.released_at is null
        and not (
          a.private_session_id is not distinct from p_private_session_id
          and a.intensive_session_id is not distinct from p_intensive_session_id
        )
        and tstzrange(a.starts_at, a.ends_at, '[)') && tstzrange(p_starts_at, p_ends_at, '[)')
    ) then
      raise exception 'Zoom room baru saja dipakai sesi lain. Muat ulang dan pilih room lain.' using errcode = '23P01';
    end if;
  else
    if v_existing_room_id is not null then
      select r.id into v_room_id
      from public.mentoring_zoom_rooms r
      where r.id = v_existing_room_id and r.is_active
        and not exists (
          select 1 from public.mentoring_zoom_room_allocations a
          where a.zoom_room_id = r.id
            and a.released_at is null
            and not (
              a.private_session_id is not distinct from p_private_session_id
              and a.intensive_session_id is not distinct from p_intensive_session_id
            )
            and tstzrange(a.starts_at, a.ends_at, '[)') && tstzrange(p_starts_at, p_ends_at, '[)')
        )
      for update;
    end if;

    if v_room_id is null then
      select r.id into v_room_id
      from public.mentoring_zoom_rooms r
      where r.is_active
        and not exists (
          select 1 from public.mentoring_zoom_room_allocations a
          where a.zoom_room_id = r.id
            and a.released_at is null
            and not (
              a.private_session_id is not distinct from p_private_session_id
              and a.intensive_session_id is not distinct from p_intensive_session_id
            )
            and tstzrange(a.starts_at, a.ends_at, '[)') && tstzrange(p_starts_at, p_ends_at, '[)')
        )
      order by r.sort_order, r.name, r.id
      for update skip locked
      limit 1;
    end if;

    if v_room_id is null then
      if not exists (select 1 from public.mentoring_zoom_rooms where is_active) then
        raise exception 'Belum ada Zoom room aktif. Tambahkan link Zoom dari menu Admin → Zoom.' using errcode = 'P0001';
      end if;
      raise exception 'Semua Zoom room sedang terpakai pada jam ini. Muat ulang pilihan jadwal.' using errcode = '23P01';
    end if;
  end if;

  begin
    if p_private_session_id is not null then
      insert into public.mentoring_zoom_room_allocations(
        zoom_room_id, private_session_id, starts_at, ends_at, released_at
      ) values (
        v_room_id, p_private_session_id, p_starts_at, p_ends_at, null
      )
      on conflict (private_session_id) where private_session_id is not null
      do update set zoom_room_id = excluded.zoom_room_id,
                    starts_at = excluded.starts_at,
                    ends_at = excluded.ends_at,
                    released_at = null;
    else
      insert into public.mentoring_zoom_room_allocations(
        zoom_room_id, intensive_session_id, starts_at, ends_at, released_at
      ) values (
        v_room_id, p_intensive_session_id, p_starts_at, p_ends_at, null
      )
      on conflict (intensive_session_id) where intensive_session_id is not null
      do update set zoom_room_id = excluded.zoom_room_id,
                    starts_at = excluded.starts_at,
                    ends_at = excluded.ends_at,
                    released_at = null;
    end if;
  exception when exclusion_violation then
    raise exception 'Zoom room baru saja dipakai sesi lain. Muat ulang dan pilih room lain.' using errcode = '23P01';
  end;
  return v_room_id;
end;
$$;

create or replace function public.admin_get_private_mentoring_slot_context(p_session_id uuid)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_result jsonb;
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  select jsonb_build_object(
    'sessionId', s.id, 'status', s.status, 'topicStatus', s.topic_status,
    'focusName', coalesce(s.resolved_topic, f.name), 'resolvedTopic', s.resolved_topic,
    'requiredTierId', pkg.mentor_tier_id, 'durationMinutes', pkg.duration_minutes,
    'menteeId', e.mentee_id, 'purchasedSessions', e.purchased_sessions,
    'sessionNumber', s.session_number, 'primaryMentorRequired', e.purchased_sessions >= 5,
    'primaryMentorId', e.primary_mentor_id,
    'mentors', coalesce((
      select jsonb_agg(jsonb_build_object(
        'mentorId', mp.user_id,
        'mentorName', coalesce(nullif(btrim(concat_ws(' ', pp.first_name, pp.last_name)), ''), au.email),
        'tierId', mp.tier_id, 'active', mp.is_active, 'timezone', mp.timezone,
        'availability', coalesce((select jsonb_agg(jsonb_build_object(
          'start', (((a.week_start_date + (a.day_of_week - 1))::date + a.start_time) at time zone mp.timezone),
          'end', (((a.week_start_date + (a.day_of_week - 1))::date + a.end_time) at time zone mp.timezone)
        ) order by a.week_start_date, a.day_of_week, a.start_time)
          from public.mentor_availability_rules a
          where a.mentor_id = mp.user_id and a.week_start_date in (
            date_trunc('week', current_timestamp at time zone mp.timezone)::date,
            date_trunc('week', current_timestamp at time zone mp.timezone)::date + 7
          )), '[]'::jsonb),
        'strativate_busy', coalesce((
          select jsonb_agg(jsonb_build_object('start', busy.starts_at, 'end', busy.ends_at) order by busy.starts_at)
          from (
            select other.scheduled_start_at as starts_at, other.scheduled_end_at as ends_at
            from public.private_mentoring_sessions other
            where other.mentor_id = mp.user_id and other.id <> s.id
              and other.status in ('scheduled', 'completed') and other.scheduled_start_at is not null
            union all
            select other.scheduled_start_at, other.scheduled_end_at
            from public.intensive_mentoring_sessions other
            where other.mentor_id = mp.user_id and other.status in ('scheduled', 'completed')
              and other.scheduled_start_at is not null
          ) busy
        ), '[]'::jsonb)
      ) order by coalesce(pp.first_name, ''), coalesce(pp.last_name, ''), mp.user_id)
      from public.mentor_profiles mp
      join public.profiles pp on pp.id = mp.user_id and pp.role = 'mentor'::public.app_role
      join auth.users au on au.id = mp.user_id
      where mp.tier_id = pkg.mentor_tier_id and mp.is_active
        and (e.purchased_sessions < 5 or mp.user_id = e.primary_mentor_id)
    ), '[]'::jsonb)
  ) into v_result
  from public.private_mentoring_sessions s
  join public.private_mentoring_enrollments e on e.id = s.enrollment_id
  join public.private_mentoring_packages pkg on pkg.id = e.package_id
  left join public.private_mentoring_session_focuses f on f.id = s.session_focus_id
  where s.id = p_session_id;
  if v_result is null then raise exception 'Private Mentoring session not found' using errcode = '22023'; end if;
  return v_result;
end;
$$;

drop function if exists public.admin_schedule_private_mentoring_session(uuid, uuid, timestamptz);
create function public.admin_schedule_private_mentoring_session(
  p_session_id uuid,
  p_mentor_id uuid,
  p_scheduled_start_at timestamptz,
  p_zoom_room_id uuid default null
)
returns public.private_mentoring_sessions
language plpgsql security definer set search_path = '' as $$
declare
  v_session public.private_mentoring_sessions;
  v_required_tier uuid;
  v_duration integer;
  v_purchased integer;
  v_primary uuid;
  v_mentor_tier uuid;
  v_mentor_active boolean;
  v_timezone text;
  v_end timestamptz;
  v_local_start timestamp;
  v_local_end timestamp;
  v_local_date date;
  v_week_start date;
  v_day smallint;
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  if p_scheduled_start_at is null or p_scheduled_start_at <= now() then
    raise exception 'Schedule must be in the future' using errcode = '22023';
  end if;
  select * into v_session from public.private_mentoring_sessions where id = p_session_id for update;
  if not found then raise exception 'Private Mentoring session not found' using errcode = '22023'; end if;

  select pkg.mentor_tier_id, pkg.duration_minutes, e.purchased_sessions, e.primary_mentor_id
  into v_required_tier, v_duration, v_purchased, v_primary
  from public.private_mentoring_enrollments e
  join public.private_mentoring_packages pkg on pkg.id = e.package_id
  where e.id = v_session.enrollment_id;

  if v_session.topic_status <> 'confirmed' or v_session.session_focus_id is null or v_session.resolved_topic is null then
    raise exception 'Session topic must be confirmed before scheduling' using errcode = '22023';
  end if;
  if v_session.status not in ('awaiting_scheduling', 'scheduled') then
    raise exception 'Session is not schedulable' using errcode = '22023';
  end if;
  if v_purchased >= 5 and v_primary is null then
    raise exception 'Set the enrollment primary mentor before scheduling' using errcode = '22023';
  end if;
  if v_purchased >= 5 and p_mentor_id is distinct from v_primary then
    raise exception 'This package must use the enrollment primary mentor' using errcode = '22023';
  end if;

  select mp.tier_id, mp.is_active, mp.timezone
  into v_mentor_tier, v_mentor_active, v_timezone
  from public.mentor_profiles mp
  join public.profiles p on p.id = mp.user_id and p.role = 'mentor'::public.app_role
  where mp.user_id = p_mentor_id;
  if not found or not v_mentor_active then raise exception 'Active mentor required' using errcode = '22023'; end if;
  if v_mentor_tier is distinct from v_required_tier then
    raise exception 'Mentor tier does not match purchased package' using errcode = '22023';
  end if;

  v_end := p_scheduled_start_at + make_interval(mins => v_duration);
  v_local_start := p_scheduled_start_at at time zone v_timezone;
  v_local_end := v_end at time zone v_timezone;
  v_local_date := v_local_start::date;
  v_week_start := date_trunc('week', v_local_start)::date;
  v_day := extract(isodow from v_local_start)::smallint;
  if v_local_end::date <> v_local_date or not exists (
    select 1 from public.mentor_availability_rules a
    where a.mentor_id = p_mentor_id and a.week_start_date = v_week_start and a.day_of_week = v_day
      and a.start_time <= v_local_start::time and a.end_time >= v_local_end::time
  ) then
    raise exception 'Selected slot is outside declared mentor availability' using errcode = '22023';
  end if;

  if exists (
    select 1 from public.private_mentoring_sessions other
    where other.id <> p_session_id and other.mentor_id = p_mentor_id and other.status in ('scheduled', 'completed')
      and tstzrange(other.scheduled_start_at, other.scheduled_end_at, '[)') && tstzrange(p_scheduled_start_at, v_end, '[)')
  ) or exists (
    select 1 from public.intensive_mentoring_sessions other
    where other.mentor_id = p_mentor_id and other.status in ('scheduled', 'completed')
      and tstzrange(other.scheduled_start_at, other.scheduled_end_at, '[)') && tstzrange(p_scheduled_start_at, v_end, '[)')
  ) then
    raise exception 'Selected slot conflicts with another Strativate mentor session' using errcode = '23P01';
  end if;

  perform public.reserve_mentoring_zoom_room(p_session_id, null, p_scheduled_start_at, v_end, p_zoom_room_id);

  begin
    update public.private_mentoring_sessions
    set mentor_id = p_mentor_id,
        scheduled_start_at = p_scheduled_start_at,
        scheduled_end_at = v_end,
        status = 'scheduled'
    where id = p_session_id
    returning * into v_session;
  exception when exclusion_violation then
    raise exception 'Selected slot was just booked by another session' using errcode = '23P01';
  end;

  insert into public.private_mentoring_session_calendar_integrations(session_id, organizer_user_id, sync_status, sync_error)
  values(p_session_id, auth.uid(), 'pending', null)
  on conflict(session_id) do update set
    sync_status = 'pending',
    sync_error = null,
    organizer_user_id = coalesce(public.private_mentoring_session_calendar_integrations.organizer_user_id, excluded.organizer_user_id);
  return v_session;
end;
$$;

create or replace function public.admin_cancel_private_mentoring_session(p_session_id uuid)
returns public.private_mentoring_sessions
language plpgsql security definer set search_path = '' as $$
declare v_session public.private_mentoring_sessions;
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  select * into v_session from public.private_mentoring_sessions where id = p_session_id for update;
  if not found then raise exception 'Private Mentoring session not found' using errcode = '22023'; end if;
  if v_session.status = 'cancelled' then return v_session; end if;
  if v_session.status = 'completed' then raise exception 'Completed sessions cannot be cancelled' using errcode = '22023'; end if;
  if v_session.status <> 'scheduled' then raise exception 'Only a scheduled session can be cancelled' using errcode = '22023'; end if;

  update public.private_mentoring_sessions set status = 'cancelled'
  where id = p_session_id returning * into v_session;
  update public.mentoring_zoom_room_allocations set released_at = coalesce(released_at, now())
  where private_session_id = p_session_id;
  insert into public.private_mentoring_session_calendar_integrations(session_id, organizer_user_id, sync_status, sync_error)
  values(p_session_id, auth.uid(), 'pending', null)
  on conflict(session_id) do update set
    sync_status = 'pending', sync_error = null,
    organizer_user_id = coalesce(public.private_mentoring_session_calendar_integrations.organizer_user_id, excluded.organizer_user_id);
  return v_session;
end;
$$;

create or replace function public.admin_set_private_mentoring_session_status(p_session_id uuid, p_status text)
returns public.private_mentoring_sessions
language plpgsql security definer set search_path = '' as $$
declare v_session public.private_mentoring_sessions; v_from text;
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  if p_status not in ('completed', 'scheduled') then raise exception 'Unsupported status transition' using errcode = '22023'; end if;
  select * into v_session from public.private_mentoring_sessions where id = p_session_id for update;
  if not found then raise exception 'Private Mentoring session not found' using errcode = '22023'; end if;
  if v_session.status = p_status then return v_session; end if;
  if not ((v_session.status = 'scheduled' and p_status = 'completed') or (v_session.status = 'completed' and p_status = 'scheduled')) then
    raise exception 'Only scheduled -> completed or completed -> scheduled is allowed' using errcode = '22023';
  end if;
  if p_status = 'completed' and v_session.topic_status <> 'confirmed' then
    raise exception 'Resolve the session topic before completion' using errcode = '22023';
  end if;
  if p_status = 'scheduled' then
    perform public.reserve_mentoring_zoom_room(p_session_id, null, v_session.scheduled_start_at, v_session.scheduled_end_at, null);
  end if;
  v_from := v_session.status::text;
  update public.private_mentoring_sessions set status = p_status where id = p_session_id returning * into v_session;
  if p_status = 'completed' then
    update public.mentoring_zoom_room_allocations set released_at = coalesce(released_at, now()) where private_session_id = p_session_id;
  end if;
  insert into public.private_mentoring_session_status_events(session_id, from_status, to_status, actor_id)
  values(p_session_id, v_from, p_status, auth.uid());
  if p_status = 'scheduled' then
    update public.private_mentoring_enrollments set status = 'active' where id = v_session.enrollment_id;
  elsif not exists (
    select 1 from public.private_mentoring_sessions s
    where s.enrollment_id = v_session.enrollment_id and s.status not in ('completed', 'cancelled')
  ) then
    update public.private_mentoring_enrollments set status = 'completed' where id = v_session.enrollment_id;
  else
    update public.private_mentoring_enrollments set status = 'active' where id = v_session.enrollment_id;
  end if;
  return v_session;
end;
$$;

drop function if exists public.admin_schedule_intensive_mentoring_session(uuid, uuid, timestamptz);
create function public.admin_schedule_intensive_mentoring_session(
  p_session_id uuid,
  p_mentor_id uuid,
  p_scheduled_start_at timestamptz,
  p_zoom_room_id uuid default null
)
returns public.intensive_mentoring_sessions
language plpgsql security definer set search_path = '' as $$
declare
  v_session public.intensive_mentoring_sessions;
  v_eng public.intensive_mentoring_engagements;
  v_timezone text;
  v_end timestamptz;
  v_local_start timestamp;
  v_local_end timestamp;
  v_week_start date;
  v_day smallint;
  v_previous_status text;
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  if p_scheduled_start_at is null or p_scheduled_start_at <= now() then
    raise exception 'Future schedule required' using errcode = '22023';
  end if;
  select * into v_session from public.intensive_mentoring_sessions where id = p_session_id for update;
  if not found or v_session.status not in ('awaiting_scheduling', 'scheduled') or v_session.session_focus_id is null or v_session.resolved_topic is null then
    raise exception 'Resolved schedulable Intensive session required' using errcode = '22023';
  end if;
  select * into v_eng from public.intensive_mentoring_engagements where id = v_session.engagement_id;
  v_previous_status := v_session.status;
  select mp.timezone into v_timezone
  from public.mentor_profiles mp join public.profiles p on p.id = mp.user_id
  where mp.user_id = p_mentor_id and mp.is_active and p.role = 'mentor'::public.app_role;
  if not found then raise exception 'Active mentor required' using errcode = '22023'; end if;

  v_end := p_scheduled_start_at + make_interval(mins => v_session.duration_minutes);
  v_local_start := p_scheduled_start_at at time zone v_timezone;
  v_local_end := v_end at time zone v_timezone;
  v_week_start := date_trunc('week', v_local_start)::date;
  v_day := extract(isodow from v_local_start)::smallint;
  if v_local_end::date <> v_local_start::date or not exists (
    select 1 from public.mentor_availability_rules a
    where a.mentor_id = p_mentor_id and a.week_start_date = v_week_start and a.day_of_week = v_day
      and a.start_time <= v_local_start::time and a.end_time >= v_local_end::time
  ) then raise exception 'Selected slot is outside declared mentor availability' using errcode = '22023'; end if;

  if exists (
    select 1 from public.private_mentoring_sessions s
    where s.mentor_id = p_mentor_id and s.status in ('scheduled', 'completed')
      and tstzrange(s.scheduled_start_at, s.scheduled_end_at, '[)') && tstzrange(p_scheduled_start_at, v_end, '[)')
  ) or exists (
    select 1 from public.intensive_mentoring_sessions s
    where s.id <> p_session_id and s.mentor_id = p_mentor_id and s.status in ('scheduled', 'completed')
      and tstzrange(s.scheduled_start_at, s.scheduled_end_at, '[)') && tstzrange(p_scheduled_start_at, v_end, '[)')
  ) then raise exception 'Selected slot conflicts with another Strativate mentor session' using errcode = '23P01'; end if;

  if exists (
    select 1 from public.private_mentoring_sessions s
    join public.private_mentoring_enrollments e on e.id = s.enrollment_id
    where e.mentee_id = v_eng.mentee_id and s.status in ('scheduled', 'completed')
      and tstzrange(s.scheduled_start_at, s.scheduled_end_at, '[)') && tstzrange(p_scheduled_start_at, v_end, '[)')
  ) or exists (
    select 1 from public.intensive_mentoring_sessions s
    join public.intensive_mentoring_engagements e on e.id = s.engagement_id
    where s.id <> p_session_id and e.mentee_id = v_eng.mentee_id and s.status in ('scheduled', 'completed')
      and tstzrange(s.scheduled_start_at, s.scheduled_end_at, '[)') && tstzrange(p_scheduled_start_at, v_end, '[)')
  ) then raise exception 'Selected slot conflicts with another mentee session' using errcode = '23P01'; end if;

  perform public.reserve_mentoring_zoom_room(null, p_session_id, p_scheduled_start_at, v_end, p_zoom_room_id);
  update public.intensive_mentoring_sessions
  set mentor_id = p_mentor_id, scheduled_start_at = p_scheduled_start_at, scheduled_end_at = v_end, status = 'scheduled'
  where id = p_session_id returning * into v_session;
  insert into public.intensive_mentoring_session_calendar_integrations(session_id, organizer_user_id, sync_status, sync_error)
  values(p_session_id, auth.uid(), 'pending', null)
  on conflict(session_id) do update set
    organizer_user_id = coalesce(public.intensive_mentoring_session_calendar_integrations.organizer_user_id, excluded.organizer_user_id),
    sync_status = 'pending', sync_error = null;
  insert into public.intensive_mentoring_session_events(session_id, event_type, actor_user_id, from_status, to_status, metadata)
  values(p_session_id, case when v_previous_status = 'scheduled' then 'rescheduled' else 'scheduled' end, auth.uid(), v_previous_status, 'scheduled', jsonb_build_object('mentorId', p_mentor_id, 'start', p_scheduled_start_at, 'end', v_end));
  perform public.emit_notification(v_eng.mentee_id, 'mentee'::public.app_role, 'session_scheduled', 'Sesi Intensive Mentoring dijadwalkan', 'Sesi Intensive Mentoring kamu telah dijadwalkan.', 'intensive_mentoring_session', p_session_id::text, 'intensive:schedule:mentee:' || p_session_id::text || ':' || extract(epoch from p_scheduled_start_at)::bigint::text);
  perform public.emit_notification(p_mentor_id, 'mentor'::public.app_role, 'session_scheduled', 'Sesi Intensive Mentoring dijadwalkan', 'Sesi Intensive Mentoring baru telah dijadwalkan untuk kamu.', 'intensive_mentoring_session', p_session_id::text, 'intensive:schedule:mentor:' || p_session_id::text || ':' || extract(epoch from p_scheduled_start_at)::bigint::text);
  return v_session;
end;
$$;

create or replace function public.admin_cancel_intensive_mentoring_session(p_session_id uuid)
returns void language plpgsql security definer set search_path = '' as $$
declare v_session public.intensive_mentoring_sessions; v_eng public.intensive_mentoring_engagements;
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  select * into v_session from public.intensive_mentoring_sessions where id = p_session_id for update;
  if not found then raise exception 'Intensive session not found' using errcode = '22023'; end if;
  if v_session.status = 'cancelled' then return; end if;
  if v_session.status = 'completed' then raise exception 'Completed session cannot be cancelled' using errcode = '22023'; end if;
  select * into v_eng from public.intensive_mentoring_engagements where id = v_session.engagement_id;
  update public.intensive_mentoring_sessions set status = 'cancelled' where id = p_session_id;
  update public.mentoring_zoom_room_allocations set released_at = coalesce(released_at, now())
  where intensive_session_id = p_session_id;
  update public.intensive_mentoring_session_calendar_integrations set sync_status = 'pending', sync_error = null
  where session_id = p_session_id;
  insert into public.intensive_mentoring_session_events(session_id, event_type, actor_user_id, from_status, to_status)
  values(p_session_id, 'cancelled', auth.uid(), v_session.status, 'cancelled');
  perform public.emit_notification(v_eng.mentee_id, 'mentee'::public.app_role, 'session_cancelled', 'Sesi Intensive Mentoring dibatalkan', 'Sesi Intensive Mentoring telah dibatalkan oleh admin.', 'intensive_mentoring_session', p_session_id::text, 'intensive:cancel:' || p_session_id::text);
  if v_session.mentor_id is not null then
    perform public.emit_notification(v_session.mentor_id, 'mentor'::public.app_role, 'session_cancelled', 'Sesi Intensive Mentoring dibatalkan', 'Sesi Intensive Mentoring yang ditugaskan kepada kamu telah dibatalkan.', 'intensive_mentoring_session', p_session_id::text, 'intensive:cancel:mentor:' || p_session_id::text);
  end if;
end;
$$;

create or replace function public.admin_set_intensive_session_status(p_session_id uuid, p_status text)
returns void language plpgsql security definer set search_path = '' as $$
declare v_session public.intensive_mentoring_sessions;
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  if p_status not in ('scheduled', 'completed') then raise exception 'Only scheduled/completed status transition is supported' using errcode = '22023'; end if;
  select * into v_session from public.intensive_mentoring_sessions where id = p_session_id for update;
  if not found then raise exception 'Intensive session not found' using errcode = '22023'; end if;
  if p_status = 'completed' and v_session.status <> 'scheduled' then raise exception 'Only scheduled session can be completed' using errcode = '22023'; end if;
  if p_status = 'scheduled' and v_session.status <> 'completed' then raise exception 'Only completed session can be reopened' using errcode = '22023'; end if;
  if p_status = 'scheduled' then
    perform public.reserve_mentoring_zoom_room(null, p_session_id, v_session.scheduled_start_at, v_session.scheduled_end_at, null);
  end if;
  update public.intensive_mentoring_sessions set status = p_status where id = p_session_id;
  if p_status = 'completed' then
    update public.mentoring_zoom_room_allocations set released_at = coalesce(released_at, now()) where intensive_session_id = p_session_id;
  end if;
  insert into public.intensive_mentoring_session_events(session_id, event_type, actor_user_id, from_status, to_status)
  values(p_session_id, case when p_status = 'completed' then 'completed' else 'completion_reverted' end, auth.uid(), v_session.status, p_status);
end;
$$;

create or replace function public.admin_assign_mentoring_zoom_room(
  p_session_kind text,
  p_session_id uuid,
  p_zoom_room_id uuid
)
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_start timestamptz;
  v_end timestamptz;
  v_status text;
  v_room public.mentoring_zoom_rooms;
  v_mentee_id uuid;
  v_mentor_id uuid;
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  if p_session_kind = 'private' then
    select s.scheduled_start_at, s.scheduled_end_at, s.status::text, e.mentee_id, s.mentor_id
    into v_start, v_end, v_status, v_mentee_id, v_mentor_id
    from public.private_mentoring_sessions s
    join public.private_mentoring_enrollments e on e.id = s.enrollment_id
    where s.id = p_session_id for update of s;
  elsif p_session_kind = 'intensive' then
    select s.scheduled_start_at, s.scheduled_end_at, s.status, g.mentee_id, s.mentor_id
    into v_start, v_end, v_status, v_mentee_id, v_mentor_id
    from public.intensive_mentoring_sessions s
    join public.intensive_mentoring_engagements g on g.id = s.engagement_id
    where s.id = p_session_id for update of s;
  else
    raise exception 'Jenis mentoring tidak valid' using errcode = '22023';
  end if;
  if not found then raise exception 'Sesi mentoring tidak ditemukan' using errcode = '22023'; end if;
  if v_status <> 'scheduled' or v_start is null or v_end is null then
    raise exception 'Hanya sesi terjadwal yang dapat mengganti Zoom room' using errcode = '22023';
  end if;

  if p_session_kind = 'private' then
    perform public.reserve_mentoring_zoom_room(p_session_id, null, v_start, v_end, p_zoom_room_id);
    update public.private_mentoring_session_calendar_integrations
    set sync_status = 'pending', sync_error = null
    where session_id = p_session_id;
  else
    perform public.reserve_mentoring_zoom_room(null, p_session_id, v_start, v_end, p_zoom_room_id);
    update public.intensive_mentoring_session_calendar_integrations
    set sync_status = 'pending', sync_error = null
    where session_id = p_session_id;
  end if;

  select * into v_room from public.mentoring_zoom_rooms where id = p_zoom_room_id;
  perform public.emit_notification(
    v_mentee_id,
    'mentee'::public.app_role,
    'meeting_url_changed',
    'Link Zoom sesi diperbarui',
    'Zoom room untuk sesi mentoring kamu telah diperbarui.',
    case when p_session_kind = 'private' then 'session' else 'intensive_mentoring_session' end,
    p_session_id::text,
    p_session_kind || ':zoom-room:' || p_session_id::text || ':' || p_zoom_room_id::text
  );
  if v_mentor_id is not null then
    perform public.emit_notification(
      v_mentor_id,
      'mentor'::public.app_role,
      'meeting_url_changed',
      'Link Zoom sesi diperbarui',
      'Zoom room untuk sesi mentoring yang kamu dampingi telah diperbarui.',
      case when p_session_kind = 'private' then 'session' else 'intensive_mentoring_session' end,
      p_session_id::text,
      p_session_kind || ':zoom-room:' || p_session_id::text || ':' || p_zoom_room_id::text || ':mentor'
    );
  end if;
  return jsonb_build_object('id', v_room.id, 'name', v_room.name, 'meetingUrl', v_room.meeting_url);
end;
$$;

create or replace function public.admin_get_mentoring_meeting_state(
  p_session_kind text,
  p_session_id uuid
)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare
  v_status text;
  v_start timestamptz;
  v_end timestamptz;
  v_room_id uuid;
  v_room_name text;
  v_room_url text;
  v_manual_url text;
  v_calendar_status text;
  v_calendar_error text;
  v_rooms jsonb := '[]'::jsonb;
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  if p_session_kind = 'private' then
    select s.status::text, s.scheduled_start_at, s.scheduled_end_at,
      a.zoom_room_id, r.name, r.meeting_url, ci.manual_meeting_url,
      coalesce(ci.sync_status, 'pending'), ci.sync_error
    into v_status, v_start, v_end, v_room_id, v_room_name, v_room_url, v_manual_url, v_calendar_status, v_calendar_error
    from public.private_mentoring_sessions s
    left join public.mentoring_zoom_room_allocations a on a.private_session_id = s.id
    left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
    left join public.private_mentoring_session_calendar_integrations ci on ci.session_id = s.id
    where s.id = p_session_id;
  elsif p_session_kind = 'intensive' then
    select s.status, s.scheduled_start_at, s.scheduled_end_at,
      a.zoom_room_id, r.name, r.meeting_url, ci.manual_meeting_url,
      coalesce(ci.sync_status, 'pending'), ci.sync_error
    into v_status, v_start, v_end, v_room_id, v_room_name, v_room_url, v_manual_url, v_calendar_status, v_calendar_error
    from public.intensive_mentoring_sessions s
    left join public.mentoring_zoom_room_allocations a on a.intensive_session_id = s.id
    left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
    left join public.intensive_mentoring_session_calendar_integrations ci on ci.session_id = s.id
    where s.id = p_session_id;
  else
    raise exception 'Jenis mentoring tidak valid' using errcode = '22023';
  end if;
  if not found then raise exception 'Sesi mentoring tidak ditemukan' using errcode = '22023'; end if;

  if v_status = 'scheduled' and v_start is not null and v_end is not null then
    select coalesce(jsonb_agg(jsonb_build_object(
      'id', r.id, 'name', r.name, 'meetingUrl', r.meeting_url, 'sortOrder', r.sort_order
    ) order by r.sort_order, r.name, r.id), '[]'::jsonb)
    into v_rooms
    from public.mentoring_zoom_rooms r
    where r.is_active
      and not exists (
        select 1 from public.mentoring_zoom_room_allocations a
        where a.zoom_room_id = r.id and a.released_at is null
          and not (
            a.private_session_id is not distinct from case when p_session_kind = 'private' then p_session_id end
            and a.intensive_session_id is not distinct from case when p_session_kind = 'intensive' then p_session_id end
          )
          and tstzrange(a.starts_at, a.ends_at, '[)') && tstzrange(v_start, v_end, '[)')
      );
  end if;

  return jsonb_build_object(
    'sessionId', p_session_id,
    'status', v_status,
    'assignedZoomRoomId', v_room_id,
    'assignedZoomRoomName', v_room_name,
    'managedMeetingUrl', case when v_status = 'scheduled' then v_room_url end,
    'manualMeetingUrl', case when v_status = 'scheduled' then v_manual_url end,
    'effectiveMeetingUrl', case when v_status = 'scheduled' then coalesce(v_manual_url, v_room_url) end,
    'calendarSyncStatus', v_calendar_status,
    'calendarSyncError', v_calendar_error,
    'availableZoomRooms', v_rooms
  );
end;
$$;

create or replace function public.service_get_private_mentoring_sync_context(p_session_id uuid)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_result jsonb;
begin
  if auth.role() is distinct from 'service_role' then raise exception 'Service role required' using errcode = '42501'; end if;
  select jsonb_build_object(
    'sessionId', s.id, 'sessionNumber', s.session_number, 'purchasedSessions', e.purchased_sessions, 'status', s.status,
    'focusName', coalesce(s.resolved_topic, f.name), 'resolvedTopic', s.resolved_topic,
    'start', s.scheduled_start_at, 'end', s.scheduled_end_at, 'menteeEmail', mentee_user.email, 'mentorEmail', mentor_user.email,
    'organizerUserId', ci.organizer_user_id, 'calendarId', coalesce(ci.google_calendar_id, 'primary'), 'eventId', ci.google_event_id,
    'iCalUID', ci.google_ical_uid,
    'managedMeetingUrl', case when s.status = 'scheduled' then r.meeting_url end,
    'manualMeetingUrl', case when s.status = 'scheduled' then ci.manual_meeting_url end
  ) into v_result
  from public.private_mentoring_sessions s
  join public.private_mentoring_enrollments e on e.id = s.enrollment_id
  join auth.users mentee_user on mentee_user.id = e.mentee_id
  left join auth.users mentor_user on mentor_user.id = s.mentor_id
  left join public.private_mentoring_session_focuses f on f.id = s.session_focus_id
  left join public.private_mentoring_session_calendar_integrations ci on ci.session_id = s.id
  left join public.mentoring_zoom_room_allocations a on a.private_session_id = s.id
  left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
  where s.id = p_session_id;
  if v_result is null then raise exception 'Private Mentoring session not found' using errcode = '22023'; end if;
  return v_result;
end;
$$;

create or replace function public.service_get_intensive_mentoring_sync_context(p_session_id uuid)
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_result jsonb;
begin
  if auth.role() is distinct from 'service_role' then raise exception 'Service role required' using errcode = '42501'; end if;
  select jsonb_build_object(
    'sessionId', s.id, 'sessionNumber', s.session_number, 'purchasedSessions', g.baseline_sessions_per_month, 'status', s.status,
    'focusName', coalesce(s.resolved_topic, f.name), 'resolvedTopic', s.resolved_topic,
    'start', s.scheduled_start_at, 'end', s.scheduled_end_at, 'menteeEmail', mentee.email, 'mentorEmail', mentor.email,
    'organizerUserId', ci.organizer_user_id, 'calendarId', coalesce(ci.google_calendar_id, 'primary'), 'eventId', ci.google_event_id,
    'iCalUID', ci.google_ical_uid,
    'managedMeetingUrl', case when s.status = 'scheduled' then r.meeting_url end,
    'manualMeetingUrl', case when s.status = 'scheduled' then ci.manual_meeting_url end
  ) into v_result
  from public.intensive_mentoring_sessions s
  join public.intensive_mentoring_engagements g on g.id = s.engagement_id
  join auth.users mentee on mentee.id = g.mentee_id
  left join auth.users mentor on mentor.id = s.mentor_id
  left join public.private_mentoring_session_focuses f on f.id = s.session_focus_id
  left join public.intensive_mentoring_session_calendar_integrations ci on ci.session_id = s.id
  left join public.mentoring_zoom_room_allocations a on a.intensive_session_id = s.id
  left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
  where s.id = p_session_id;
  if v_result is null then raise exception 'Intensive session not found' using errcode = '22023'; end if;
  return v_result;
end;
$$;

drop function if exists public.list_my_private_mentoring_sessions_v2();
create function public.list_my_private_mentoring_sessions_v2()
returns table(
  session_id uuid, enrollment_id uuid, session_number integer, status text,
  session_focus_id uuid, focus_name text, requested_focus_id uuid, mentee_topic_request text, topic_status text, resolved_topic text,
  mentor_id uuid, mentor_name text, primary_mentor_id uuid, primary_mentor_name text,
  scheduled_start_at timestamptz, scheduled_end_at timestamptz,
  mentor_tier_code text, mentor_tier_name text, package_id uuid, purchased_sessions integer,
  mentor_timezone text, duration_minutes integer, meeting_url text, google_event_id text, google_ical_uid text, google_sync_status text
)
language sql stable security definer set search_path = '' as $$
  select s.id, e.id, s.session_number, s.status::text, s.session_focus_id, f.name::text, s.requested_focus_id, s.mentee_topic_request, s.topic_status, s.resolved_topic,
    s.mentor_id, nullif(btrim(concat_ws(' ', mp.first_name, mp.last_name)), ''), e.primary_mentor_id, nullif(btrim(concat_ws(' ', primary_profile.first_name, primary_profile.last_name)), ''),
    s.scheduled_start_at, s.scheduled_end_at, t.code, t.name, e.package_id, e.purchased_sessions, mentor_profile.timezone, pkg.duration_minutes,
    case when s.status = 'scheduled' then coalesce(ci.manual_meeting_url, r.meeting_url) end,
    ci.google_event_id, ci.google_ical_uid, coalesce(ci.sync_status, 'pending')
  from public.private_mentoring_sessions s
  join public.private_mentoring_enrollments e on e.id = s.enrollment_id
  join public.private_mentoring_packages pkg on pkg.id = e.package_id
  join public.mentor_tiers t on t.id = pkg.mentor_tier_id
  left join public.private_mentoring_session_focuses f on f.id = s.session_focus_id
  left join public.profiles mp on mp.id = s.mentor_id
  left join public.profiles primary_profile on primary_profile.id = e.primary_mentor_id
  left join public.mentor_profiles mentor_profile on mentor_profile.user_id = s.mentor_id
  left join public.private_mentoring_session_calendar_integrations ci on ci.session_id = s.id
  left join public.mentoring_zoom_room_allocations a on a.private_session_id = s.id
  left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
  where e.mentee_id = auth.uid()
  order by e.created_at desc, s.session_number;
$$;

drop function if exists public.list_my_mentor_private_mentoring_sessions();
create function public.list_my_mentor_private_mentoring_sessions()
returns table(
  session_id uuid, enrollment_id uuid, mentee_id uuid, mentee_name text, mentee_email text,
  session_number integer, purchased_sessions integer, status text, focus_name text, resolved_topic text, mentor_scope_notes text,
  scheduled_start_at timestamptz, scheduled_end_at timestamptz, mentor_timezone text, duration_minutes integer,
  meeting_url text, google_event_id text, google_ical_uid text, google_sync_status text
)
language sql stable security definer set search_path = '' as $$
  select s.id, e.id, e.mentee_id, nullif(btrim(concat_ws(' ', p.first_name, p.last_name)), ''), coalesce(u.email, '')::text,
    s.session_number, e.purchased_sessions, s.status::text, coalesce(s.resolved_topic, f.name)::text, s.resolved_topic, s.mentor_scope_notes,
    s.scheduled_start_at, s.scheduled_end_at, mentor_profile.timezone, pkg.duration_minutes,
    case when s.status = 'scheduled' then coalesce(ci.manual_meeting_url, r.meeting_url) end,
    ci.google_event_id, ci.google_ical_uid, coalesce(ci.sync_status, 'pending')
  from public.private_mentoring_sessions s
  join public.private_mentoring_enrollments e on e.id = s.enrollment_id
  join public.private_mentoring_packages pkg on pkg.id = e.package_id
  join public.profiles p on p.id = e.mentee_id
  join auth.users u on u.id = e.mentee_id
  join public.mentor_profiles mentor_profile on mentor_profile.user_id = s.mentor_id
  left join public.private_mentoring_session_focuses f on f.id = s.session_focus_id
  left join public.private_mentoring_session_calendar_integrations ci on ci.session_id = s.id
  left join public.mentoring_zoom_room_allocations a on a.private_session_id = s.id
  left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
  where s.mentor_id = auth.uid()
  order by s.scheduled_start_at nulls last, s.session_number;
$$;

drop function if exists public.list_admin_private_mentoring_calendar_sessions(timestamptz, timestamptz);
create function public.list_admin_private_mentoring_calendar_sessions(p_from timestamptz, p_to timestamptz)
returns table(
  session_id uuid, enrollment_id uuid, mentee_id uuid, mentee_name text, mentee_email text,
  mentor_id uuid, mentor_name text, mentor_tier_name text, session_number integer, purchased_sessions integer,
  status text, focus_name text, scheduled_start_at timestamptz, scheduled_end_at timestamptz, mentor_timezone text, duration_minutes integer,
  meeting_url text, managed_meeting_url text, manual_meeting_url text, zoom_room_name text,
  google_event_id text, google_ical_uid text, google_sync_status text, google_sync_error text
)
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  return query
  select s.id, e.id, e.mentee_id, nullif(btrim(concat_ws(' ', mentee.first_name, mentee.last_name)), ''), coalesce(mu.email, '')::text,
    s.mentor_id, nullif(btrim(concat_ws(' ', mentor.first_name, mentor.last_name)), ''), tier.name,
    s.session_number, e.purchased_sessions, s.status::text, coalesce(s.resolved_topic, f.name)::text, s.scheduled_start_at, s.scheduled_end_at, mentor_profile.timezone, pkg.duration_minutes,
    case when s.status = 'scheduled' then coalesce(ci.manual_meeting_url, r.meeting_url) end,
    case when s.status = 'scheduled' then r.meeting_url end,
    case when s.status = 'scheduled' then ci.manual_meeting_url end,
    r.name,
    ci.google_event_id, ci.google_ical_uid, coalesce(ci.sync_status, 'pending'), ci.sync_error
  from public.private_mentoring_sessions s
  join public.private_mentoring_enrollments e on e.id = s.enrollment_id
  join public.private_mentoring_packages pkg on pkg.id = e.package_id
  join public.mentor_tiers tier on tier.id = pkg.mentor_tier_id
  join public.profiles mentee on mentee.id = e.mentee_id
  join auth.users mu on mu.id = e.mentee_id
  left join public.profiles mentor on mentor.id = s.mentor_id
  left join public.mentor_profiles mentor_profile on mentor_profile.user_id = s.mentor_id
  left join public.private_mentoring_session_focuses f on f.id = s.session_focus_id
  left join public.private_mentoring_session_calendar_integrations ci on ci.session_id = s.id
  left join public.mentoring_zoom_room_allocations a on a.private_session_id = s.id
  left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
  where s.status <> 'cancelled' and s.scheduled_start_at is not null
    and (p_from is null or s.scheduled_end_at > p_from)
    and (p_to is null or s.scheduled_start_at < p_to)
  order by s.scheduled_start_at, s.id;
end;
$$;

drop function if exists public.list_my_intensive_mentoring_engagements();
create function public.list_my_intensive_mentoring_engagements()
returns table(
  engagement_id uuid, base_entitlement_id uuid, base_kind text, program_name text, status text, baseline_sessions_per_month integer,
  primary_mentor_id uuid, primary_mentor_name text, competition_name text, program_stage text, current_activity text, progress_summary text, started_at timestamptz,
  add_ons jsonb, sessions jsonb
)
language sql stable security definer set search_path = '' as $$
  select g.id, g.base_entitlement_id, e.entitlement_kind, coalesce(p.name, b.name, o.title)::text, g.status, g.baseline_sessions_per_month, g.primary_mentor_id,
    nullif(btrim(concat_ws(' ', mentor.first_name, mentor.last_name)), '')::text, g.competition_name, g.program_stage, g.current_activity, g.progress_summary, g.started_at,
    public.intensive_engagement_add_ons_json(g.id),
    coalesce((
      select jsonb_agg(jsonb_build_object(
        'sessionId', s.id, 'sessionNumber', s.session_number, 'durationMinutes', s.duration_minutes, 'status', s.status,
        'focusId', s.session_focus_id, 'focusName', f.name, 'menteeTopicRequest', s.mentee_topic_request,
        'topicStatus', s.topic_status, 'resolvedTopic', s.resolved_topic, 'mentorId', s.mentor_id,
        'mentorName', nullif(btrim(concat_ws(' ', sm.first_name, sm.last_name)), ''),
        'scheduledStartAt', s.scheduled_start_at, 'scheduledEndAt', s.scheduled_end_at,
        'meetingUrl', case when s.status = 'scheduled' then coalesce(ci.manual_meeting_url, r.meeting_url) end,
        'zoomRoomId', a.zoom_room_id, 'zoomRoomName', r.name,
        'googleSyncStatus', coalesce(ci.sync_status, 'pending'), 'creationSource', s.creation_source
      ) order by s.session_number)
      from public.intensive_mentoring_sessions s
      left join public.private_mentoring_session_focuses f on f.id = s.session_focus_id
      left join public.profiles sm on sm.id = s.mentor_id
      left join public.intensive_mentoring_session_calendar_integrations ci on ci.session_id = s.id
      left join public.mentoring_zoom_room_allocations a on a.intensive_session_id = s.id
      left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
      where s.engagement_id = g.id
    ), '[]'::jsonb)
  from public.intensive_mentoring_engagements g
  join public.intensive_mentoring_entitlements e on e.id = g.base_entitlement_id
  left join public.intensive_mentoring_packages p on p.id = e.package_id
  left join public.intensive_mentoring_bundles b on b.id = e.bundle_id
  left join public.intensive_mentoring_custom_offers o on o.id = e.custom_offer_id
  left join public.profiles mentor on mentor.id = g.primary_mentor_id
  where g.mentee_id = auth.uid()
  order by g.created_at desc, g.id;
$$;

drop function if exists public.list_admin_intensive_mentoring_engagements();
create function public.list_admin_intensive_mentoring_engagements()
returns table(
  engagement_id uuid, mentee_id uuid, mentee_name text, mentee_email text, base_entitlement_id uuid, base_kind text, program_name text, status text,
  baseline_sessions_per_month integer, primary_mentor_id uuid, primary_mentor_name text, program_stage text, current_activity text, progress_summary text, created_at timestamptz,
  add_ons jsonb, sessions jsonb, unassigned_add_ons jsonb
)
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  return query
  select g.id, g.mentee_id, nullif(btrim(concat_ws(' ', mp.first_name, mp.last_name)), ''), coalesce(mu.email, '')::text,
    g.base_entitlement_id, e.entitlement_kind, coalesce(p.name, b.name, o.title)::text, g.status, g.baseline_sessions_per_month,
    g.primary_mentor_id, nullif(btrim(concat_ws(' ', mentor.first_name, mentor.last_name)), '')::text,
    g.program_stage, g.current_activity, g.progress_summary, g.created_at,
    public.intensive_engagement_add_ons_json(g.id),
    coalesce((
      select jsonb_agg(jsonb_build_object(
        'sessionId', s.id, 'sessionNumber', s.session_number, 'durationMinutes', s.duration_minutes, 'status', s.status,
        'focusId', s.session_focus_id, 'focusName', f.name, 'menteeTopicRequest', s.mentee_topic_request,
        'topicStatus', s.topic_status, 'resolvedTopic', s.resolved_topic, 'mentorId', s.mentor_id,
        'mentorName', nullif(btrim(concat_ws(' ', sm.first_name, sm.last_name)), ''),
        'scheduledStartAt', s.scheduled_start_at, 'scheduledEndAt', s.scheduled_end_at,
        'meetingUrl', case when s.status = 'scheduled' then coalesce(ci.manual_meeting_url, r.meeting_url) end,
        'zoomRoomId', a.zoom_room_id, 'zoomRoomName', r.name,
        'googleSyncStatus', coalesce(ci.sync_status, 'pending'),
        'creationSource', s.creation_source, 'creationReason', s.creation_reason
      ) order by s.session_number)
      from public.intensive_mentoring_sessions s
      left join public.private_mentoring_session_focuses f on f.id = s.session_focus_id
      left join public.profiles sm on sm.id = s.mentor_id
      left join public.intensive_mentoring_session_calendar_integrations ci on ci.session_id = s.id
      left join public.mentoring_zoom_room_allocations a on a.intensive_session_id = s.id
      left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
      where s.engagement_id = g.id
    ), '[]'::jsonb),
    coalesce((
      select jsonb_agg(jsonb_build_object('entitlementId', a.id, 'name', ao.name, 'code', ao.code, 'createdAt', a.created_at) order by a.created_at, a.id)
      from public.intensive_mentoring_entitlements a
      join public.intensive_mentoring_add_ons ao on ao.id = a.add_on_id
      where a.mentee_id = g.mentee_id and a.entitlement_kind = 'add_on' and a.engagement_id is null
    ), '[]'::jsonb)
  from public.intensive_mentoring_engagements g
  join public.intensive_mentoring_entitlements e on e.id = g.base_entitlement_id
  join public.profiles mp on mp.id = g.mentee_id
  join auth.users mu on mu.id = g.mentee_id
  left join public.intensive_mentoring_packages p on p.id = e.package_id
  left join public.intensive_mentoring_bundles b on b.id = e.bundle_id
  left join public.intensive_mentoring_custom_offers o on o.id = e.custom_offer_id
  left join public.profiles mentor on mentor.id = g.primary_mentor_id
  order by g.created_at desc, g.id;
end;
$$;

drop function if exists public.list_my_mentor_intensive_mentoring_sessions();
create function public.list_my_mentor_intensive_mentoring_sessions()
returns table(
  session_id uuid, engagement_id uuid, mentee_id uuid, mentee_name text, mentee_email text, program_name text,
  session_number integer, status text, focus_name text, resolved_topic text,
  scheduled_start_at timestamptz, scheduled_end_at timestamptz, mentor_timezone text, duration_minutes integer,
  meeting_url text, google_event_id text, google_ical_uid text, google_sync_status text, add_ons jsonb
)
language sql stable security definer set search_path = '' as $$
  select s.id, g.id, g.mentee_id, nullif(btrim(concat_ws(' ', mp.first_name, mp.last_name)), ''), coalesce(mu.email, '')::text,
    coalesce(p.name, b.name, o.title)::text, s.session_number, s.status, f.name, s.resolved_topic,
    s.scheduled_start_at, s.scheduled_end_at, mentor_profile.timezone, s.duration_minutes,
    case when s.status = 'scheduled' then coalesce(ci.manual_meeting_url, r.meeting_url) end,
    ci.google_event_id, ci.google_ical_uid, coalesce(ci.sync_status, 'pending'), public.intensive_engagement_add_ons_json(g.id)
  from public.intensive_mentoring_sessions s
  join public.intensive_mentoring_engagements g on g.id = s.engagement_id
  join public.intensive_mentoring_entitlements e on e.id = g.base_entitlement_id
  join public.profiles mp on mp.id = g.mentee_id
  join auth.users mu on mu.id = g.mentee_id
  join public.mentor_profiles mentor_profile on mentor_profile.user_id = s.mentor_id
  left join public.intensive_mentoring_packages p on p.id = e.package_id
  left join public.intensive_mentoring_bundles b on b.id = e.bundle_id
  left join public.intensive_mentoring_custom_offers o on o.id = e.custom_offer_id
  left join public.private_mentoring_session_focuses f on f.id = s.session_focus_id
  left join public.intensive_mentoring_session_calendar_integrations ci on ci.session_id = s.id
  left join public.mentoring_zoom_room_allocations a on a.intensive_session_id = s.id
  left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
  where s.mentor_id = auth.uid()
  order by s.scheduled_start_at nulls last, s.session_number;
$$;

drop function if exists public.list_admin_intensive_mentoring_calendar_sessions(timestamptz, timestamptz);
create function public.list_admin_intensive_mentoring_calendar_sessions(p_from timestamptz, p_to timestamptz)
returns table(
  session_id uuid, enrollment_id uuid, mentee_id uuid, mentee_name text, mentee_email text,
  mentor_id uuid, mentor_name text, mentor_tier_name text, session_number integer, purchased_sessions integer,
  status text, focus_name text, scheduled_start_at timestamptz, scheduled_end_at timestamptz, mentor_timezone text, duration_minutes integer,
  meeting_url text, managed_meeting_url text, manual_meeting_url text, zoom_room_name text,
  google_event_id text, google_ical_uid text, google_sync_status text, google_sync_error text
)
language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.is_admin() then raise exception 'Admin required' using errcode = '42501'; end if;
  return query
  select s.id, g.id, g.mentee_id, nullif(btrim(concat_ws(' ', mentee.first_name, mentee.last_name)), ''), coalesce(mu.email, '')::text,
    s.mentor_id, nullif(btrim(concat_ws(' ', mentor.first_name, mentor.last_name)), ''), tier.name,
    s.session_number, g.baseline_sessions_per_month, s.status, coalesce(s.resolved_topic, f.name)::text,
    s.scheduled_start_at, s.scheduled_end_at, mp.timezone, s.duration_minutes,
    case when s.status = 'scheduled' then coalesce(ci.manual_meeting_url, r.meeting_url) end,
    case when s.status = 'scheduled' then r.meeting_url end,
    case when s.status = 'scheduled' then ci.manual_meeting_url end,
    r.name,
    ci.google_event_id, ci.google_ical_uid, coalesce(ci.sync_status, 'pending'), ci.sync_error
  from public.intensive_mentoring_sessions s
  join public.intensive_mentoring_engagements g on g.id = s.engagement_id
  join public.profiles mentee on mentee.id = g.mentee_id
  join auth.users mu on mu.id = g.mentee_id
  left join public.profiles mentor on mentor.id = s.mentor_id
  left join public.mentor_profiles mp on mp.user_id = s.mentor_id
  left join public.mentor_tiers tier on tier.id = mp.tier_id
  left join public.private_mentoring_session_focuses f on f.id = s.session_focus_id
  left join public.intensive_mentoring_session_calendar_integrations ci on ci.session_id = s.id
  left join public.mentoring_zoom_room_allocations a on a.intensive_session_id = s.id
  left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
  where s.status <> 'cancelled' and s.scheduled_start_at is not null
    and (p_from is null or s.scheduled_end_at > p_from)
    and (p_to is null or s.scheduled_start_at < p_to)
  order by s.scheduled_start_at, s.id;
end;
$$;

drop function if exists public.list_my_intensive_mentoring_calendar_sessions();
create function public.list_my_intensive_mentoring_calendar_sessions()
returns table(
  session_id uuid, enrollment_id uuid, mentee_id uuid, mentee_name text, mentee_email text,
  mentor_id uuid, mentor_name text, mentor_tier_name text, session_number integer, purchased_sessions integer,
  status text, focus_name text, scheduled_start_at timestamptz, scheduled_end_at timestamptz, mentor_timezone text, duration_minutes integer,
  meeting_url text, managed_meeting_url text, manual_meeting_url text, zoom_room_name text,
  google_event_id text, google_ical_uid text, google_sync_status text, google_sync_error text
)
language sql stable security definer set search_path = '' as $$
  select s.id, g.id, g.mentee_id, nullif(btrim(concat_ws(' ', mentee.first_name, mentee.last_name)), ''), ''::text,
    s.mentor_id, nullif(btrim(concat_ws(' ', mentor.first_name, mentor.last_name)), ''), tier.name,
    s.session_number, g.baseline_sessions_per_month, s.status, coalesce(s.resolved_topic, f.name)::text,
    s.scheduled_start_at, s.scheduled_end_at, mp.timezone, s.duration_minutes,
    case when s.status = 'scheduled' then coalesce(ci.manual_meeting_url, r.meeting_url) end,
    null::text, null::text, r.name,
    ci.google_event_id, ci.google_ical_uid, coalesce(ci.sync_status, 'pending'), null::text
  from public.intensive_mentoring_sessions s
  join public.intensive_mentoring_engagements g on g.id = s.engagement_id
  join public.profiles mentee on mentee.id = g.mentee_id
  left join public.profiles mentor on mentor.id = s.mentor_id
  left join public.mentor_profiles mp on mp.user_id = s.mentor_id
  left join public.mentor_tiers tier on tier.id = mp.tier_id
  left join public.private_mentoring_session_focuses f on f.id = s.session_focus_id
  left join public.intensive_mentoring_session_calendar_integrations ci on ci.session_id = s.id
  left join public.mentoring_zoom_room_allocations a on a.intensive_session_id = s.id
  left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
  where g.mentee_id = auth.uid() and s.status <> 'cancelled'
  order by s.scheduled_start_at nulls last, s.session_number;
$$;

create or replace function public.notify_private_mentoring_integration_changes()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  v_mentee uuid;
  v_mentor uuid;
  v_room_url text;
  v_effective text;
  v_old_effective text;
begin
  select e.mentee_id, s.mentor_id, r.meeting_url
  into v_mentee, v_mentor, v_room_url
  from public.private_mentoring_sessions s
  join public.private_mentoring_enrollments e on e.id = s.enrollment_id
  left join public.mentoring_zoom_room_allocations a on a.private_session_id = s.id
  left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
  where s.id = new.session_id;
  v_effective := coalesce(new.manual_meeting_url, v_room_url);
  v_old_effective := coalesce(old.manual_meeting_url, v_room_url);
  if v_effective is distinct from v_old_effective and v_effective is not null then
    if v_mentor is not null then
      perform public.emit_notification(v_mentor, 'mentor'::public.app_role, 'meeting_url_changed', 'Meeting link tersedia',
        'Meeting link sesi mentoring tersedia atau berubah.', 'session', new.session_id::text,
        'session:' || new.session_id || ':meeting:' || md5(v_effective) || ':mentor');
    end if;
    perform public.emit_notification(v_mentee, 'mentee'::public.app_role, 'meeting_url_changed', 'Meeting link tersedia',
      'Meeting link sesi mentoring tersedia atau berubah.', 'session', new.session_id::text,
      'session:' || new.session_id || ':meeting:' || md5(v_effective) || ':mentee');
  end if;
  if new.sync_status = 'failed' and old.sync_status is distinct from 'failed' then
    perform public.emit_notification(null, 'admin'::public.app_role, 'calendar_failed', 'Google Calendar sync gagal',
      coalesce(new.sync_error, 'Google Calendar belum tersinkron.'), 'session', new.session_id::text,
      'session:' || new.session_id || ':calendar-failed:' || md5(coalesce(new.sync_error, '')));
  end if;
  return new;
end;
$$;

create or replace function public.notify_intensive_mentoring_integration_changes()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  v_mentee uuid;
  v_mentor uuid;
  v_room_url text;
  v_effective text;
  v_old_effective text;
begin
  select g.mentee_id, s.mentor_id, r.meeting_url
  into v_mentee, v_mentor, v_room_url
  from public.intensive_mentoring_sessions s
  join public.intensive_mentoring_engagements g on g.id = s.engagement_id
  left join public.mentoring_zoom_room_allocations a on a.intensive_session_id = s.id
  left join public.mentoring_zoom_rooms r on r.id = a.zoom_room_id
  where s.id = new.session_id;
  v_effective := coalesce(new.manual_meeting_url, v_room_url);
  v_old_effective := coalesce(old.manual_meeting_url, v_room_url);
  if v_effective is distinct from v_old_effective and v_effective is not null then
    if v_mentor is not null then
      perform public.emit_notification(v_mentor, 'mentor'::public.app_role, 'meeting_url_changed', 'Meeting link Intensive tersedia',
        'Meeting link sesi Intensive Mentoring tersedia atau berubah.', 'intensive_mentoring_session', new.session_id::text,
        'intensive:session:' || new.session_id || ':meeting:' || md5(v_effective) || ':mentor');
    end if;
    perform public.emit_notification(v_mentee, 'mentee'::public.app_role, 'meeting_url_changed', 'Meeting link Intensive tersedia',
      'Meeting link sesi Intensive Mentoring tersedia atau berubah.', 'intensive_mentoring_session', new.session_id::text,
      'intensive:session:' || new.session_id || ':meeting:' || md5(v_effective) || ':mentee');
  end if;
  if new.sync_status = 'failed' and old.sync_status is distinct from 'failed' then
    perform public.emit_notification(null, 'admin'::public.app_role, 'calendar_failed', 'Google Calendar Intensive sync gagal',
      coalesce(new.sync_error, 'Google Calendar Intensive belum tersinkron.'), 'intensive_mentoring_session', new.session_id::text,
      'intensive:session:' || new.session_id || ':calendar-failed:' || md5(coalesce(new.sync_error, '')));
  end if;
  return new;
end;
$$;

create or replace function public.invalidate_zoom_room_allocation_changes()
returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_private_session_id uuid;
  v_intensive_session_id uuid;
  v_mentee_id uuid;
  v_mentor_id uuid;
begin
  if tg_op = 'DELETE' then
    v_private_session_id := old.private_session_id;
    v_intensive_session_id := old.intensive_session_id;
  else
    v_private_session_id := new.private_session_id;
    v_intensive_session_id := new.intensive_session_id;
  end if;

  perform public.bump_operational_invalidation('admin'::public.app_role, null, 'provider');
  perform public.bump_operational_invalidation('admin'::public.app_role, null, 'calendar');
  perform public.bump_operational_invalidation('admin'::public.app_role, null, 'availability');

  if v_private_session_id is not null then
    select e.mentee_id, s.mentor_id into v_mentee_id, v_mentor_id
    from public.private_mentoring_sessions s
    join public.private_mentoring_enrollments e on e.id = s.enrollment_id
    where s.id = v_private_session_id;
  else
    select g.mentee_id, s.mentor_id into v_mentee_id, v_mentor_id
    from public.intensive_mentoring_sessions s
    join public.intensive_mentoring_engagements g on g.id = s.engagement_id
    where s.id = v_intensive_session_id;
  end if;

  if v_mentee_id is not null then
    perform public.bump_operational_invalidation('mentee'::public.app_role, v_mentee_id, 'provider');
    perform public.bump_operational_invalidation('mentee'::public.app_role, v_mentee_id, 'calendar');
    perform public.bump_operational_invalidation('mentee'::public.app_role, v_mentee_id, 'mentoring');
  end if;
  if v_mentor_id is not null then
    perform public.bump_operational_invalidation('mentor'::public.app_role, v_mentor_id, 'provider');
    perform public.bump_operational_invalidation('mentor'::public.app_role, v_mentor_id, 'calendar');
    perform public.bump_operational_invalidation('mentor'::public.app_role, v_mentor_id, 'mentor-dashboard');
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

create trigger zoom_room_allocations_operational_invalidation
after insert or update or delete on public.mentoring_zoom_room_allocations
for each row execute function public.invalidate_zoom_room_allocation_changes();

create or replace function public.invalidate_managed_zoom_room_changes()
returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_room_id uuid;
  v_allocation record;
begin
  v_room_id := case when tg_op = 'DELETE' then old.id else new.id end;
  perform public.bump_operational_invalidation('admin'::public.app_role, null, 'provider');
  perform public.bump_operational_invalidation('admin'::public.app_role, null, 'availability');
  perform public.bump_operational_invalidation('admin'::public.app_role, null, 'calendar');

  if tg_op = 'UPDATE' and (
    old.meeting_url is distinct from new.meeting_url
    or old.name is distinct from new.name
    or old.is_active is distinct from new.is_active
  ) then
    for v_allocation in
      select a.private_session_id, a.intensive_session_id,
        coalesce(pe.mentee_id, ig.mentee_id) as mentee_id,
        coalesce(ps.mentor_id, ins.mentor_id) as mentor_id
      from public.mentoring_zoom_room_allocations a
      left join public.private_mentoring_sessions ps on ps.id = a.private_session_id
      left join public.private_mentoring_enrollments pe on pe.id = ps.enrollment_id
      left join public.intensive_mentoring_sessions ins on ins.id = a.intensive_session_id
      left join public.intensive_mentoring_engagements ig on ig.id = ins.engagement_id
      where a.zoom_room_id = v_room_id and a.released_at is null and a.ends_at > now()
    loop
      if v_allocation.mentee_id is not null then
        perform public.bump_operational_invalidation('mentee'::public.app_role, v_allocation.mentee_id, 'provider');
        perform public.bump_operational_invalidation('mentee'::public.app_role, v_allocation.mentee_id, 'calendar');
        perform public.bump_operational_invalidation('mentee'::public.app_role, v_allocation.mentee_id, 'mentoring');
      end if;
      if v_allocation.mentor_id is not null then
        perform public.bump_operational_invalidation('mentor'::public.app_role, v_allocation.mentor_id, 'provider');
        perform public.bump_operational_invalidation('mentor'::public.app_role, v_allocation.mentor_id, 'calendar');
        perform public.bump_operational_invalidation('mentor'::public.app_role, v_allocation.mentor_id, 'mentor-dashboard');
      end if;
    end loop;
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

create trigger managed_zoom_rooms_operational_invalidation
after insert or update or delete on public.mentoring_zoom_rooms
for each row execute function public.invalidate_managed_zoom_room_changes();

-- The old provider RPCs remain only as migration provenance and are no longer executable at runtime.
revoke all on function public.service_get_zoom_meeting_context(uuid) from service_role;
revoke all on function public.service_claim_zoom_meeting_creation(uuid) from service_role;
revoke all on function public.service_store_zoom_meeting(uuid, text, text, text, text, text) from service_role;
revoke all on function public.service_mark_zoom_sync(uuid, text, text) from service_role;
revoke all on function public.service_get_intensive_zoom_meeting_context(uuid) from service_role;
revoke all on function public.service_claim_intensive_zoom_meeting_creation(uuid) from service_role;
revoke all on function public.service_store_intensive_zoom_meeting(uuid, text, text, text, text, text) from service_role;
revoke all on function public.service_mark_intensive_zoom_sync(uuid, text, text) from service_role;

revoke all on function public.reserve_mentoring_zoom_room(uuid, uuid, timestamptz, timestamptz, uuid)
from public, anon, authenticated;
grant execute on function public.reserve_mentoring_zoom_room(uuid, uuid, timestamptz, timestamptz, uuid)
to service_role;

revoke all on function
  public.admin_list_mentoring_zoom_rooms(),
  public.admin_upsert_mentoring_zoom_room(uuid, text, text, boolean, integer),
  public.admin_delete_mentoring_zoom_room(uuid),
  public.admin_get_mentoring_zoom_room_pool(timestamptz, timestamptz, uuid, uuid),
  public.admin_assign_mentoring_zoom_room(text, uuid, uuid),
  public.admin_get_mentoring_meeting_state(text, uuid),
  public.admin_schedule_private_mentoring_session(uuid, uuid, timestamptz, uuid),
  public.admin_schedule_intensive_mentoring_session(uuid, uuid, timestamptz, uuid)
from public, anon;

grant execute on function
  public.admin_list_mentoring_zoom_rooms(),
  public.admin_upsert_mentoring_zoom_room(uuid, text, text, boolean, integer),
  public.admin_delete_mentoring_zoom_room(uuid),
  public.admin_get_mentoring_zoom_room_pool(timestamptz, timestamptz, uuid, uuid),
  public.admin_assign_mentoring_zoom_room(text, uuid, uuid),
  public.admin_get_mentoring_meeting_state(text, uuid),
  public.admin_schedule_private_mentoring_session(uuid, uuid, timestamptz, uuid),
  public.admin_schedule_intensive_mentoring_session(uuid, uuid, timestamptz, uuid)
to authenticated, service_role;

revoke all on function
  public.list_my_private_mentoring_sessions_v2(),
  public.list_my_mentor_private_mentoring_sessions(),
  public.list_admin_private_mentoring_calendar_sessions(timestamptz, timestamptz),
  public.list_my_intensive_mentoring_engagements(),
  public.list_admin_intensive_mentoring_engagements(),
  public.list_my_mentor_intensive_mentoring_sessions(),
  public.list_admin_intensive_mentoring_calendar_sessions(timestamptz, timestamptz),
  public.list_my_intensive_mentoring_calendar_sessions()
from public, anon;

grant execute on function
  public.list_my_private_mentoring_sessions_v2(),
  public.list_my_mentor_private_mentoring_sessions(),
  public.list_admin_private_mentoring_calendar_sessions(timestamptz, timestamptz),
  public.list_my_intensive_mentoring_engagements(),
  public.list_admin_intensive_mentoring_engagements(),
  public.list_my_mentor_intensive_mentoring_sessions(),
  public.list_admin_intensive_mentoring_calendar_sessions(timestamptz, timestamptz),
  public.list_my_intensive_mentoring_calendar_sessions()
to authenticated, service_role;

revoke all on function
  public.service_get_private_mentoring_sync_context(uuid),
  public.service_get_intensive_mentoring_sync_context(uuid)
from public, anon, authenticated;
grant execute on function
  public.service_get_private_mentoring_sync_context(uuid),
  public.service_get_intensive_mentoring_sync_context(uuid)
to service_role;

revoke all on function
  public.list_my_private_mentoring_sessions_v2(),
  public.list_my_mentor_private_mentoring_sessions(),
  public.list_admin_private_mentoring_calendar_sessions(timestamptz, timestamptz),
  public.list_my_intensive_mentoring_engagements(),
  public.list_admin_intensive_mentoring_engagements(),
  public.list_my_mentor_intensive_mentoring_sessions(),
  public.list_admin_intensive_mentoring_calendar_sessions(timestamptz, timestamptz),
  public.list_my_intensive_mentoring_calendar_sessions()
from public, anon;

grant execute on function
  public.list_my_private_mentoring_sessions_v2(),
  public.list_my_mentor_private_mentoring_sessions(),
  public.list_admin_private_mentoring_calendar_sessions(timestamptz, timestamptz),
  public.list_my_intensive_mentoring_engagements(),
  public.list_admin_intensive_mentoring_engagements(),
  public.list_my_mentor_intensive_mentoring_sessions(),
  public.list_admin_intensive_mentoring_calendar_sessions(timestamptz, timestamptz),
  public.list_my_intensive_mentoring_calendar_sessions()
to authenticated, service_role;

comment on table public.mentoring_zoom_rooms is
  'Admin-managed reusable Zoom room inventory. Active row count defines mentoring concurrency capacity.';
comment on table public.mentoring_zoom_room_allocations is
  'Shared Private/Intensive Zoom room reservations. The exclusion constraint enforces one overlapping session per room.';
comment on column public.private_mentoring_session_calendar_integrations.provider_meeting_url is
  'Legacy Zoom API audit value only. Active runtime links resolve from manual_meeting_url or mentoring_zoom_rooms.';
comment on column public.intensive_mentoring_session_calendar_integrations.provider_meeting_url is
  'Legacy Zoom API audit value only. Active runtime links resolve from manual_meeting_url or mentoring_zoom_rooms.';
