import 'server-only'
import { createClient } from '@/lib/supabase/server'
import type { IntensiveMentoringEntitlementView,PrivateMentoringCatalogView,PrivateMentoringSessionView } from './types'

type PrivateSessionRow={session_id:string;enrollment_id:string;session_number:number;status:PrivateMentoringSessionView['status'];session_focus_id:string|null;focus_name:string|null;requested_focus_id:string|null;mentee_topic_request:string|null;topic_status:PrivateMentoringSessionView['topicStatus'];resolved_topic:string|null;mentor_id:string|null;mentor_name:string|null;primary_mentor_id:string|null;primary_mentor_name:string|null;scheduled_start_at:string|null;scheduled_end_at:string|null;mentor_tier_code:string;mentor_tier_name:string;package_id:string;purchased_sessions:number;mentor_timezone:string|null;duration_minutes:number;meeting_url:string|null;google_event_id:string|null;google_ical_uid:string|null;google_sync_status:PrivateMentoringSessionView['googleSyncStatus']}
type IntensiveEntitlementRow={entitlement_id:string;order_item_id:string;entitlement_kind:IntensiveMentoringEntitlementView['entitlementKind'];name:string;purchased_sessions:number|null;status:IntensiveMentoringEntitlementView['status'];created_at:string}
type RpcClient={rpc<T>(name:string,args?:Record<string,unknown>):Promise<{data:T|null;error:{message:string}|null}>}

export async function getPublicPrivateMentoringCatalog():Promise<PrivateMentoringCatalogView|null>{const supabase=await createClient();const[pathsResult,focusesResult,categoriesResult,packagesResult,tiersResult]=await Promise.all([supabase.from('private_mentoring_learning_paths').select('*').eq('is_active',true).order('sort_order').order('id'),supabase.from('private_mentoring_session_focuses').select('*').eq('is_active',true).order('sort_order').order('id'),supabase.from('competition_categories').select('*').eq('is_active',true).order('sort_order').order('id'),supabase.from('private_mentoring_packages').select('*').eq('is_active',true).order('sort_order').order('id'),supabase.from('mentor_tiers').select('*').eq('is_active',true).order('sort_order').order('id')]);const results=[pathsResult,focusesResult,categoriesResult,packagesResult,tiersResult];const failed=results.find(result=>result.error);if(failed?.error){console.error('Private Mentoring catalog unavailable',failed.error.message);return null}const tiers=tiersResult.data??[];const tierById=new Map(tiers.map(tier=>[tier.id,tier]));const packages=(packagesResult.data??[]).flatMap(packageRow=>{const tier=tierById.get(packageRow.mentor_tier_id);if(!tier)return[];return[{id:packageRow.id,mentorTierId:tier.id,mentorTierCode:tier.code,mentorTierName:tier.name,sessionCount:packageRow.session_count,priceAmount:Number(packageRow.price_amount),referencePriceAmount:packageRow.reference_price_amount===null?null:Number(packageRow.reference_price_amount),pricePerSession:Math.round(Number(packageRow.price_amount) / packageRow.session_count),durationMinutes:packageRow.duration_minutes,maxParticipants:packageRow.max_participants,sortOrder:packageRow.sort_order}]});return{learningPaths:(pathsResult.data??[]).map(row=>({id:row.id,code:row.code,slug:row.slug,name:row.name,description:row.description,sortOrder:row.sort_order})),sessionFocuses:(focusesResult.data??[]).map(row=>({id:row.id,code:row.code,slug:row.slug,name:row.name,description:row.description,sortOrder:row.sort_order})),competitionCategories:(categoriesResult.data??[]).map(row=>({id:row.id,code:row.code,slug:row.slug,name:row.name,sortOrder:row.sort_order})),packages}}

export async function listMyPrivateMentoringSessions():Promise<PrivateMentoringSessionView[]>{const supabase=await createClient();const rpc=supabase as unknown as RpcClient;const{data,error}=await rpc.rpc<PrivateSessionRow[]>('list_my_private_mentoring_sessions_v2');if(error){console.error('Private Mentoring sessions unavailable',error.message);return[]}return(data??[]).map(row=>({sessionId:row.session_id,enrollmentId:row.enrollment_id,sessionNumber:row.session_number,status:row.status,sessionFocusId:row.session_focus_id,focusName:row.focus_name,requestedFocusId:row.requested_focus_id,menteeTopicRequest:row.mentee_topic_request,topicStatus:row.topic_status,resolvedTopic:row.resolved_topic,mentorId:row.mentor_id,mentorName:row.mentor_name,primaryMentorId:row.primary_mentor_id,primaryMentorName:row.primary_mentor_name,scheduledStartAt:row.scheduled_start_at,scheduledEndAt:row.scheduled_end_at,mentorTierCode:row.mentor_tier_code,mentorTierName:row.mentor_tier_name,packageId:row.package_id,purchasedSessions:row.purchased_sessions,mentorTimezone:row.mentor_timezone,durationMinutes:row.duration_minutes,meetingUrl:row.meeting_url,googleEventId:row.google_event_id,googleICalUid:row.google_ical_uid,googleSyncStatus:row.google_sync_status}))}

export async function listMyIntensiveMentoringEntitlements():Promise<IntensiveMentoringEntitlementView[]>{const supabase=await createClient();const rpc=supabase as unknown as RpcClient;const{data,error}=await rpc.rpc<IntensiveEntitlementRow[]>('list_my_intensive_mentoring_entitlements');if(error){console.error('Intensive Mentoring entitlements unavailable',error.message);return[]}return(data??[]).map(row=>({entitlementId:row.entitlement_id,orderItemId:row.order_item_id,entitlementKind:row.entitlement_kind,name:row.name,purchasedSessions:row.purchased_sessions,status:row.status,createdAt:row.created_at}))}
